// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with {type:'json'};
import source from '../data/arkpedia-hoederer-prefabs.json' with {type:'json'};
import {HOEDERER_OPERATORS as configs} from '../shared/arkpedia/hoederer-operators.js';
import {StandardBattle} from '../server/sim/arkpedia.js';
import {defaultBuild} from '../shared/arkpedia/loadout.js';
import {acquireTargets,effectiveProfile} from '../server/sim/ai.js';
const ID='char_4088_hodrer',ALLY='char_208_melan',OTHER='char_337_utage';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const rows=r=>r.flatMap(x=>x.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id=ID,{skill=0,rank=10,elite=null,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} source snapshot needed`);elite??=op.phases.length-1;rank=Math.min(rank,elite===2?10:elite===1?7:4);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,potential,skillId:op.skills[skill].id,skillRank:rank};}
function make(opts={},more=[]){const d=structuredClone(data);d.stage.geometry.waves[0].spawns=[];d.stage.battle.dp_per_second=0;const b=new StandardBattle(d,{operators:[build(ID,opts),...more.map(id=>build(id))]});b.setViewport('fullscreen-workspace');b.autoFinish=false;b.recordEvents=true;b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));rng(b,[.99]);b.receipts=[];b.on('damaged',c=>b.receipts.push({...c,time:b.time}));return{b,deploy:(id=ID,r=3,c=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,r,c,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;}};}
function rng(b,values){let n=0;const old=b.rng;const r=()=>values[Math.min(n++,values.length-1)];r.pick=old.pick;r.int=old.int;r.chance=p=>r()<p;b.rng=r;return()=>n;}
function advance(b,s){for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);}
function enemy(b,{r=3,c=5,hp=100000,def=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[r,c]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:0});e.def={...e.def,immune:new Set(e.def.immune)};e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',persist:true,flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,r,c){e.x=c;e.y=r;e.tileR=r;e.tileC=c;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(u){u.skill.setSpTotal(u.skill.spCost);assert.equal(u.skill.activate('test'),true);u.atkCd=1000;}
function shot(b,u,targets){assert.equal(b.forceAttack(u,targets==null?undefined:Array.isArray(targets)?targets:[targets]),true);u.atkCd=1000;}
function atkEvent(b,u){return b._evq.filter(x=>x[0]==='atk'&&x[1]===u.id).at(-1)[4];}
function victimReceipts(b,e){return b.receipts.filter(c=>c.target===e);}
function active(b,u){cast(u);advance(b,1.6);}

test('Hoederer retains full original3skills, four verified bundles and both official facing identities',()=>{assert.deepEqual(Object.keys(configs),[ID]);assert.equal(source.frameParity,false);assert.equal(source.sourceBundles.length,4);for(const x of source.sourceBundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);for(const f of['Front','Back'])assert.equal(source.originalModels[ID][f].sha256,source.officialSkeletonBindings[ID][f].sha256);const c=rows(source.characters[ID]);for(const id of['4434281238489574836','5374150808936230324','-5456309651121263180']){const a=c.find(x=>x.pathId===id);assert.equal(a._maxAnimScale,1);const q=c.find(x=>x.pathId===a._selector.m_PathID);assert.equal(q._limitedMaxTargetNumToBlockedCnt,1);assert.equal(q._allowZeroBlockCntLimit,0);}const s2=rows(source.skills.skchr_hodrer_2).find(x=>x.pathId==='-4179552938929335778');assert.equal(s2._switchToMode,1);assert.equal(s2._restartFSM,0);assert.equal(source.buffTemplates['hodrer_s_3[periodic]'].eventToActions.ON_BUFF_TRIGGER[0]._damageType,'PURE');assert.ok(source.verificationLimits.some(x=>x.includes('ON_ABILITY_SPELL_ON')));});
test('all thirty skill ranks and E0/E1/E2 records instantiate complete source-specific kits',()=>{for(let skill=0;skill<3;skill++)for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill,rank}),u=deploy();assert.equal(u.skill.id,configs[ID].skillIds[skill]);assert.equal(u.skill.noSkill,false);assert.deepEqual(b.errors,[]);}for(const elite of[0,1,2]){const{deploy}=make({elite}),u=deploy();assert.equal(u.def.talents.length,elite===0?0:elite===1?1:2);}});
test('normal source.7 release is one direct separately mitigated ground hit per selected victim',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{def:100});shot(b,u,e);near(atkEvent(b,u).windup,.7);assert.equal(atkEvent(b,u).animation,'Attack');advance(b,.65);near(e.hp,100000);advance(b,.15);near(100000-e.hp,u.s.atk*1.1-100);assert.equal(b.projectiles.list.length,0);assert.equal(victimReceipts(b,e)[0].dmg.applyWay,'melee');});
test('native cap1 animation playback remains .7 at excess ASPD and slows at low ASPD',()=>{for(const[aspd,t]of[[200,.7],[-50,1.4]]){const{b,deploy}=make(),u=deploy(),e=enemy(b);b.addBuff(u,{key:'test:aspd',mods:{aspd}});shot(b,u,e);near(atkEvent(b,u).windup,t);advance(b,t+.1);near(100000-e.hp,u.s.atk*1.1);}});
test('Crusher ordinary target count follows current block capacity with blocked priority and in-range enemies',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{r:3,c:3}),a=enemy(b),z=enemy(b,{c:5.1}),air=enemy(b,{fly:true});e.blockedBy=u;u.blocking=[e];let targets=acquireTargets(b,u,effectiveProfile(u));assert.equal(targets.length,2);assert.equal(targets[0],e);assert.ok(!targets.includes(air));b.addBuff(u,{key:'test:block',mods:{blockCnt:1}});targets=acquireTargets(b,u,effectiveProfile(u));assert.equal(targets.length,3);assert.ok(targets.includes(a)&&targets.includes(z));b.addBuff(u,{key:'test:no-block',mods:{blockCntMul:0}});assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,1);});
test('natural multi-victim ordinary loop emits each damage once without blanket-AoE duplication',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1}),extra=enemy(b,{c:5.2});u.atkCd=0;b.step();u.atkCd=1000;advance(b,.8);assert.equal(u.stats.attacks,1);near(300000-e.hp-z.hp-extra.hp,2*u.s.atk*1.1);assert.equal(b.receipts.filter(c=>c.source===u&&c.target.side==='enemy').length,2);});
test('native CAST normal selection reselects victims at release and excludes air or hidden targets',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b),z=enemy(b,{r:1,c:8}),air=enemy(b,{fly:true}),hidden=enemy(b);hidden.hidden=true;shot(b,u,e);b.kill(e);move(b,z,3,5);advance(b,.8);near(100000-z.hp,u.s.atk*1.1);near(air.hp,100000);near(hidden.hp,100000);});
test('T1 selected E1/E2 uses pre-mitigation ordinary or stunned/bound scale, not generic post-DEF damage',()=>{for(const[elite,plain,strong]of[[1,1.05,1.25],[2,1.1,1.4]])for(const status of[null,'stun','bind','sluggish']){const{b,deploy}=make({elite}),u=deploy(),e=enemy(b,{def:150});if(status)b.applyStatus(e,status,{duration:5});shot(b,u,e);advance(b,.8);near(100000-e.hp,u.s.atk*(status==='stun'||status==='bind'?strong:plain)-150);}});
test('T1 reads victim control at actual release, so removing or adding Bind during windup changes scale',()=>{for(const how of['add','remove']){const{b,deploy}=make(),u=deploy(),e=enemy(b);if(how==='remove')b.applyStatus(e,'bind',{duration:5,key:'test:bind'});shot(b,u,e);if(how==='add')b.applyStatus(e,'bind',{duration:5,key:'test:bind'});else b.removeBuff(e,'test:bind');advance(b,.8);near(100000-e.hp,u.s.atk*(how==='add'?1.4:1.1));}});
test('E2 Sanctuary covers self and directly behind all friendly unit types, not sideways/forward',()=>{const{b,deploy}=make({},[ALLY,OTHER]),u=deploy(),a=deploy(ALLY,3,3),z=deploy(OTHER,3,5);advance(b,.05);near(u.s.physTakenMul,.82);near(a.s.artsTakenMul,.82);near(z.s.physTakenMul,1);assert.equal(z.profile.noHeal,true);move(b,z,3,3);move(b,a,2,4);advance(b,.05);near(z.s.physTakenMul,.82);near(a.s.physTakenMul,1);});
test('Sanctuary selected potential gives21percent and does not scale True damage or HP loss',()=>{const{b,deploy}=make({potential:5}),u=deploy(),e=enemy(b);advance(b,.05);near(u.s.physTakenMul,.79);let hp=u.hp;b.dealDamage(e,u,{amount:100,type:'phys'});near(hp-u.hp,79);hp=u.hp;b.dealDamage(e,u,{amount:100,type:'arts'});near(hp-u.hp,79);hp=u.hp;b.dealDamage(e,u,{amount:100,type:'true'});near(hp-u.hp,100);hp=u.hp;b.loseHp(u,100);near(hp-u.hp,100);});
test('Sanctuary strongest owned source falls back and unrelated aura survives Hoederer withdrawal',()=>{const{b,deploy}=make({},[ALLY]),u=deploy(),a=deploy(ALLY,3,3);advance(b,.05);b.applyStatus(a,'sanctuary',{key:'other:strong',value:.4,duration:.15});b.applyStatus(a,'sanctuary',{key:'other:weak',value:.1});near(a.s.physTakenMul,.6);advance(b,.25);near(a.s.physTakenMul,.82);b.retreatOperator(ID);near(a.s.physTakenMul,.9);assert.ok(a.findBuff('other:weak'));assert.ok(!a.findBuff(`hoederer:sanctuary:${u.id}`));});
test('Sanctuary reevaluates target-free and friendly isolation without broadening healability gates',()=>{const{b,deploy}=make({},[ALLY]),u=deploy(),a=deploy(ALLY,3,3);advance(b,.05);for(const flag of['untargetable','isolated']){b.addBuff(a,{key:'test:gate',flags:{[flag]:true}});advance(b,.05);near(a.s.physTakenMul,1);b.removeBuff(a,'test:gate');advance(b,.05);near(a.s.physTakenMul,.82);}b.addBuff(a,{key:'test:heal-free',flags:{healFree:true,noHeal:true}});advance(b,.05);near(a.s.physTakenMul,.82);});
test('S1 all ranks heal once per attack family and apply selected scale to each native-cap victim',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({rank}),u=deploy(),e=enemy(b,{def:100}),z=enemy(b,{c:5.1,def:100});u.hp=u.s.maxHp*.1;cast(u);shot(b,u,[e,z]);near(u.hp,u.s.maxHp*(.1+u.skill.bb.hp_ratio));assert.equal(atkEvent(b,u).animation,'Skill_1');advance(b,.8);for(const x of[e,z])near(100000-x.hp,u.s.atk*u.skill.bb.atk_scale*1.1-100);assert.equal(u.skill.charges,0);assert.equal(u.skill.active,false);}});
test('S1 INPUT keeps original startup victims, without replacing a living hidden input',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1});cast(u);shot(b,u,e);e.hidden=true;advance(b,.8);near(e.hp,100000);near(z.hp,100000);assert.equal(u.skill.charges,0);});
test('S1 source dead-input recovery refunds before emission only, never emitted own kill',()=>{for(const why of['dead','own-kill']){const{b,deploy}=make(),u=deploy(),e=enemy(b,{hp:why==='own-kill'?1:100000});cast(u);shot(b,u,e);if(why==='dead')b.kill(e);advance(b,.8);assert.equal(u.skill.charges,why==='dead'?1:0);assert.equal(e.alive,false);}});
test('S1 heal respects actual HealFree but self noHeal is independent from allied heal selectors',()=>{for(const flag of['healFree','noHeal']){const{b,deploy}=make(),u=deploy(),e=enemy(b);u.hp=100;b.addBuff(u,{key:'test:heal',flags:{[flag]:true}});cast(u);shot(b,u,e);near(u.hp,flag==='healFree'?100:100+u.s.maxHp*.25);}});
test('S1 sub-tick accepted control cancels unborn damage and preserves pending override without a dead-input refund',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);u.hp=100;cast(u);shot(b,u,e);const hp=u.hp;b.applyStatus(u,'stun',{duration:.001});advance(b,.8);near(e.hp,100000);near(u.hp,hp);assert.equal(u.skill.pending,true);assert.equal(u.skill.charges,0);});
test('S2 selected passive ATK applies before first cast and remains in both paid states at every rank',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:1,rank}),u=deploy();near(u.s.atk,u.base.atk*(1+u.skill.bb.atk));cast(u);assert.equal(u.mem.hoedererStance,true);assert.equal(u.skill.active,false);near(u.s.atk,u.base.atk*(1+u.skill.bb.atk));advance(b,.25);cast(u);assert.equal(u.mem.hoedererStance,false);near(u.s.atk,u.base.atk*(1+u.skill.bb.atk));}});
test('S2 flat BAT+.5 and block+1 preserve unrelated flat/percentage terms and restore only owned stats',()=>{const{b,deploy}=make({skill:1}),u=deploy();b.addBuff(u,{key:'external',mods:{batFlat:.4,batPct:.2,blockCnt:1,atkPct:.1}});cast(u);near(u.s.bat,(u.base.bat+.4+.5)*1.2);near(u.s.blockCnt,u.base.blockCnt+2);near(u.s.atk,u.base.atk*(1+.1+u.skill.bb.atk));advance(b,.25);cast(u);near(u.s.bat,(u.base.bat+.4)*1.2);near(u.s.blockCnt,u.base.blockCnt+1);assert.ok(u.findBuff('external'));});
test('S2 switching back requires another full selected SP cost and naturally recharges while stance persists',()=>{const{b,deploy}=make({skill:1}),u=deploy();cast(u);assert.equal(u.skill.activate('test'),false);advance(b,4.9);assert.equal(u.skill.ready,false);advance(b,.45);assert.equal(u.skill.ready,true);assert.equal(u.skill.activate('test'),true);assert.equal(u.mem.hoedererStance,false);near(u.skill.spTotal,0);});
test('S2 actual block-capacity3 includes ordinary unblocked legal victims and no fourth target',()=>{const{b,deploy}=make({skill:1}),u=deploy(),es=[enemy(b),enemy(b,{c:5.1}),enemy(b,{c:5.2}),enemy(b,{c:5.3})];cast(u);advance(b,.25);assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,3);shot(b,u);advance(b,.9);near(es.reduce((n,e)=>n+100000-e.hp,0),3*u.s.atk*1.4);assert.equal(es.filter(e=>e.hp<100000).length,3);});
test('S2 original A/B.767 clips alternate, cap1 is retained, successful new Stun uses stronger T1',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{def:100});cast(u);advance(b,.25);for(const expected of['Skill_2_Loop_A','Skill_2_Loop_B']){const hp=e.hp;shot(b,u,e);assert.equal(atkEvent(b,u).animation,expected);near(atkEvent(b,u).windup,.767);advance(b,.9);near(hp-e.hp,u.s.atk*1.4-100);assert.equal(e.s.flags.stun,true);}});
test('S2 rejected Stun immunity retains ordinary T1 while accepted Resist halves the stun duration',()=>{for(const immune of[true,false]){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);if(immune)e.def.immune.add('stun');else b.applyStatus(e,'resist',{source:u,duration:5,value:.5});cast(u);advance(b,.25);shot(b,u,e);advance(b,.85);near(100000-e.hp,u.s.atk*(immune?1.1:1.4));if(immune)assert.equal(Boolean(e.s.flags.stun),false);else{advance(b,.6);assert.equal(Boolean(e.s.flags.stun),false);}}});
test('S2 natural3second attack cadence is not accelerated to the original2.5second visual duration',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(u);advance(b,.25);u.atkCd=0;advance(b,3.9);assert.equal(u.stats.attacks,2);assert.equal(victimReceipts(b,e).length,2);});
test('S3 all ranks apply seventy-second HP/ATK and forward range with original literal startup/end forms',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:2,rank}),u=deploy();b.addBuff(u,{key:'external',mods:{hpPct:.1,atkPct:.2}});const before=new Set(u.rangeKeys);cast(u);near(u.s.maxHp,u.base.maxHp*(1+.1+u.skill.bb.max_hp));near(u.s.atk,u.base.atk*(1+.2+u.skill.bb.atk));near(u.skill.timeLeft,70);assert.equal(u.mem.regularFormVisual.clip,'Skill_3_Begin');assert.ok(u.s.flags.disarm);assert.ok(u.rangeKeys.length>before.size);advance(b,1.6);assert.equal(u.mem.regularFormVisual.clip,'Skill_3_Idle');assert.equal(Boolean(u.s.flags.disarm),false);u.skill.end('duration');assert.equal(u.mem.regularFormVisual.clip,'Skill_3_End');advance(b,.3);near(u.s.atk,u.base.atk*1.2);near(u.s.maxHp,u.base.maxHp*1.1);assert.equal(u.mem.regularFormVisual,null);assert.ok(u.findBuff('external'));}});
test('S3 source1.5s startup gates ordinary attacks while direct self-drain clock begins at activation',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(u);const hp=u.hp;u.atkCd=0;advance(b,1.4);near(e.hp,100000);near(hp-u.hp,100);assert.equal(u.stats.attacks,0);advance(b,1);assert.equal(u.stats.attacks,1);assert.ok(e.hp<100000);});
test('S3 each accepted family heals fivepercent exactly once despite two victims, respecting healing modifiers',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1});active(b,u);u.hp=1000;b.addBuff(u,{key:'heal-mod',mods:{healingDealtMul:1.5,healingTakenMul:.5}});shot(b,u,[e,z]);near(u.hp,1000+u.s.maxHp*.05*.75);});
test('S3 explicit per-victim stun probability and original Down/Back source event remain independent',()=>{for(const dir of['RIGHT','LEFT','DOWN','UP']){const{b,deploy}=make({skill:2}),u=deploy(ID,3,4,dir),e=enemy(b,{r:dir==='DOWN'?2:dir==='UP'?4:3,c:dir==='LEFT'?3:dir==='RIGHT'?5:4}),z=enemy(b,{r:e.y,c:e.x+.05});active(b,u);rng(b,[0,.99]);shot(b,u,[e,z]);assert.equal(atkEvent(b,u).animation,dir==='DOWN'?'Skill_Down_3_Loop':'Skill_3_Loop');advance(b,.8);assert.equal(e.s.flags.stun,true);assert.equal(Boolean(z.s.flags.stun),false);near(100000-e.hp,u.s.atk*1.4);near(100000-z.hp,u.s.atk*1.1);}});
test('S3 forward extension actually acquires front2 with normal ground-only capacity cap',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{c:6}),air=enemy(b,{c:6,fly:true}),side=enemy(b,{r:2,c:6});assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);active(b,u);const targets=acquireTargets(b,u,effectiveProfile(u));assert.ok(targets.includes(e));assert.ok(!targets.includes(air)&&!targets.includes(side));shot(b,u);advance(b,.8);assert.ok(e.hp<100000);u.skill.end('duration');advance(b,.3);assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);});
test('S3 output marks have exact1s wait-first tick and repeated hits do not reset the existing cadence',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);active(b,u);b.dealDamage(u,e,{amount:1,type:'phys'});const hp=e.hp;advance(b,.6);near(e.hp,hp);b.dealDamage(u,e,{amount:1,type:'phys'});const next=e.hp;advance(b,.5);near(next-e.hp,200);const buff=e.findBuff(`hoederer:burn:${u.id}`);assert.ok(buff);assert.equal(e.buffs.filter(x=>x.key===buff.key).length,1);});
test('S3 incoming damage marks enemy sources even air/out-of-range and outgoing marks share source-owned key',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{r:1,c:8,fly:true}),other=enemy(b);active(b,u);b.dealDamage(e,u,{amount:1,type:'true'});b.dealDamage(u,other,{amount:1,type:'true'});assert.ok(e.findBuff(`hoederer:burn:${u.id}`));assert.ok(other.findBuff(`hoederer:burn:${u.id}`));const a=e.hp,z=other.hp;advance(b,1.1);near(a-e.hp,200);near(z-other.hp,200);});
test('S3 pre-mitigation marks retain explicit dodged/shielded mapping but exclude invulnerable/HP loss/element gauge',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b),shield=enemy(b),invuln=enemy(b),gauge=enemy(b);active(b,u);b.addBuff(e,{key:'dodge',mods:{dodgePhys:1}});b.addBuff(shield,{key:'shield',shield:1000});b.addBuff(invuln,{key:'invuln',flags:{invulnerable:true}});rng(b,[0]);b.dealDamage(u,e,{amount:1,type:'phys'});b.dealDamage(u,shield,{amount:1,type:'phys'});b.dealDamage(u,invuln,{amount:1,type:'phys'});b.dealDamage(u,gauge,{amount:1,type:'element',element:'burn'});b.loseHp(gauge,1,{source:u});assert.ok(e.findBuff(`hoederer:burn:${u.id}`));assert.ok(shield.findBuff(`hoederer:burn:${u.id}`));assert.ok(!invuln.findBuff(`hoederer:burn:${u.id}`));assert.ok(!gauge.findBuff(`hoederer:burn:${u.id}`));});
test('S3 true sourceless DoT ignores owner ATK/talent/outgoing buffs but keeps target Fragile/shields and credit',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);active(b,u);b.dealDamage(u,e,{amount:1,type:'true'});b.addBuff(u,{key:'outgoing',mods:{dmgDealtMul:10,atkPct:100}});b.applyStatus(e,'bind',{duration:5});b.applyStatus(e,'fragile',{value:.5});b.addBuff(e,{key:'test:shield',shield:100});const hp=e.hp,stats=u.stats.dmg;advance(b,1.1);near(hp-e.hp,200);near(u.stats.dmg-stats,200);const tick=victimReceipts(b,e).find(c=>c.dmg.tags.includes('hoederer:burn'));assert.equal(tick.source,null);assert.equal(tick.credit,u);assert.equal(tick.dmg.applyWay,'none');});
test('S3 derived marks continue outside range/target-free while owned marks clear on skill finish and preserve foreign buff',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);active(b,u);b.dealDamage(u,e,{amount:1,type:'true'});b.addBuff(e,{key:'hoederer:burn:other',source:u,mods:{defPct:-.1}});move(b,e,1,8);b.addBuff(e,{key:'free',flags:{untargetable:true,stealth:true}});const hp=e.hp;advance(b,1.1);near(hp-e.hp,200);u.skill.end('duration');assert.ok(!e.findBuff(`hoederer:burn:${u.id}`));assert.ok(e.findBuff('hoederer:burn:other'));const after=e.hp;advance(b,2);near(e.hp,after);});
test('S3 direct self100HP drain bypasses shields/Fragile and remains lethal without granting hurt-SP',()=>{const{b,deploy}=make({skill:2}),u=deploy();cast(u);u.hp=150;b.addBuff(u,{key:'shield',shield:10000});b.addBuff(u,{key:'fragile',mods:{dmgTakenMul:10}});advance(b,1.1);near(u.hp,50);assert.ok(u.findBuff('shield').shield>=10000);near(u.skill.spTotal,0);advance(b,1);assert.equal(u.alive,false);assert.ok(!u.findBuff('hoederer:drain'));});
test('S3 source/control interruption cancels unborn ordinary strikes while autonomous marks keep parent lifetime',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b),z=enemy(b);active(b,u);b.dealDamage(u,z,{amount:1,type:'true'});shot(b,u,e);b.applyStatus(u,'stun',{duration:.001});advance(b,.8);near(e.hp,100000);const hp=z.hp;advance(b,.4);near(hp-z.hp,200);});
test('S3 retreat or source death clears all own derived marks/aura/forms while next deployment starts clean',()=>{for(const why of['retreat','death']){const{b,deploy}=make({skill:2},[ALLY]),u=deploy(),a=deploy(ALLY,3,3),e=enemy(b);active(b,u);b.dealDamage(u,e,{amount:1,type:'true'});if(why==='retreat')b.retreatOperator(ID);else b.kill(u);assert.ok(!e.findBuff(`hoederer:burn:${u.id}`));assert.ok(!a.findBuff(`hoederer:sanctuary:${u.id}`));assert.equal(u.mem.regularFormVisual,null);const hp=e.hp;advance(b,2);near(e.hp,hp);if(why==='retreat'){b.bench[ID].readyAt=b.time;const v=deploy();assert.equal(v.mem.hoedererStance,false);assert.ok(!v.findBuff('hoederer:drain'));}}});
test('actual sourceless marked enemy death preserves Hoederer kill credit without new recursive mark',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{hp:201});active(b,u);let killer=null;b.on('kill',c=>{if(c.victim===e)killer=c.killer;});b.dealDamage(u,e,{amount:1,type:'true'});advance(b,1.1);assert.equal(e.alive,false);assert.equal(killer,u);assert.equal(e.buffs.filter(x=>x.key===`hoederer:burn:${u.id}`).length,1);const receipts=victimReceipts(b,e).length;advance(b,2);near(e.hp,0);assert.equal(victimReceipts(b,e).length,receipts);});
test('native noSP during bounded S2 Begin/End excludes gifts until mode transition finishes',()=>{const{b,deploy}=make({skill:1}),u=deploy();cast(u);near(u.skill.gainSp(2,'talent'),0);advance(b,.25);assert.equal(u.skill.gainSp(2,'talent'),2);cast(u);near(u.skill.gainSp(2,'talent'),0);advance(b,.25);assert.equal(u.skill.gainSp(2,'talent'),2);});
