// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with {type:'json'};
import source from '../data/arkpedia-bagpipe-prefabs.json' with {type:'json'};
import {BAGPIPE_OPERATORS as configs} from '../shared/arkpedia/bagpipe-operators.js';
import {StandardBattle} from '../server/sim/arkpedia.js';
import {defaultBuild} from '../shared/arkpedia/loadout.js';
import {acquireTargets,effectiveProfile} from '../server/sim/ai.js';
const ID='char_222_bpipe',FANG='char_123_fang',MYRTLE='char_151_myrtle',KROOS='char_124_kroos';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const rows=r=>r.flatMap(x=>x.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id=ID,{skill=0,rank=10,elite=null,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} source snapshot needed`);elite??=op.phases.length-1;rank=Math.min(rank,elite===2?10:elite===1?7:4);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,potential,skillId:op.skills[skill].id,skillRank:rank};}
function make(opts={},more=[],support=false){const d=structuredClone(data);d.stage.geometry.waves[0].spawns=[];d.stage.battle.dp_per_second=0;const b=new StandardBattle(d,support?{operators:more.map(id=>build(id)),support:{id:ID,skillId:'skchr_bpipe_3'}}:{operators:[build(ID,opts),...more.map(id=>build(id))]});b.setViewport('fullscreen-workspace');b.autoFinish=false;b.recordEvents=true;b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));rng(b,[.99]);b.receipts=[];b.on('damaged',c=>{if(c.source?.defId===ID&&c.dmg)b.receipts.push({...c,time:b.time});});return{b,deploy:(id=ID,r=3,c=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,r,c,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;}};}
function rng(b,values){let n=0;const old=b.rng;const r=()=>values[Math.min(n++,values.length-1)];r.pick=old.pick;r.int=old.int;r.chance=p=>r()<p;b.rng=r;return()=>n;}
function advance(b,s){for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);}
function enemy(b,{r=3,c=5,hp=100000,def=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[r,c]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:0});e.def={...e.def,immune:new Set(e.def.immune)};e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',persist:true,flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,r,c){e.x=c;e.y=r;e.tileR=r;e.tileC=c;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(u){u.skill.setSpTotal(u.skill.spCost);assert.equal(u.skill.activate('test'),true);u.atkCd=1000;}
function shot(b,u,e){assert.equal(b.forceAttack(u,e?[e]:undefined),true);u.atkCd=1000;}
function atkEvent(b,u){return b._evq.filter(x=>x[0]==='atk'&&x[1]===u.id).at(-1)[4];}

test('Bagpipe preserves all3 original skills, four verified bundles, actual facing bytes and distinct SP/crit contracts',()=>{assert.deepEqual(Object.keys(configs),[ID]);assert.equal(configs[ID].criticalTalent,false);assert.equal(source.frameParity,false);assert.equal(source.sourceBundles.length,4);for(const x of source.sourceBundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);for(const f of['Front','Back'])assert.equal(source.originalModels[ID][f].sha256,source.officialSkeletonBindings[ID][f].sha256);const s2=rows(source.skills.skchr_bpipe_2).find(x=>x.pathId==='6121859831695212308');assert.equal(s2._additionalTimes,1);assert.equal(s2._waitAttackEventForAllAttacks,1);assert.equal(s2._selectTargetTiming,1);assert.equal(s2._splitDamage,0);const s3=rows(source.characters[ID]).find(x=>x.pathId==='-4722877676851957677');assert.equal(s3._additionalTimes,2);assert.equal(source.buffTemplates.bpipe_t_1.eventToActions.ON_CALCULATE_DAMAGE[1]._probKey,'prob');assert.equal(source.independentCalculator.gitBlobSha1,'05e6f1c21ae08c0db954a43e937800f788acc65a');assert.ok(source.verificationLimits.some(x=>x.includes('SplashDamage')));});
test('all thirty skill ranks and selected E1/E2/potential records instantiate with no inherited critical shortcut',()=>{for(let skill=0;skill<3;skill++)for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill,rank}),u=deploy();assert.equal(u.skill.id,configs[ID].skillIds[skill]);assert.equal(u.skill.noSkill,false);assert.equal(u.def.raw.arkpedia.critical,undefined);assert.deepEqual(b.errors,[]);}const{deploy}=make({elite:0,rank:4}),u=deploy();assert.equal(u.def.talents.length,0);});
test('ordinary first begin + capped loop release is one direct separately mitigated ground hit',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{def:100});shot(b,u,e);const a=atkEvent(b,u);near(a.windup,.167+.267);assert.deepEqual(a.animation,{begin:'Attack_Begin',loop:'Attack_Loop',beginDuration:.167});advance(b,.4);near(e.hp,100000);advance(b,.15);near(100000-e.hp,u.s.atk-100);assert.equal(b.projectiles.list.length,0);assert.equal(b.receipts[0].dmg.applyWay,'melee');});
test('first-only begin samples unrestricted controller rate while normal release honors ability cap1',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);b.addBuff(u,{key:'aspd',mods:{aspd:200}});shot(b,u,e);near(atkEvent(b,u).windup,.167/3+.267);advance(b,.7);shot(b,u,e);near(atkEvent(b,u).windup,.267);assert.equal(atkEvent(b,u).animation,'Attack_Loop');});
test('normal CAST replaces dead original startup input and never acquires flying enemy',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1}),air=enemy(b,{fly:true});shot(b,u,e);b.kill(e);advance(b,.6);near(100000-z.hp,u.s.atk);near(air.hp,100000);assert.equal(u.stats.attacks,1);});
test('talent selected E1/E2/potential rolls once per calculated damage and boosts ATK before DEF',()=>{for(const[elite,potential,scale,prob]of[[1,1,1.1,.25],[1,3,1.1,.28],[2,1,1.3,.25],[2,3,1.3,.28]]){const{b,deploy}=make({elite,potential,rank:7}),u=deploy(),e=enemy(b,{def:150});const t=u.def.talents.find(t=>t.bb.prob).bb;near(t.atk_scale,scale);near(t.prob,prob);const count=rng(b,[0]);shot(b,u,e);advance(b,.6);near(100000-e.hp,u.s.atk*scale-150);assert.equal(count(),1);}});
test('S2 two events roll separately and an extra receipt never recursively rolls',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{def:100}),z=enemy(b,{c:5.1,def:100}),count=rng(b,[0,.99]);cast(u);shot(b,u,e);advance(b,.8);near(100000-e.hp,u.s.atk*2*(1.3+1)-200);near(100000-z.hp,u.s.atk*2*1.3-100);assert.equal(count(),2);assert.equal(u.stats.attacks,1);assert.equal(b.receipts.length,3);});
test('S3 triple events roll independently with two separately mitigated crit extra receipts',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{def:100}),z=enemy(b,{c:5.1,def:100}),count=rng(b,[0,.99,0]);cast(u);shot(b,u,e);advance(b,1);near(100000-e.hp,u.s.atk*(1.3+1+1.3)-300);near(100000-z.hp,2*(u.s.atk*1.3-100));assert.equal(count(),3);assert.equal(u.stats.attacks,1);assert.equal(b.receipts.length,5);});
test('extra victim cap1 excludes primary and ignores out-of-range/flying/hidden/target-free inputs',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1}),other=enemy(b,{c:5.2}),outside=enemy(b,{c:6}),air=enemy(b,{fly:true}),free=enemy(b),hidden=enemy(b);hidden.hidden=true;b.addBuff(free,{key:'free',flags:{untargetable:true}});rng(b,[0]);shot(b,u,e);advance(b,.6);near(100000-e.hp,u.s.atk*1.3);near(100000-z.hp+100000-other.hp,u.s.atk*1.3);for(const x of[outside,air,free,hidden])near(x.hp,100000);assert.equal(b.receipts.length,2);});
test('each later spell reselects extra membership instead of retaining startup extra target',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b),z=enemy(b,{r:1,c:8});rng(b,[0]);cast(u);shot(b,u,e);advance(b,.32);assert.equal(b.receipts.length,1);move(b,z,3,5.1);advance(b,.25);near(100000-z.hp,u.s.atk*2*1.3);assert.equal(b.receipts.length,3);});
test('crit extra stays ordinary melee and dodge of main does not suppress its independent receipt',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1});b.addBuff(e,{key:'dodge',mods:{dodgePhys:1}});rng(b,[0]);shot(b,u,e);advance(b,.6);near(e.hp,100000);near(100000-z.hp,u.s.atk*1.3);const c=b.receipts.find(c=>c.target===z);assert.equal(c.dmg.applyWay,'melee');assert.equal(c.dmg.isAttack,true);assert.ok(c.dmg.tags.includes('bagpipe:duplicate-lock'));});
test('S1 all ranks apply35s selected additive ATK/ASPD and clean only owned modifiers',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({rank}),u=deploy();b.addBuff(u,{key:'external',mods:{atkPct:.2,aspd:7}});cast(u);near(u.s.atk,u.base.atk*(1.2+u.skill.bb.atk));near(u.s.aspd,107+u.skill.bb.attack_speed);near(u.skill.timeLeft,35);u.skill.end('test');near(u.s.atk,u.base.atk*1.2);near(u.s.aspd,107);assert.ok(u.findBuff('external'));}});
test('S2 all ranks have two original event deadlines, separate full damage and selected charge capacity',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:1,rank}),u=deploy(),e=enemy(b,{def:100});cast(u);shot(b,u,e);near(atkEvent(b,u).windup,.267);advance(b,.32);near(100000-e.hp,u.s.atk*u.skill.bb.atk_scale-100);advance(b,.25);near(100000-e.hp,2*(u.s.atk*u.skill.bb.atk_scale-100));assert.equal(b.receipts.length,2);assert.equal(u.skill.maxCharges,u.skill.bb.cnt);assert.equal(u.skill.charges,0);}});
test('S2 time SP naturally refills selected three charges and never grants during a timed S3',()=>{const{b,deploy}=make({skill:1}),u=deploy();u.skill.setSpTotal(0);advance(b,12.05);assert.equal(u.skill.charges,3);near(u.skill.spTotal,12);const f=make({skill:2}),v=f.deploy();cast(v);advance(f.b,2);near(v.skill.spTotal,0);});
test('S2 input timing1 retains startup primary rather than selecting a later live alternative',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1});cast(u);shot(b,u,e);b.addBuff(e,{key:'free',flags:{untargetable:true}});advance(b,.7);near(e.hp,100000);near(z.hp,100000);assert.equal(u.skill.charges,0);});
test('S2 pre-emission true-dead input refund excludes own emitted kill and living invalid input',()=>{for(const state of['dead','hidden']){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(u);shot(b,u,e);if(state==='dead')b.kill(e);else e.hidden=true;advance(b,.7);assert.equal(u.skill.charges,state==='dead'?1:0);near(e.hp,state==='dead'?0:100000);}const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{hp:1});cast(u);shot(b,u,e);advance(b,.7);assert.equal(e.alive,false);assert.equal(u.skill.charges,0);assert.equal(b.receipts.length,1);});
test('S2 sub-tick foreign control before release cancels output and retains pending charge without false refund',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(u);shot(b,u,e);b.applyStatus(u,'stun',{duration:.001});advance(b,.7);near(e.hp,100000);assert.equal(u.skill.pending,true);assert.equal(u.skill.charges,0);assert.ok(!u.findBuff('bagpipe:s2-no-sp'));});
test('S2 accepted sub-tick control after first event cancels only unborn tail; rejected immunity retains it',()=>{for(const immune of[false,true]){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);u.def={...u.def,immune:new Set(u.def.immune)};if(immune)u.def.immune.add('stun');cast(u);shot(b,u,e);advance(b,.32);b.applyStatus(u,'stun',{duration:.001});advance(b,.3);near(100000-e.hp,(immune?2:1)*u.s.atk*2);assert.ok(!u.findBuff('bagpipe:s2-no-sp'));}});
test('S2 withdrawal and selected victim death after first event cancel pending second strike',()=>{for(const why of['withdraw','death','lifetime']){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(u);shot(b,u,e);advance(b,.32);const hp=e.hp;if(why==='withdraw')b.retreatOperator(ID);else if(why==='death')b.kill(e);else e.deploySeq++;advance(b,.3);if(why==='death')near(e.hp,0);else near(e.hp,hp);assert.equal(b.receipts.length,1);}});
test('S2 source noSP blocks startup and between events then resumes after last event',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(u);shot(b,u,e);near(u.skill.gainSp(2,'talent'),0);advance(b,.32);near(u.skill.sp,0);near(u.skill.gainSp(2,'talent'),0);advance(b,.3);assert.equal(u.skill.gainSp(2,'talent'),2);assert.ok(u.skill.sp>=2);});
test('S3 all ranks retain ATK/DEF/BAT percentage and additive block, preserving independent foreign BAT terms',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:2,rank}),u=deploy();b.addBuff(u,{key:'external',mods:{batFlat:.4,batPct:.2,atkPct:.1,defPct:.2,blockCnt:1}});cast(u);near(u.s.atk,u.base.atk*(1.1+u.skill.bb.atk));near(u.s.def,u.base.def*(1.2+u.skill.bb.def));near(u.s.bat,(u.base.bat+.4)*(1+.2+.7));near(u.s.blockCnt,u.base.blockCnt+2);u.skill.end('test');near(u.s.bat,(u.base.bat+.4)*1.2);near(u.s.blockCnt,u.base.blockCnt+1);assert.ok(u.findBuff('external'));}});
test('S3 natural AI cap1 primary emits only its three source events despite two blocked or nearby victims',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1});cast(u);assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,1);u.atkCd=0;b.step();u.atkCd=1000;advance(b,1);assert.equal(u.stats.attacks,1);near(200000-e.hp-z.hp,3*u.s.atk);assert.equal(b.receipts.length,3);});
test('S3 natural attack cadence honors its native1.7s BAT rather than a fake immediate triple loop',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(u);u.atkCd=0;advance(b,2.5);assert.equal(u.stats.attacks,2);assert.equal(b.receipts.length,6);near(100000-e.hp,6*u.s.atk);});
test('S3 already started tail survives nominal mode detach at current ATK but control cancels unborn events',()=>{for(const state of['mode','control']){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(u);shot(b,u,e);advance(b,.52);const hp=e.hp;if(state==='mode')u.skill.end('duration');else b.applyStatus(u,'stun',{duration:.001});advance(b,.3);near(hp-e.hp,state==='mode'?2*u.base.atk:0);}});
test('squad selected6/8SP applies from undeployed bench to self and Pioneer, never another profession',()=>{for(const potential of[1,5]){const{b,deploy}=make({potential},[FANG,KROOS]),f=deploy(FANG,2,3),k=deploy(KROOS,2,4),u=deploy();const sp=potential===1?6:8;near(f.skill.sp,f.def.skill.initSp+sp);near(k.skill.sp,k.def.skill.initSp);near(u.skill.sp,u.def.skill.initSp+sp);}});
test('squad E1 has no SP deck gift; maxed support source grants8 once per fresh deploy including later redeploy',()=>{const low=make({elite:1,rank:7},[FANG]),f=low.deploy(FANG,2,3);near(f.skill.sp,f.def.skill.initSp);const{b,deploy}=make({},[FANG],true),u=deploy(),v=deploy(FANG,2,3);near(u.skill.sp,u.def.skill.initSp+8);near(v.skill.sp,v.def.skill.initSp+8);b.retreatOperator(FANG);b.bench[FANG].readyAt=b.time;const z=deploy(FANG,2,3);near(z.skill.sp,z.def.skill.initSp+8);});
test('actual owned primary/crit-extra enemy kills credit trait1DP once each, foreign kill gives nothing',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{hp:1}),z=enemy(b,{c:5.1,hp:1});rng(b,[0]);b.getPlayer('arkpedia').dp=0;shot(b,u,e);advance(b,.6);near(b.dp,2);const extra=enemy(b);b.kill(extra);near(b.dp,2);assert.equal(e.alive,false);assert.equal(z.alive,false);});
test('manual Charger retreat refunds raw original cost, not inflated redeploy cost, and death refunds nothing',()=>{const{b,deploy}=make(),u=deploy();b.getPlayer('arkpedia').dp=0;b.retreatOperator(ID);near(b.dp,u.base.cost);b.bench[ID].readyAt=b.time;const v=deploy();const paid=b.bench[ID].lastCost;assert.ok(paid>v.base.cost);b.getPlayer('arkpedia').dp=0;b.retreatOperator(ID);near(b.dp,v.base.cost);b.bench[ID].readyAt=b.time;const w=deploy();b.getPlayer('arkpedia').dp=0;b.kill(w);near(b.dp,0);});
test('source literal Front/Back/Down clips preserve two/three actual event release families',()=>{for(const dir of['RIGHT','LEFT','DOWN','UP'])for(const skill of[1,2]){const{b,deploy}=make({skill}),u=deploy(ID,3,4,dir),e=enemy(b,{r:dir==='UP'?4:dir==='DOWN'?2:3,c:dir==='LEFT'?3:dir==='RIGHT'?5:4});cast(u);shot(b,u,e);const expected=skill===1?dir==='DOWN'?'Skill_Down':'Skill':dir==='DOWN'?'Skill_2_Loop_Down':'Skill_2_Loop';assert.equal(atkEvent(b,u).animation,expected);advance(b,1);assert.equal(b.receipts.length,skill===1?2:3);}});
test('disengagement completes literal Attack_End, resets begin, and new attack clears stale form without shifting clocks',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);shot(b,u,e);advance(b,.6);move(b,e,1,8);advance(b,.45);assert.equal(u.mem.regularFormVisual.clip,'Attack_End');assert.equal(u.mem.bagpipeOpening,true);move(b,e,3,5);shot(b,u,e);assert.equal(u.mem.regularFormVisual,null);assert.equal(atkEvent(b,u).animation.begin,'Attack_Begin');advance(b,.6);near(100000-e.hp,2*u.s.atk);});
test('scoped per-spell hooks and finite tails leave no persistent hit hook or SP lock',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b),initial=b._hooks.hit?.length??0;cast(u);shot(b,u,e);advance(b,1);assert.equal(b._hooks.hit?.length??0,initial);assert.equal(u.mem.bagpipeCast,null);assert.ok(!u.findBuff('bagpipe:s2-no-sp'));});
