// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with { type: 'json' };
import evidence from '../data/arkpedia-fartooth-prefabs.json' with { type: 'json' };
import { FARTOOTH_OPERATORS as configs } from '../shared/arkpedia/fartooth-operators.js';
import { StandardBattle } from '../server/sim/arkpedia.js';
import { defaultBuild } from '../shared/arkpedia/loadout.js';
import { acquireTargets, effectiveProfile } from '../server/sim/ai.js';
const ID='char_430_fartth',FANG='char_123_fang';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const advance=(b,s)=>{for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);};
const rows=p=>p.flatMap(r=>r.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id,{skill=0,elite=null,rank=10,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} snapshot is required`);elite??=op.phases.length-1;rank=Math.min(rank,elite===2?10:elite===1?7:4);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,skillId:op.skills[skill].id,skillRank:rank,potential};}
function make(opts={},more=[]){const src=structuredClone(data);src.stage.geometry.waves[0].spawns=[];src.stage.geometry.rows=19;src.stage.geometry.cols=21;src.stage.geometry.tileGrid=Array.from({length:19},()=>Array(21).fill(2));src.stage.battle.dp_per_second=0;const b=new StandardBattle(src,{operators:[build(ID,opts),...more.map(id=>build(id))]});b.autoFinish=false;b.recordEvents=true;b._received=[];b.on('damaged',c=>b._received.push(c));b.setViewport('fullscreen-workspace');b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));const deploy=(id=ID,row=3,col=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,row,col,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;};return{b,deploy};}
function enemy(b,{x=5,y=3,hp=100000,def=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[y,x]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:0});e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,x,y=3){e.x=x;e.y=y;e.tileR=y;e.tileC=x;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(b,u){u.skill.setSpTotal(u.skill.spCost);assert.equal(b.activateOperator(ID),true);u.atkCd=1000;}
function shot(b,u,e,s=1){assert.equal(b.forceAttack(u,Array.isArray(e)?e:[e]),true);u.atkCd=1000;advance(b,s);}
const hits=(b,u)=>b._received.filter(e=>e.source===u);
function firstFlight(b,u){let fired=0;const original=b.addProjectile.bind(b);b.addProjectile=p=>{if(p.source===u)fired++;return original(p);};for(let i=0;i<60&&!fired;i++)b.step();assert.deepEqual(b.errors,[]);assert.ok(fired>0);}

test('Fartooth retains exact table override, source CAST, one-hit speed14 and original chararts aliases',()=>{
 assert.deepEqual(Object.keys(configs),[ID]);assert.equal(configs[ID].skillIds[0],'skcom_quickattack[3]');assert.equal(evidence.tableContracts[ID].skillPrefabOverrides['skcom_quickattack[3]'],'skchr_fartth_1');assert.equal(evidence.frameParity,false);assert.equal(evidence.sourceBundles.length,5);for(const x of evidence.sourceBundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);
 for(const face of['Front','Back']){const m=evidence.models[ID][face];assert.equal(m.sha256,evidence.officialSkeletonBindings[ID][face].sha256);near(m.hits.Attack_Loop[0],.1);near(m.hits.Skill3_Loop[0],.1);near(m.durations.Skill3_Begin,.167);}
 for(const r of rows(evidence.characters[ID]).filter(x=>x._projectileKey?.startsWith('projectile_chr_fartth'))){assert.equal(r._selectTargetTiming,0);assert.equal(r._attachPassiveBuffsOnDummy,1);}
 for(const p of Object.values(evidence.projectiles)){const r=rows(p);near(r.find(x=>x._speed)._speed,14);near(r.find(x=>x._lifeTime)._lifeTime,10);assert.equal(r.find(x=>x._maxHitNum)._maxHitNum,1);assert.equal(r.find(x=>x._managedBySource!=null)._stopWhenSourceInvalid,0);}
 const checker=rows(evidence.characters[ID]).find(x=>x.pathId==='3025377128745239187');assert.equal(checker._disableWhenAppliedDamageModifier,1);assert.equal(checker._disableWhenAttack,0);const range=rows(evidence.characters[ID]).find(x=>x.pathId==='7900942731019715219');near(range._horizonSize,1);assert.equal(range._isHorizontalInfinite,0);
 const condition=evidence.templates['fartth_s_3[damagescale]'].eventToActions.ON_OUTPUT_DAMAGE[0];assert.match(condition._conditionNode.$type,/CheckTargetInRange/);assert.equal(evidence.templates.fartth_t_2.eventToActions.ON_OUTPUT_MODIFIER[0]._ignoreMissFlag,'PHYSICAL');
});
test('all thirty selected ranks produce source combat scales, ASPD, range and full manual skills',()=>{for(let skill=0;skill<3;skill++)for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill,rank}),u=deploy(),e=enemy(b,{x:skill===2?10:5,def:100}),l=data.operators[ID].skills[skill].levels[rank-1];assert.equal(u.skill.id,configs[ID].skillIds[skill]);assert.equal(u.skill.spType,'time');assert.equal(u.skill.manual,true);near(u.skill.spCost,l.spData.spCost);cast(b,u);if(skill===2)advance(b,.25);shot(b,u,e,1.3);const bb=u.skill.bb;near(100000-e.hp,(u.base.atk*(1+(bb.atk??0))-100)*(skill===2?bb.damage_scale:1));near(u.s.aspd,100+(bb.attack_speed??0));assert.equal(hits(b,u).length,1);}});
test('normal lowest-DEF selector keeps one victim rather than inherited flying priority or splash',()=>{const{b,deploy}=make(),u=deploy(),low=enemy(b,{def:10}),high=enemy(b,{x:5.2,def:300,fly:true}),p=effectiveProfile(u);assert.deepEqual(acquireTargets(b,u,p),[low]);shot(b,u,low);near(100000-low.hp,u.s.atk-10);near(high.hp,100000);assert.equal(hits(b,u).length,1);assert.equal(hits(b,u)[0].dmg.applyWay,'ranged');assert.equal(hits(b,u)[0].dmg.isAttack,true);});
test('ordinary first-entry begin and Down alias are literal original clips, followed by loop-only attack',()=>{for(const dir of['RIGHT','DOWN','UP']){const{b,deploy}=make(),u=deploy(ID,8,8,dir),e=enemy(b,{x:dir==='RIGHT'?9:8,y:dir==='DOWN'?7:dir==='UP'?9:8});b.forceAttack(u,[e]);u.atkCd=1000;const evt=b._evq.find(x=>x[0]==='atk'&&x[1]===u.id),clip=dir==='DOWN'?'Attack_Down_Loop':'Attack_Loop';assert.equal(evt[4].animation.loop,clip);near(evt[4].windup,.267);advance(b,.2);near(e.hp,100000);advance(b,.25);assert.ok(e.hp<100000);b._evq=[];shot(b,u,e);const next=b._evq.find(x=>x[0]==='atk'&&x[1]===u.id);assert.equal(next[4].animation,clip);near(next[4].windup,.1);}});
test('normal CAST releases at entrant after old victim leaves and suppresses target-free output',()=>{for(const state of['leave','free']){const{b,deploy}=make(),u=deploy(),old=enemy(b),next=enemy(b,{x:12});b.forceAttack(u,[old]);u.atkCd=1000;if(state==='leave')move(b,old,12);else b.addBuff(old,{key:'test:free',flags:{untargetable:true}});move(b,next,5);advance(b,1);near(old.hp,100000);near(100000-next.hp,u.s.atk);assert.equal(hits(b,u).length,1);}});
test('sub-tick accepted control cancels unborn arrow but rejected immunity preserves it',()=>{for(const immune of[false,true]){const{b,deploy}=make(),u=deploy(),e=enemy(b);if(immune)u.def.immune.add('stun');b.forceAttack(u,[e]);u.atkCd=1000;b.applyStatus(u,'stun',{duration:.001});advance(b,1);near(100000-e.hp,immune?u.s.atk:0);}});
test('skill-mode switch cancels an unborn ordinary arrow without producing a second victim',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);b.forceAttack(u,[e]);u.atkCd=1000;cast(b,u);advance(b,1);near(e.hp,100000);assert.equal(hits(b,u).length,0);});
test('S2 natural loop attacks globally blocked victim exactly once and keeps one attack lifecycle',()=>{const{b,deploy}=make({skill:1},[FANG]),blocker=deploy(FANG,3,10),u=deploy(),e=enemy(b,{x:10.2}),outside=enemy(b,{x:12,def:-100});e.blockedBy=blocker;blocker.blocking=[e];assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);cast(b,u);assert.deepEqual(acquireTargets(b,u,effectiveProfile(u)),[e]);u.atkCd=0;b.step();u.atkCd=1000;advance(b,1);near(100000-e.hp,u.s.atk);near(outside.hp,100000);assert.equal(u.stats.attacks,1);assert.equal(hits(b,u).length,1);});
test('S2 union retains unblocked normal-range victims and never selects unblocked outside or hidden blocked enemies',()=>{const{b,deploy}=make({skill:1},[FANG]),blocker=deploy(FANG,3,10),u=deploy(),inside=enemy(b,{def:10}),blocked=enemy(b,{x:10.2,def:0}),outside=enemy(b,{x:12,def:-20});blocked.blockedBy=blocker;blocker.blocking=[blocked];blocked.hidden=true;cast(b,u);assert.deepEqual(acquireTargets(b,u,effectiveProfile(u)),[inside]);shot(b,u,inside);assert.ok(inside.hp<100000);near(outside.hp,100000);near(blocked.hp,100000);});
test('S2 CAST sees block loss before release and selects a new in-range victim',()=>{const{b,deploy}=make({skill:1},[FANG]),blocker=deploy(FANG,3,10),u=deploy(),old=enemy(b,{x:10.2}),next=enemy(b,{x:12});old.blockedBy=blocker;blocker.blocking=[old];cast(b,u);b.forceAttack(u,[old]);u.atkCd=1000;old.blockedBy=null;blocker.blocking=[];move(b,next,5);advance(b,1);near(old.hp,100000);near(100000-next.hp,u.s.atk);});
test('S3 one-wide infinite forward line rotates in all four directions and restores original range',()=>{for(const[dir,x,y]of[['RIGHT',18,8],['LEFT',0,8],['UP',8,17],['DOWN',8,0]]){const{b,deploy}=make({skill:2}),u=deploy(ID,8,8,dir),e=enemy(b,{x,y}),side=enemy(b,{x:dir==='UP'||dir==='DOWN'?x+1:x,y:dir==='UP'||dir==='DOWN'?y:y+1}),back=enemy(b,{x:dir==='RIGHT'?7:dir==='LEFT'?9:8,y:dir==='UP'?7:dir==='DOWN'?9:8});assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);cast(b,u);advance(b,.25);assert.deepEqual(acquireTargets(b,u,effectiveProfile(u)),[e]);shot(b,u,e,1.3);near(100000-e.hp,u.s.atk*u.skill.bb.damage_scale);near(side.hp,100000);near(back.hp,100000);u.skill.end('duration');assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);}});
test('S3 bonus multiplies mitigated damage only outside original range, with no splash on another line victim',()=>{for(const x of[7,10]){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x,def:300}),extra=enemy(b,{x:x+.2,def:400});cast(b,u);advance(b,.25);shot(b,u,e,1.3);near(100000-e.hp,(u.s.atk-300)*(x===10?1.4:1));near(extra.hp,100000);assert.equal(hits(b,u).length,1);}});
test('S3 original CheckTargetInRange evaluates the moved victim at impact in both directions',()=>{for(const[start,end,scale]of[[7,10,1.4],[10,7,1]]){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:start,def:100});cast(b,u);advance(b,.25);b.forceAttack(u,[e]);u.atkCd=1000;firstFlight(b,u);move(b,e,end);advance(b,1);near(100000-e.hp,(u.s.atk-100)*scale);}});
test('S3 bonus remains tied to source range_id3-9 rather than generic range-extend modifiers',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:10,def:200});b.addBuff(u,{key:'test:extend',mods:{rangeExtend:10}});b.refreshRange(u);cast(b,u);advance(b,.25);shot(b,u,e,1.3);near(100000-e.hp,(u.s.atk-200)*1.4);});
test('Concentration source promotion and potential wait ten seconds and reset on accepted damage receipt',()=>{for(const[elite,potential,pct]of[[1,1,.1],[1,5,.13],[2,1,.15],[2,5,.18]]){const{b,deploy}=make({elite,potential}),u=deploy(),e=enemy(b);advance(b,9.9);near(u.s.atk,u.base.atk);advance(b,.2);near(u.s.atk,u.base.atk*(1+pct));b.dealDamage(e,u,{amount:10,type:'true'});near(u.s.atk,u.base.atk);advance(b,9.9);near(u.s.atk,u.base.atk);advance(b,.2);near(u.s.atk,u.base.atk*(1+pct));}});
test('Concentration applied-damage checker resets on shielded receipt but not own attacks, healing or HP loss',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);advance(b,10.1);const atk=u.s.atk;shot(b,u,e);near(u.s.atk,atk);b.loseHp(u,100,{source:u});b.heal(u,u,100);near(u.s.atk,atk);b.addBuff(u,{key:'test:shield',shield:100});b.dealDamage(e,u,{amount:30,type:'true'});near(u.s.atk,u.base.atk);assert.ok(u.findBuff('test:shield'));advance(b,10.1);near(u.s.atk,atk);});
test('retreat and redeployment do not inherit the previous Concentration clock or buff',()=>{const{b,deploy}=make(),u=deploy();advance(b,10.1);assert.ok(u.s.atk>u.base.atk);b.retreat(u);advance(b,80);const fresh=deploy();assert.notEqual(fresh,u);near(fresh.s.atk,fresh.base.atk);advance(b,9.9);near(fresh.s.atk,fresh.base.atk);advance(b,.2);assert.ok(fresh.s.atk>fresh.base.atk);});
test('E2 all selected skills lower taunt and bypass Physical dodge only for their active attacks',()=>{for(let skill=0;skill<3;skill++){const{b,deploy}=make({skill}),u=deploy(),e=enemy(b);b.addBuff(e,{key:'test:dodge',mods:{dodgePhys:1,dodgeArts:1}});shot(b,u,e);near(e.hp,100000);cast(b,u);if(skill===2)advance(b,.25);near(u.s.taunt,-1);shot(b,u,e);near(100000-e.hp,u.s.atk);u.skill.end('duration');near(u.s.taunt,0);const hp=e.hp;shot(b,u,e);near(e.hp,hp);}});
test('E1 active skill retains dodge and ordinary Arts outputs do not inherit Physical miss-ignore',()=>{const{b,deploy}=make({elite:1,skill:1}),u=deploy(),e=enemy(b);b.addBuff(e,{key:'test:dodge',mods:{dodgePhys:1,dodgeArts:1}});cast(b,u);near(u.s.taunt,0);shot(b,u,e);near(e.hp,100000);const f=make(),v=f.deploy(),z=enemy(f.b);f.b.addBuff(z,{key:'test:dodge',mods:{dodgeArts:1}});cast(f.b,v);f.b.dealDamage(v,z,{amount:100,type:'arts',isAttack:true,attackId:123});near(z.hp,100000);});
test('born active-skill arrow retains selected Physical dodge bypass across withdrawal and skill end',()=>{for(const state of['withdraw','end']){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:10,def:200});b.addBuff(e,{key:'test:dodge',mods:{dodgePhys:1}});cast(b,u);advance(b,.25);b.forceAttack(u,[e]);u.atkCd=1000;firstFlight(b,u);if(state==='withdraw')b.retreat(u);else u.skill.end('duration');advance(b,1);near(100000-e.hp,(u.base.atk-200)*1.4);assert.equal(hits(b,u).length,1);}});
test('dead or disappeared born trace target never hits a replacement or later deployment',()=>{for(const state of['dead','hidden']){const{b,deploy}=make(),u=deploy(),e=enemy(b,{x:7}),next=enemy(b,{x:7.1});b.forceAttack(u,[e]);u.atkCd=1000;firstFlight(b,u);if(state==='dead')b.kill(e);else e.hidden=true;advance(b,1);near(next.hp,100000);assert.equal(hits(b,u).length,0);}});
test('S3 exact begin, idle, loop and end presentation follow original alias mapping',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(b,u);assert.equal(u.mem.regularFormVisual.clip,'Skill3_Begin');assert.equal(u.s.flags.disarm,true);advance(b,.25);assert.equal(u.mem.regularFormVisual.clip,'Skill3_Idle');b._evq=[];shot(b,u,e);const event=b._evq.find(x=>x[0]==='atk'&&x[1]===u.id);assert.equal(event[4].animation,'Skill3_Loop');u.skill.end('duration');assert.equal(u.mem.regularFormVisual.clip,'Skill3_End');advance(b,.25);assert.equal(u.mem.regularFormVisual,null);});
test('natural S3 loop selects one lowest-DEF victim and produces one hit rather than per-victim duplicate waves',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:10,def:0}),z=enemy(b,{x:10.1,def:100});cast(b,u);advance(b,.25);u.atkCd=0;b.step();u.atkCd=1000;advance(b,1);near(100000-e.hp,u.s.atk*1.4);near(z.hp,100000);assert.equal(u.stats.attacks,1);assert.equal(hits(b,u).length,1);});
test('temporary source-victim-attack damage hook detaches after impact and leaves unrelated dodge unchanged',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:10}),other=enemy(b,{x:12});b.addBuff(e,{key:'test:dodge',mods:{dodgePhys:1}});b.addBuff(other,{key:'test:dodge',mods:{dodgePhys:1}});cast(b,u);advance(b,.25);const before=b._hooks.hit?.length??0;shot(b,u,e,1.3);assert.equal(b._hooks.hit?.length??0,before);const ownHit=hits(b,u)[0];b.dealDamage(u,other,{amount:100,type:'phys',isAttack:true,attackId:ownHit.dmg.attackId});near(other.hp,100000);assert.equal(b._hooks.hit?.length??0,before);});
