// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with { type: 'json' };
import source from '../data/arkpedia-jieyun-prefabs.json' with { type: 'json' };
import { JIEYUN_OPERATORS as configs } from '../shared/arkpedia/jieyun-operators.js';
import { StandardBattle } from '../server/sim/arkpedia.js';
import { defaultBuild } from '../shared/arkpedia/loadout.js';
import { effectiveProfile } from '../server/sim/ai.js';
import { COLS } from '../server/sim/constants.js';
const ID='char_4078_bdhkgt',FANG='char_123_fang';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const rows=r=>r.flatMap(x=>x.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id=ID,{skill=0,rank=10,elite=2,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} snapshot required`);elite=Math.min(elite,op.phases.length-1);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,skillId:op.skills[skill].id,skillRank:Math.min(rank,[4,7,10][elite]),potential};}
function make(opts={}){const d=structuredClone(data);d.stage.geometry.waves[0].spawns=[];d.stage.battle.dp_per_second=0;d.stage.geometry.rows=19;d.stage.geometry.cols=21;d.stage.geometry.tileGrid=Array.from({length:19},()=>Array(21).fill(2));const b=new StandardBattle(d,{operators:[build(ID,opts),build(FANG)]});b.autoFinish=false;b.setViewport('fullscreen-workspace');b.recordEvents=true;b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));const receipts=[];b.on('damaged',c=>receipts.push({...c,time:b.time}));const deploy=(id=ID,r=3,c=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,r,c,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;};return{b,deploy,receipts};}
function advance(b,s){for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);}
function enemy(b,{x=6,y=3,hp=100000,def=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[y,x]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:1});e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,x,y=3){e.x=x;e.y=y;e.tileR=y;e.tileC=x;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(b,u){u.skill.setSpTotal(u.skill.spCost);assert.equal(b.activateOperator(ID),true);u.atkCd=1000;}
function force(b,u,e){assert.equal(b.forceAttack(u,Array.isArray(e)?e:[e]),true);u.atkCd=1000;}
function onlyTile(b,x=6,y=3){const old=b.rng.pick,key=y*COLS+x;b.rng.pick=a=>a.includes(key)?key:old(a);}
const ownerHits=(r,u,e)=>r.filter(x=>x.source===u&&(!e||x.target===e));
function firstFlight(b,u){for(let i=0;i<50;i++){b.step();if(b.projectiles.list.some(x=>x.source===u))return;}assert.fail('no source flight');}

test('Jieyun exact source IDs, native release/flight/cache fields and actual facing aliases are retained',()=>{assert.deepEqual(Object.keys(configs),[ID]);assert.deepEqual(configs[ID].skillIds,['skchr_bdhkgt_1','skchr_bdhkgt_2']);assert.equal(source.frameParity,false);assert.equal(source.source.bundles.length,5);for(const x of source.source.bundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);for(const face of['Front','Back']){const m=source.models[ID][face];assert.equal(m.sha256,source.originalFacingBindings[ID][face].sha256);near(m.hits.Attack[0],.5);near(m.durations.Skill_2_End,.9);assert.equal(m.hits.Skill_2_Loop,undefined);}const c=rows(source.skills.skchr_bdhkgt_2).find(x=>x.pathId==='-4574780865977429649');assert.equal(c._waitForAttackEvent,0);near(c._preDelay,source.releaseDelay);assert.equal(c._waitForProjectileInvalid,1);const p=rows(source.projectiles.projectile_chr_bdhkgt_s2);near(p.find(x=>x._speed)._speed,11);near(p.find(x=>x._keepAlreadyHitTime!=null)._keepAlreadyHitTime,1);assert.equal(p.find(x=>x._stopWhenSourceInvalid!=null)._stopWhenSourceInvalid,0);assert.equal(source.models[ID].Front.durations.Skill_1,undefined);});
test('natural ordinary AoE releases one projectile and one NORMAL hit per victim, without generic duplicate splash',()=>{const{b,deploy,receipts}=make(),u=deploy(),a=enemy(b),z=enemy(b,{x:6.4}),far=enemy(b,{x:8});u.atkCd=0;b.step();u.atkCd=1000;advance(b,1);near(100000-a.hp,u.s.atk);near(100000-z.hp,u.s.atk);near(far.hp,100000);assert.equal(ownerHits(receipts,u).length,2);assert.equal(u.stats.attacks,1);assert.ok(ownerHits(receipts,u).every(x=>x.dmg.isAttack&&x.dmg.applyWay==='ranged'));});
test('ordinary CAST swaps a leaving victim for an entrant and suppresses untargetable release input',()=>{for(const blocked of[false,true]){const{b,deploy}=make(),u=deploy(),old=enemy(b),next=enemy(b,{x:15});force(b,u,old);move(b,old,15);move(b,next,6);if(blocked)b.addBuff(next,{key:'test:free',flags:{untargetable:true}});advance(b,1);near(old.hp,100000);assert.equal(next.hp<100000,!blocked);}});
test('ordinary original cap1 timing and DOWN alias do not invent a missing Skill1',()=>{for(const dir of['RIGHT','DOWN','LEFT','UP']){const{b,deploy}=make(),u=deploy(ID,5,5,dir),x=dir==='RIGHT'?7:dir==='LEFT'?3:5,y=dir==='UP'?7:dir==='DOWN'?3:5,e=enemy(b,{x,y});let emitted=0;const add=b.addProjectile.bind(b);b.addProjectile=p=>{emitted++;return add(p);};b.addBuff(u,{key:'test:fast',mods:{aspd:100}});force(b,u,e);advance(b,.45);assert.equal(emitted,0);advance(b,.1);assert.equal(emitted,1);assert.equal(u.profile.attackVisual(b,u),dir==='DOWN'?'Attack_Down':'Attack');}});
test('first-deployment ATK respects promotion and potential, and disappears on second successful spawn',()=>{for(const[elite,potential,scale]of[[0,1,0],[1,1,.08],[1,5,.10],[2,1,.13],[2,5,.15]]){const{b,deploy}=make({elite,potential}),u=deploy();near(u.s.atk,u.base.atk*(1+scale));b.retreat(u);b.bench[ID].readyAt=b.time;const next=deploy();near(next.s.atk,next.base.atk);assert.equal(b.bench[ID].deployments,2);}});
test('first-deployment cost is selected after potential and is consumed only after successful placement',()=>{for(const[elite,potential,discount]of[[0,1,0],[1,1,1],[2,1,3],[2,6,3]]){const{b,deploy}=make({elite,potential}),base=b.data.getChess(ID).stats.cost;near(b.cost(ID),base-discount);b.getPlayer('arkpedia').dp=0;assert.throws(()=>b.deployOperator(ID,3,4,'RIGHT'),/DP/);near(b.cost(ID),base-discount);assert.equal(b.bench[ID].deployments,0);const u=deploy();near(b.bench[ID].lastCost,base-discount);b.retreat(u);b.bench[ID].readyAt=b.time;near(b.cost(ID),Math.floor(base*1.5));const z=deploy();b.retreat(z);near(b.cost(ID),base*2);}});
test('S1 all ten ranks add selected ATK to the first talent rather than multiply independent percentages',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({rank}),u=deploy(),e=enemy(b,{def:100});cast(b,u);near(u.s.atk,u.base.atk*(1+.13+u.skill.bb.atk));near(u.s.aspd,u.base.aspd+20);force(b,u,e);advance(b,1);near(100000-e.hp,u.s.atk-100);advance(b,29.2);assert.equal(u.skill.active,false);near(u.s.atk,u.base.atk*1.13);near(u.s.aspd,u.base.aspd);}});
test('S1 natural family releases one normal projectile despite multiple AoE victims',()=>{const{b,deploy,receipts}=make(),u=deploy(),a=enemy(b),z=enemy(b,{x:6.3});cast(b,u);u.atkCd=0;b.step();u.atkCd=1000;advance(b,1);assert.equal(ownerHits(receipts,u).length,2);assert.equal(u.stats.attacks,1);near(100000-a.hp,u.s.atk);near(100000-z.hp,u.s.atk);});
test('S2 permits an empty command without invented damage, consumes SP and ends through original .9 clip',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy();cast(b,u);advance(b,.45);assert.equal(u.mem.regularFormVisual.clip,'Skill_2_End');assert.equal(b.projectiles.list.length,0);assert.equal(receipts.length,0);assert.equal(u.skill.gainSp(10,'test'),0);advance(b,.9);assert.equal(u.skill.active,false);assert.equal(Boolean(u.s.flags.disarm),false);assert.equal(u.mem.jieyunCast,null);});
test('S2 all ten ranks use selected Physical coefficient and refresh one-second half-speed movement',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy,receipts}=make({skill:1,rank}),u=deploy(),e=enemy(b,{x:7,def:100});onlyTile(b,7);cast(b,u);advance(b,.8);const h=ownerHits(receipts,u,e);assert.equal(h.length,1);near(h[0].amount,Math.max(u.s.atk*u.skill.bb.atk_scale-100,u.s.atk*u.skill.bb.atk_scale*.05));near(e.s.moveSpeed,.5);assert.equal(h[0].dmg.isAttack,true);assert.equal(h[0].dmg.applyWay,'ranged');}});
test('S2 explicit predelay and speed11 flight remain distinct from normal .5 release and noSP remains held',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{x:7});onlyTile(b,7);cast(b,u);advance(b,.3);assert.equal(b.projectiles.list.length,0);advance(b,.15);assert.equal(b.projectiles.list.length,1);near(e.hp,100000);assert.equal(u.skill.gainSp(10,'test'),0);advance(b,.4);assert.ok(e.hp<100000);assert.equal(u.skill.active,true);assert.equal(effectiveProfile(u).noAttack,true);assert.equal(u.skill.gainSp(10,'test'),0);});
test('S2 native CAST policy reselects a current ground entrant and never homes after the tile release',()=>{const{b,deploy}=make({skill:1}),u=deploy(),old=enemy(b),next=enemy(b,{x:15});cast(b,u);move(b,old,15);move(b,next,7);onlyTile(b,7);advance(b,.45);const p=b.projectiles.list.find(x=>x.source===u);assert.ok(p);near(p.tx,7);move(b,next,10);advance(b,.5);near(old.hp,100000);near(next.hp,100000);const late=enemy(b,{x:7});advance(b,.1);assert.ok(late.hp<100000);});
test('S2 per-victim collision cooldown gives late entrants immediate independent hits without catch-up burst',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),a=enemy(b,{x:7}),z=enemy(b,{x:15});onlyTile(b,7);cast(b,u);advance(b,.8);const first=ownerHits(receipts,u,a)[0];assert.ok(first);move(b,z,7.1);advance(b,.1);assert.equal(ownerHits(receipts,u,z).length,1);advance(b,.6);assert.equal(ownerHits(receipts,u,a).length,1);advance(b,.5);assert.ok(ownerHits(receipts,u,a).length>=2);for(const e of[a,z]){const hits=ownerHits(receipts,u,e);for(let i=1;i<hits.length;i++)assert.ok(hits[i].time-hits[i-1].time>=1-1e-7);}});
test('S2 collider damages moving-path victims and ALL-motion endpoint victims but cannot select an air-only tile',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),dest=enemy(b,{x:7}),walk=enemy(b,{x:5}),air=enemy(b,{x:7.2,fly:true});onlyTile(b,7);cast(b,u);advance(b,.8);assert.ok(ownerHits(receipts,u,walk).length);assert.ok(ownerHits(receipts,u,air).length);assert.ok(ownerHits(receipts,u,dest).length);const f=make({skill:1}),z=f.deploy(),sole=enemy(f.b,{fly:true});cast(f.b,z);advance(f.b,1.4);near(sole.hp,100000);assert.equal(z.skill.active,false);});
test('accepted sub-tick controls cancel unborn S2, immunity rejection preserves release, and born effect survives control',()=>{for(const immune of[false,true]){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{x:7});if(immune)u.def.immune.add('stun');cast(b,u);b.applyStatus(u,'stun',{duration:.001});advance(b,1);assert.equal(e.hp<100000,immune);}const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b,{x:7});cast(b,u);advance(b,.8);const n=ownerHits(receipts,u,e).length;b.applyStatus(u,'stun',{duration:.001});advance(b,1.1);assert.ok(ownerHits(receipts,u,e).length>n);});
test('born S2 graph survives owner withdrawal with documented current retired ATK and eventually releases its unowned timer',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b,{x:7});cast(b,u);advance(b,.8);const first=ownerHits(receipts,u,e)[0].amount;near(first,u.s.atk*u.skill.bb.atk_scale);b.retreat(u);const current=u.s.atk;assert.ok(first>current*u.skill.bb.atk_scale);advance(b,1.1);near(ownerHits(receipts,u,e)[1].amount,current*u.skill.bb.atk_scale);advance(b,16);const n=ownerHits(receipts,u,e).length;advance(b,2);assert.equal(ownerHits(receipts,u,e).length,n);assert.equal(u.mem.jieyunCast,null);});
test('born S2 damage evaluates later current source modifiers instead of retaining initial skill ATK',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b,{x:7});cast(b,u);advance(b,.8);const initial=ownerHits(receipts,u,e)[0].amount;b.addBuff(u,{key:'test:late',mods:{atkPct:1}});advance(b,1.1);near(ownerHits(receipts,u,e)[1].amount,u.s.atk*u.skill.bb.atk_scale);assert.ok(ownerHits(receipts,u,e)[1].amount>initial);});
test('overlapping old/new born effects retain both damage sources while their common slow never doubles',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b,{x:7});onlyTile(b,7);cast(b,u);advance(b,.8);b.retreat(u);b.bench[ID].readyAt=b.time;const z=deploy();cast(b,z);advance(b,1.1);assert.ok(ownerHits(receipts,u,e).length>=2);assert.ok(ownerHits(receipts,z,e).length);near(e.s.moveSpeed,.5);assert.equal(e.buffs.filter(x=>x.key==='bdhkgt_s_2').length,1);});
test('selected fifteen-second endpoint lifetime plus literal End.9 releases attack/SP with no extra boundary pulse',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b,{x:7});cast(b,u);advance(b,.8);const hold=u.mem.jieyunCast.holdUntil;assert.ok(Number.isFinite(hold));advance(b,hold-b.time+.1);const n=ownerHits(receipts,u,e).length;assert.equal(u.mem.regularFormVisual.clip,'Skill_2_End');assert.equal(u.skill.gainSp(1,'test'),0);advance(b,.9);assert.equal(u.skill.active,false);assert.equal(Boolean(u.s.flags.disarm),false);assert.ok(u.skill.gainSp(1,'test')>0);advance(b,2);assert.equal(ownerHits(receipts,u,e).length,n);});
test('directional S2 source Begin/Loop/End clips stay within the actual model for all four facings',()=>{for(const dir of['RIGHT','DOWN','LEFT','UP']){const{b,deploy}=make({skill:1}),u=deploy(ID,5,5,dir),x=dir==='RIGHT'?8:dir==='LEFT'?2:5,y=dir==='UP'?8:dir==='DOWN'?2:5;enemy(b,{x,y});cast(b,u);assert.equal(u.mem.regularFormVisual.clip,dir==='DOWN'?'Skill_Down_2_Begin':'Skill_2_Begin');advance(b,1.7);assert.equal(u.mem.regularFormVisual.clip,dir==='DOWN'?'Skill_Down_2_Loop':'Skill_2_Loop');assert.equal(u.skill.active,true);}});

test('native 3-16 selection is the single tile three spaces ahead, not a broad normal attack-range picker',()=>{assert.deepEqual(source.rangeTable['3-16'].grids,[{row:0,col:3}]);const{b,deploy}=make({skill:1}),u=deploy(),nearby=enemy(b,{x:6});cast(b,u);advance(b,1.4);near(nearby.hp,100000);assert.equal(u.skill.active,false);});

test('Tile18 bounded policy never emits beyond native3-16 when a huge body overlaps the tile but its center lies outside',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b,{x:8});e.hitArea={w:3,h:1,dx:0,dy:0};cast(b,u);advance(b,1.4);assert.equal(b.projectiles.list.length,0);near(e.hp,100000);assert.equal(ownerHits(receipts,u).length,0);assert.equal(u.skill.active,false);});
test('normal and S1 camouflage collateral remains legal without revealing or conflating independent invisibility',()=>{for(const active of[false,true]){const{b,deploy}=make(),u=deploy(),input=enemy(b),camouflage=enemy(b,{x:6.3}),invisible=enemy(b,{x:6.2});b.addBuff(camouflage,{key:'test:camo',flags:{camou:true}});b.addBuff(invisible,{key:'test:invisible',flags:{stealth:true}});if(active)cast(b,u);force(b,u,input);advance(b,1);near(100000-camouflage.hp,u.s.atk);near(invisible.hp,100000);assert.equal(Boolean(camouflage.s.flags.camou),true);assert.equal(Boolean(camouflage.s.flags.reveal),false);}});
test('born S2 collision permits camouflage while retaining hidden, target-free, sleeping and invisible legality',()=>{const{b,deploy}=make({skill:1}),u=deploy(),input=enemy(b,{x:7}),camo=enemy(b,{x:7.1}),hidden=enemy(b,{x:7.1}),free=enemy(b,{x:7.1}),sleeping=enemy(b,{x:7.1}),invisible=enemy(b,{x:7.1});b.addBuff(camo,{key:'test:camo',flags:{camou:true}});hidden.hidden=true;b.addBuff(free,{key:'test:free',flags:{untargetable:true}});b.applyStatus(sleeping,'sleep',{duration:20});b.addBuff(invisible,{key:'test:invisible',flags:{stealth:true}});cast(b,u);advance(b,.8);assert.ok(input.hp<100000);assert.ok(camo.hp<100000);for(const e of[hidden,free,sleeping,invisible])near(e.hp,100000);assert.equal(Boolean(camo.s.flags.camou),true);assert.equal(Boolean(camo.s.flags.reveal),false);});
