// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with { type: 'json' };
import source from '../data/arkpedia-w-prefabs.json' with { type: 'json' };
import { W_OPERATORS as configs } from '../shared/arkpedia/w-operators.js';
import { installW } from '../server/sim/content/arkpedia-w.js';
import { StandardBattle } from '../server/sim/arkpedia.js';
import { defaultBuild } from '../shared/arkpedia/loadout.js';
import { COLS } from '../server/sim/constants.js';
const ID='char_113_cqbw',TOKEN='token_10008_cqbw_box',FANG='char_123_fang';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const rows=r=>r.flatMap(x=>x.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id=ID,{skill=0,rank=10,elite=2,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} snapshot required`);elite=Math.min(elite,op.phases.length-1);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,skillId:op.skills[skill].id,skillRank:Math.min(rank,[4,7,10][elite]),potential};}
function make(opts={}){const d=structuredClone(data);d.stage.geometry.waves[0].spawns=[];d.stage.battle.dp_per_second=0;d.stage.geometry.rows=19;d.stage.geometry.cols=21;d.stage.geometry.tileGrid=Array.from({length:19},()=>Array(21).fill(2));const b=new StandardBattle(d,{operators:[build(ID,opts),build(FANG)]});b.autoFinish=false;b.setViewport('fullscreen-workspace');b.recordEvents=true;b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));const receipts=[];b.on('damaged',c=>receipts.push({...c,time:b.time}));const deploy=(id=ID,r=3,c=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,r,c,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;};return{b,deploy,receipts};}
function advance(b,s){for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);}
function enemy(b,{x=5,y=3,hp=100000,def=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[y,x]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:0});e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,x,y=3){e.x=x;e.y=y;e.tileR=y;e.tileC=x;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(b,u){u.skill.setSpTotal(u.skill.spCost);assert.equal(u.skill.manual?b.activateOperator(ID):u.skill.activate('DEFAULT'),true);u.atkCd=1000;}
function force(b,u,e){assert.equal(b.forceAttack(u,Array.isArray(e)?e:[e]),true);u.atkCd=1000;}
function keyMine(b,u,r=3,c=6){const key=r*COLS+c,old=b.rng.pick;b.rng.pick=a=>typeof a[0]==='number'&&a.includes(key)?key:old(a);cast(b,u);force(b,u,u);advance(b,.35);const t=[...u.mem.wMines][0];assert.ok(t);return t;}
const mineHits=(r,t)=>r.filter(x=>x.source===t),ownerHits=(r,u)=>r.filter(x=>x.source===u);
function firstFlight(b,u){let n=0;const old=b.addProjectile.bind(b);b.addProjectile=p=>{if(p.source===u)n++;return old(p);};for(let i=0;i<60&&!n;i++)b.step();assert.ok(n);assert.deepEqual(b.errors,[]);}

test('W source exact skill IDs, ordinary/skill aliases, projectile radii and original mine clocks are retained',()=>{assert.deepEqual(Object.keys(configs),[ID]);assert.deepEqual(configs[ID].skillIds,['skchr_cqbw_1','skchr_cqbw_2','skchr_cqbw_3']);assert.equal(source.frameParity,false);assert.equal(source.sourceBundles.length,6);for(const x of source.sourceBundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);for(const face of['Front','Back']){const m=source.models[ID][face];assert.equal(m.sha256,source.officialSkeletonBindings[ID][face].sha256);near(m.hits.Attack[0],.4);near(m.hits.Skill_1[0],.4);near(m.hits.Skill_2[0],.267);near(m.hits.Skill_3[0],.5);}const main=rows(source.skills.sktok_cqbw_token).find(x=>x.pathId==='-772262193217815092');assert.equal(main._waitForAttackEvent,0);near(main._preDelay,1.5);assert.equal(main._selectTargetTiming,1);const root=rows(source.characters[TOKEN]).find(x=>x._category!=null);assert.equal(root._category,2);assert.equal(root._occupiedRemainingCharacterCnt,0);assert.equal(root._useRealBornTimeFromAnim,1);near(source.tokenModel.hits.Attack[0],1.5);near(source.tokenModel.durations.Start,.5);const mover=rows(source.projectiles.projectile_chr_cqbw_s3).find(x=>x._delayAfterReached!=null);near(mover._delayTime,3);assert.equal(mover._stopIfTargetDead,1);assert.equal(mover._stopIfTargetDisappeared,1);assert.equal(source.primaryCorroboration.gitBlobSha,'47440aa534c87ad45015814227e21647c7866642');});
test('ordinary natural AoE creates one projectile and one hit per victim, with no duplicate splash',()=>{const{b,deploy,receipts}=make(),u=deploy(),a=enemy(b),z=enemy(b,{x:5.6}),far=enemy(b,{x:7.5});u.atkCd=0;b.step();u.atkCd=1000;advance(b,1);near(100000-a.hp,u.s.atk);near(100000-z.hp,u.s.atk);near(far.hp,100000);assert.equal(ownerHits(receipts,u).length,2);assert.equal(u.stats.attacks,1);assert.ok(ownerHits(receipts,u).every(x=>x.dmg.isAttack&&x.dmg.applyWay==='ranged'));});
test('ordinary CAST suppresses leaving input and hits entering victim, with source cap1 windup',()=>{const{b,deploy}=make(),u=deploy(),old=enemy(b),next=enemy(b,{x:15});force(b,u,old);move(b,old,15);move(b,next,5);advance(b,1);near(old.hp,100000);near(100000-next.hp,u.s.atk);for(const aspd of[200,50]){const f=make(),a=f.deploy(),e=enemy(f.b);f.b.addBuff(a,{key:'test:aspd',mods:{aspd:aspd-100}});let n=0;const add=f.b.addProjectile.bind(f.b);f.b.addProjectile=p=>{n++;return add(p);};force(f.b,a,e);advance(f.b,aspd===50?.7:.3);assert.equal(n,0);advance(f.b,.15);assert.equal(n,1);}});
test('Ambush is promotion-selected, anchored ten seconds after actual deployment and evades both physical and Arts',()=>{for(const[elite,p]of[[0,0],[1,.4],[2,.6]]){const{b,deploy}=make({elite}),e=enemy(b);advance(b,3);const u=deploy();advance(b,9.8);near(u.s.dodgePhys,0);near(u.s.taunt,u.base.tauntLevel);advance(b,.3);near(u.s.dodgePhys,p);near(u.s.dodgeArts,p);near(u.s.taunt,u.base.tauntLevel+(p?-1:0));const hp=u.hp,old=b.rng;b.rng=Object.assign(()=>0,b.rng);b.dealDamage(e,u,{amount:100,type:'phys'});b.dealDamage(e,u,{amount:100,type:'arts'});b.rng=old;near(u.hp,hp-(p?0:Math.max(5,100-u.s.def)+100*(1-u.s.res/100)));}});
test('Ambush deploy timer resets on retirement and redeployment, rather than using global battle phase',()=>{const{b,deploy}=make(),u=deploy();advance(b,10.1);near(u.s.dodgePhys,.6);b.retreat(u);b.bench[ID].readyAt=b.time;const z=deploy();assert.notEqual(z,u);advance(b,9.8);near(z.s.dodgePhys,0);advance(b,.3);near(z.s.dodgePhys,.6);});
test('Insult to Injury scales incoming Physical from any source only while stunned in W range',()=>{const{b,deploy}=make({potential:5}),u=deploy(),e=enemy(b,{def:0}),ally=deploy(FANG,2,4);b.applyStatus(e,'stun',{duration:2});b.dealDamage(ally,e,{amount:100,type:'phys'});near(100000-e.hp,121);const hp=e.hp;b.dealDamage(ally,e,{amount:100,type:'arts'});near(hp-e.hp,100);move(b,e,15);const far=e.hp;b.dealDamage(ally,e,{amount:100,type:'phys'});near(far-e.hp,100);move(b,e,5);b.removeBuff(e,'stun');const free=e.hp;b.dealDamage(ally,e,{amount:100,type:'phys'});near(free-e.hp,100);});
test('owned Physical vulnerability picks strongest W and restores weaker source after withdrawal',()=>{const{b,deploy}=make(),u=deploy(),other=deploy(FANG,2,4),e=enemy(b);other.x=u.x;other.y=u.y;other.tileR=u.tileR;other.tileC=u.tileC;other.rangeGrid=structuredClone(u.rangeGrid);b._refreshRange(other);const def={...u.def,charId:ID,talents:[{bb:{damage_scale:1.21}}]};other.def=def;installW({battle:b,unit:other,def});b.applyStatus(e,'stun',{duration:10});b.dealDamage(u,e,{amount:100,type:'phys'});near(100000-e.hp,121);b.retreat(other);const hp=e.hp;b.dealDamage(u,e,{amount:100,type:'phys'});near(hp-e.hp,118);b.retreat(u);near(e.s.physTakenMul,1);});
test('S1 all ten ranks preserve selected grenade damage and stun duration',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy,receipts}=make({rank}),u=deploy(),e=enemy(b,{def:100});cast(b,u);advance(b,1);const bb=u.skill.bb;near(100000-e.hp,(u.s.atk*bb.atk_scale-100)*1.18);assert.equal(ownerHits(receipts,u).length,1);const stun=e.buffs.find(x=>x.status==='stun');assert.ok(stun);assert.ok(stun.timeLeft<=bb.stun&&stun.timeLeft>bb.stun-.6);}});
test('S1 original release and actual flight retain noSP/attack lock until hit or fizzle',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{x:8});cast(b,u);advance(b,.35);near(e.hp,100000);assert.equal(u.skill.gainSp(10,'test'),0);advance(b,.15);assert.equal(u.skill.gainSp(10,'test'),0);advance(b,.5);assert.ok(e.hp<100000);assert.equal(Boolean(u.s.flags.disarm),false);assert.ok(u.skill.gainSp(1,'test')>0);});
test('S1 CAST selects current entrants and legally spends without a target',()=>{for(const empty of[false,true]){const{b,deploy}=make(),u=deploy(),old=enemy(b),next=enemy(b,{x:15});cast(b,u);move(b,old,15);if(!empty)move(b,next,5);advance(b,1);near(old.hp,100000);assert.equal(next.hp<100000,!empty);assert.equal(Boolean(u.s.flags.disarm),false);assert.equal(u.mem.regularFormVisual,null);}});
test('sub-tick controls cancel only unborn S1/S3, while immunity-rejected controls leave legal emission intact',()=>{for(const skill of[0,2])for(const immune of[false,true]){const{b,deploy,receipts}=make({skill}),u=deploy(),e=enemy(b);if(immune)u.def.immune.add('stun');cast(b,u);b.applyStatus(u,'stun',{duration:.001});advance(b,4);assert.equal(ownerHits(receipts,u).length,immune?1:0);assert.equal(Boolean(u.s.flags.disarm),false);}});
test('born S1 grenade survives owner withdrawal and does not retain detached vulnerability aura',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{x:8,def:100});cast(b,u);firstFlight(b,u);b.retreat(u);advance(b,1);near(100000-e.hp,u.s.atk*u.skill.bb.atk_scale-100);near(e.s.physTakenMul,1);});
test('S2 natural loop lays one zero-slot device on an empty field without self damage',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),hp=u.hp;u.skill.rule='DEFAULT';u.skill.setSpTotal(u.skill.spCost);u.atkCd=0;b.step();u.atkCd=1000;advance(b,.3);const list=[...u.mem.wMines];assert.equal(list.length,1);assert.equal(list[0].kind,'device');assert.equal(list[0].deploymentSlotCost,0);assert.equal(list[0].defId,TOKEN);assert.equal(b.deployedSlots(),1);near(u.hp,hp);assert.equal(receipts.length,0);});
test('S2 has no eligible tile gate without losing ready indicator or spending charge',()=>{const{b,deploy}=make({skill:1}),u=deploy();for(const t of b.grid.tiles)t.build='NONE';u.skill.setSpTotal(u.skill.spCost);assert.equal(u.skill.ready,true);assert.equal(b.activateOperator(ID),false);near(u.skill.spTotal,u.skill.spCost);});
test('S2 occupied retained input does not retarget or spawn another mine',()=>{const{b,deploy}=make({skill:1}),u=deploy(),key=3*COLS+6,old=b.rng.pick;b.rng.pick=a=>a.includes(key)?key:old(a);cast(b,u);force(b,u,u);deploy(FANG,3,6);advance(b,.4);assert.equal(u.mem.wMines.size,0);assert.equal(u.skill.charges,0);assert.ok(u.skill.spTotal<.2);assert.equal(u.skill.pending,false);});
test('S2 mine waits real .5 birth and explicit 1.5 trigger fuse, then withdraws after one burst',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b,{x:6}),t=keyMine(b,u);advance(b,.4);near(e.hp,100000);advance(b,.2);assert.equal(t.mem.regularFormVisual.clip,'Attack');advance(b,1.3);near(e.hp,100000);advance(b,.3);assert.ok(e.hp<100000);assert.equal(t.alive,false);assert.equal(mineHits(receipts,t).length,1);});
test('S2 all ten ranks preserve selected owner-ATK mine coefficient and stun',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:1,rank}),u=deploy(),e=enemy(b,{x:6,def:100}),t=keyMine(b,u),atk=t.s.atk;advance(b,2.2);near(100000-e.hp,(atk*u.skill.bb.atk_scale-100)*1.18);assert.ok(e.buffs.some(x=>x.status==='stun'));}});
test('S2 retained input set is ground-only and does not add new fuse-time entrants',()=>{const{b,deploy}=make({skill:1}),u=deploy(),a=enemy(b,{x:6}),air=enemy(b,{x:6.1,fly:true}),late=enemy(b,{x:15}),t=keyMine(b,u);advance(b,.6);move(b,a,15);move(b,late,6);advance(b,1.6);assert.ok(a.hp<100000);near(air.hp,100000);near(late.hp,100000);assert.equal(t.alive,false);});
test('S2 sampling retains placing ATK through mine birth and later owner modifiers, but owner finish kills it',()=>{const{b,deploy}=make({skill:1}),u=deploy();b.addBuff(u,{key:'test:atk',mods:{atkPct:.4}});const t=keyMine(b,u),sample=u.s.atk;near(t.s.atk,sample);b.addBuff(u,{key:'test:late',mods:{atkPct:2}});advance(b,.6);near(t.s.atk,sample);const e=enemy(b,{x:6});advance(b,1.7);near(100000-e.hp,sample*u.skill.bb.atk_scale*1.18);const next=keyMine(b,u,2,7);b.retreat(u);assert.equal(next.alive,false);assert.equal(u.mem.wMines.size,0);});
test('S2 dormant mine expires at selected120 seconds and releases its occupied tile',()=>{const{b,deploy}=make({skill:1}),u=deploy(),t=keyMine(b,u);advance(b,119.7);assert.equal(t.alive,true);advance(b,.4);assert.equal(t.alive,false);assert.equal(u.mem.wMines.size,0);assert.ok(!b.allyUnits.some(a=>a.alive&&a.deployed&&a.tileR===t.tileR&&a.tileC===t.tileC));});
test('S2 brief accepted control cancels unborn placement without a later mine, and cancels mine fuse',()=>{const{b,deploy}=make({skill:1}),u=deploy();cast(b,u);force(b,u,u);b.applyStatus(u,'stun',{duration:.001});advance(b,.4);assert.equal(u.mem.wMines.size,0);const t=keyMine(b,u),e=enemy(b,{x:6});advance(b,.6);b.applyStatus(t,'stun',{duration:.001});advance(b,1.7);near(e.hp,100000);assert.equal(t.alive,false);});
test('S3 all ten ranks use current highest HP and selected three/four independent bombs',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy,receipts}=make({skill:2,rank}),u=deploy(),es=[[5,2],[8,2],[5,4],[8,4],[6.5,3]].map(([x,y],i)=>enemy(b,{x,y,hp:100000-i*10000}));cast(b,u);advance(b,.55);assert.equal(u.mem.wBombs.size,u.skill.bb.max_target);advance(b,3.1);for(let i=0;i<es.length;i++)near(100000-i*10000-es[i].hp,i<u.skill.bb.max_target?u.s.atk*u.skill.bb.atk_scale*1.18:0);assert.equal(ownerHits(receipts,u).length,u.skill.bb.max_target);}});
test('S3 original .5 release plus three-second bomb delay is independent from full own cast window',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(b,u);advance(b,.45);assert.equal(u.mem.wBombs.size,0);near(e.hp,100000);advance(b,.1);assert.equal(u.mem.wBombs.size,1);assert.equal(u.skill.gainSp(1,'test'),0);advance(b,1.5);assert.equal(Boolean(u.s.flags.disarm),false);assert.ok(u.skill.gainSp(1,'test')>0);advance(b,1.3);near(e.hp,100000);advance(b,.3);assert.ok(e.hp<100000);assert.equal(u.mem.wBombs.size,0);});
test('S3 CAST reselects highest current HP at release and never marks target-free pending victims',()=>{const{b,deploy}=make({skill:2,rank:1}),u=deploy(),a=enemy(b,{hp:99999}),next=enemy(b,{x:15,hp:100000});cast(b,u);b.addBuff(a,{key:'test:free',flags:{untargetable:true}});move(b,next,5);advance(b,.6);assert.deepEqual([...u.mem.wBombs].map(x=>x.target),[next]);advance(b,3.1);near(a.hp,99999);assert.ok(next.hp<100000);});
test('S3 overlapping bombs each have their own blast, without projectile multiplicity per victim',()=>{const{b,deploy,receipts}=make({skill:2}),u=deploy(),a=enemy(b),z=enemy(b,{x:5.2});cast(b,u);advance(b,3.7);near(100000-a.hp,2*u.s.atk*u.skill.bb.atk_scale*1.18);near(100000-z.hp,2*u.s.atk*u.skill.bb.atk_scale*1.18);assert.equal(ownerHits(receipts,u).length,4);});
test('S3 follows original victim location, while an early dead/disappeared Stop blasts once without replacing it',()=>{for(const state of['dead','hidden']){const{b,deploy,receipts}=make({skill:2}),u=deploy(),a=enemy(b),old=enemy(b,{x:15}),next=enemy(b,{x:15});cast(b,u);advance(b,.6);move(b,a,7);move(b,next,7.5);advance(b,.04);if(state==='dead')b.kill(a);else a.hidden=true;advance(b,.1);assert.equal(u.mem.wBombs.size,0);assert.ok(next.hp<100000);near(old.hp,100000);const n=ownerHits(receipts,u).length;advance(b,3);assert.equal(ownerHits(receipts,u).length,n);}});
test('S3 born cached bombs survive owner withdrawal, preserve sampled ATK and lose detached source aura',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{def:100});b.addBuff(u,{key:'test:sample',mods:{atkPct:.5}});cast(b,u);advance(b,.6);const atk=u.s.atk;b.retreat(u);assert.ok(u.s.atk<atk);advance(b,3.1);near(100000-e.hp,atk*u.skill.bb.atk_scale-100);near(e.s.physTakenMul,1);assert.equal(u.mem.wBombs.size,0);});
