// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with {type:'json'};
import source from '../data/arkpedia-puzzle-prefabs.json' with {type:'json'};
import {PUZZLE_OPERATORS as configs} from '../shared/arkpedia/puzzle-operators.js';
import {installPuzzle} from '../server/sim/content/arkpedia-puzzle.js';
import {StandardBattle} from '../server/sim/arkpedia.js';
import {defaultBuild} from '../shared/arkpedia/loadout.js';
import {acquireTargets,effectiveProfile} from '../server/sim/ai.js';
const ID='char_4017_puzzle',KEY='puzzle_skill_2[damage]',FANG='char_123_fang';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const rows=r=>r.flatMap(x=>x.components.map(c=>({pathId:c.pathId,...c.data})));
const bb=(skill,rank=10)=>Object.fromEntries(source.tables.skills[`skchr_puzzle_${skill+1}`].levels[rank-1].blackboard.map(x=>[x.key,x.value]));
function build(id=ID,{skill=0,rank=10,elite=2,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} source snapshot needed`);elite=Math.min(elite,op.phases.length-1);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,potential,skillId:op.skills[skill].id,skillRank:Math.min(rank,[4,7,10][elite])};}
function make(opts={}){const d=structuredClone(data);d.stage.geometry.waves[0].spawns=[];d.stage.battle.dp_per_second=0;const b=new StandardBattle(d,{operators:[build(ID,opts),build(FANG)]});b.setViewport('fullscreen-workspace');b.autoFinish=false;b.recordEvents=true;b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));const receipts=[];b.on('damaged',c=>{if(c.source?.defId===ID&&c.dmg)receipts.push({...c,time:b.time});});const deploy=(id=ID,r=3,c=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,r,c,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;};return{b,u:deploy(),deploy,receipts};}
function advance(b,s){for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);}
function enemy(b,{r=3,c=5,hp=99999,def=0,res=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[r,c]});Object.assign(e.base,{maxHp:100000,def,res,moveSpeed:0});e.def={...e.def,immune:new Set(e.def.immune)};e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',persist:true,flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,r,c){e.x=c;e.y=r;e.tileR=r;e.tileC=c;b._enemiesDirty=true;b._buildEnemyIndex();}
function block(u,e){u.blocking=[e];e.blockedBy=u;}
function cast(u){u.skill.setSpTotal(u.skill.spCost);assert.equal(u.skill.activate('test'),true);u.atkCd=1000;}
function shot(b,u,e){assert.equal(b.forceAttack(u,e?[e]:undefined),true);u.atkCd=1000;}
function event(b,u){return b._evq.filter(x=>x[0]==='atk'&&x[1]===u.id).at(-1)[4];}
function poisonShot(f,e){shot(f.b,f.u,e);advance(f.b,.32);assert.ok(e.findBuff(KEY));return e.findBuff(KEY);}

test('Puzzle retains source native templates, all20 ranks, five verified bundles and both actual bound facing bytes',()=>{assert.deepEqual(Object.keys(configs),[ID]);assert.deepEqual(configs[ID].skillIds,['skchr_puzzle_1','skchr_puzzle_2']);assert.equal(source.frameParity,false);assert.equal(source.source.bundles.length,5);for(const x of source.source.bundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);for(const f of['Front','Back'])assert.equal(source.models[ID][f].sha256,source.originalFacingBindings[ID][f].sha256);assert.equal(Object.keys(source.originalBuffTemplates).length,6);for(const id of configs[ID].skillIds)assert.equal(source.tables.skills[id].levels.length,10);const t=source.buffTemplates.puzzle_t_1.eventToActions.ON_CALCULATE_DAMAGE;assert.equal(t.some(x=>x.$type.includes('IsAttack')),false);const dot=source.buffTemplates['puzzle_s_2[damage]'].eventToActions.ON_BUFF_TRIGGER[0];assert.equal(dot._attackType,'BUFF');assert.equal(dot._applyWay,'NONE');assert.equal(dot._damageType,'MAGICAL');assert.ok(source.verificationLimits.some(x=>x.includes('overrideType3')));});
test('both native S2 families retain exact shared stack, snapshot, lifetime, trigger and source-removal flags',()=>{for(const row of source.characters[ID].filter(x=>x.data._activeBuffs)){const dot=row.data._activeBuffs.find(x=>x.buffKey===KEY);if(!dot)continue;assert.equal(dot.overrideType,3);assert.equal(dot.independentCharacterSource,0);assert.equal(dot.takeSnapshotWhenExtend,1);assert.equal(dot.lifeTimeType,1);assert.equal(dot.durationKey,'duration_2');assert.equal(dot.triggerLifeType,2);assert.equal(dot.triggerCnt,16);near(dot.firstTriggerInterval,.15);near(dot.triggerInterval,1);assert.equal(dot.waitFirstTriggerInterval,1);assert.equal(dot.isDamageMissable,0);}const count=source.buffTemplates['puzzle_s_2[cnt]'].eventToActions.ON_BUFF_START[0];assert.equal(count._checkBuffSource,false);assert.equal(count._addition,1);assert.equal(count._additionKey,'addition_cnt');for(let rank=1;rank<=10;rank++){near(bb(1,rank)['attack@addtion_cnt'],1);assert.equal(bb(1,rank)['attack@addition_cnt'],undefined);}for(const group of Object.values(source.projectiles))for(const row of group)if(row.data._stopWhenSourceInvalid!==undefined)assert.equal(row.data._stopWhenSourceInvalid,0);});
test('every source phase/rank/skill/potential builds exact selected records without inherited generic talent stats',()=>{for(const skill of[0,1])for(let rank=1;rank<=10;rank++){const{b,u}=make({skill,rank});assert.equal(u.skill.id,configs[ID].skillIds[skill]);assert.equal(u.skill.noSkill,false);near(u.s.atk,u.base.atk);assert.deepEqual(b.errors,[]);}for(const[elite,potential,scale,sp]of[[0,1,0,0],[1,1,1.1,1],[1,5,1.15,1],[2,1,1.2,2],[2,5,1.25,2]]){const{u}=make({elite,potential});if(elite===0)assert.equal(u.def.talents.length,0);else{near(u.def.talents[0].bb.atk_scale,scale);near(u.def.talents[0].bb.sp,sp);}}});
test('ordinary blocked Combat is direct single-target physical damage at original.4 event',()=>{const{b,u,receipts}=make(),e=enemy(b,{c:4.2,def:120}),z=enemy(b,{c:4.3});block(u,e);shot(b,u,e);assert.equal(event(b,u).animation,'Combat');near(event(b,u).windup,.4);advance(b,.35);near(e.hp,99999);advance(b,.12);near(99999-e.hp,u.s.atk-120);near(z.hp,99999);assert.equal(b.projectiles.list.length,0);assert.equal(receipts[0].dmg.applyWay,'melee');});
test('ordinary unblocked Attack tracks source speed10 projectile and hits air without a fake splash',()=>{const{b,u,receipts}=make(),e=enemy(b,{fly:true,c:6}),z=enemy(b,{c:6.1});shot(b,u,e);assert.equal(event(b,u).animation,'Attack');near(event(b,u).windup,.4);advance(b,.46);near(e.hp,99999);assert.ok(b.projectiles.list.length);advance(b,.3);near(99999-e.hp,u.s.atk);near(z.hp,99999);assert.equal(receipts[0].dmg.applyWay,'ranged');});
test('ordinary CAST reacquires legal entering replacement and rejects leaving/hidden/target-free startup input',()=>{for(const reason of['leave','hidden','free']){const{b,u}=make(),e=enemy(b),z=enemy(b,{c:8});shot(b,u,e);if(reason==='leave')move(b,e,3,8);else if(reason==='hidden')e.hidden=true;else b.addBuff(e,{key:'free',flags:{untargetable:true}});move(b,z,3,5);advance(b,.7);near(e.hp,99999);near(99999-z.hp,u.s.atk);}});
test('source one-victim cap prioritizes actual blocking before unblocked ground/air and preserves all facing clips',()=>{for(const dir of['RIGHT','LEFT','UP','DOWN']){const{b,u}=make({dir}),e=enemy(b,{c:4.2}),z=enemy(b,{fly:true});u.dir=dir;b._refreshRange(u);block(u,e);assert.deepEqual(acquireTargets(b,u,effectiveProfile(u)),[e]);shot(b,u,e);assert.equal(event(b,u).animation,'Combat');advance(b,.5);near(99999-e.hp,u.s.atk);near(z.hp,99999);}});
test('ordinary release scales with uncapped ASPD and T1 full-HP gate samples impact before DEF',()=>{const{b,u}=make(),e=enemy(b,{hp:100000,def:150});b.addBuff(u,{key:'fast',mods:{aspd:200}});block(u,e);shot(b,u,e);near(event(b,u).windup,.4/3);advance(b,.25);near(100000-e.hp,u.s.atk*1.2-150);near(u.skill.spTotal,u.def.skill.initSp+3);});
test('T1 selected E1/E2/potential checks exact full HP, never a near-full approximation',()=>{for(const[elite,potential,scale,sp]of[[0,1,1,0],[1,1,1.1,1],[1,5,1.15,1],[2,1,1.2,2],[2,5,1.25,2]])for(const full of[true,false]){const{b,u}=make({elite,potential}),e=enemy(b,{hp:full?100000:99999,def:200});u.skill.setSpTotal(0);const hp=e.hp;b.dealDamage(u,e,{amount:300,type:'phys',isAttack:true,applyWay:'melee',canDodge:false});near(hp-e.hp,300*(full?scale:1)-200);near(u.skill.spTotal,full?sp:0);}});
test('T1 current full-HP state is sampled at projectile impact rather than cached attack startup',()=>{for(const state of['wound','heal']){const{b,u}=make(),e=enemy(b,{c:6,hp:state==='wound'?100000:99999});shot(b,u,e);advance(b,.47);e.hp=state==='wound'?99999:100000;const hp=e.hp;advance(b,.3);near(hp-e.hp,u.s.atk*(state==='heal'?1.2:1));}});
test('T1 original lacks IsAttack gate: own typed BUFF/NONE and true calculations qualify, other sources do not',()=>{for(const type of['arts','true']){const{b,u,receipts}=make(),e=enemy(b,{hp:100000,res:20});u.skill.setSpTotal(0);b.dealDamage(u,e,{amount:100,type,canDodge:false,isAttack:false,applyWay:'none',tags:['dot']});near(100000-e.hp,120*(type==='arts'?.8:1));near(u.skill.spTotal,2);assert.equal(receipts[0].dmg.isAttack,false);assert.equal(receipts[0].dmg.applyWay,'none');const z=enemy(b,{hp:100000});b.dealDamage(null,z,{amount:100,type:'true'});near(100000-z.hp,100);near(u.skill.spTotal,2);}});
test('T1 hit-scope does not see element gauges, pure HP loss, sourceless or pre-hook invulnerability/sleep',()=>{for(const mode of['element','loss','sourceless','invulnerable','sleep']){const{b,u}=make(),e=enemy(b,{hp:100000});u.skill.setSpTotal(0);if(mode==='invulnerable')b.addBuff(e,{key:'inv',flags:{invulnerable:true}});if(mode==='sleep')b.applyStatus(e,'sleep',{duration:10});if(mode==='loss')b.loseHp(e,100,u);else b.dealDamage(u,e,{amount:100,type:mode==='element'?'element':'true',element:'burn',sourceless:mode==='sourceless'});near(u.skill.spTotal,0);}});
test('T1 nonforced SP respects noSp/active timed gate while preserving full-HP damage scaling',()=>{for(const hold of['noSp','active']){const{b,u}=make({skill:1}),e=enemy(b,{hp:100000});if(hold==='active')cast(u);else{u.skill.setSpTotal(0);b.addBuff(u,{key:'hold',flags:{noSp:true}});}b.dealDamage(u,e,{amount:100,type:'true',isAttack:false});near(100000-e.hp,120);near(u.skill.spTotal,0);}});
test('T1 pre-mitigation SP can survive a subsequently dodged modifier but S2 output DP cannot',()=>{const{b,u}=make(),e=enemy(b,{hp:100000});u.skill.setSpTotal(0);b.addBuff(e,{key:'dodge',mods:{dodgePhys:1}});b.dealDamage(u,e,{amount:100,type:'phys',isAttack:true});near(e.hp,100000);near(u.skill.spTotal,2);});
test('Key Clue every rank emits selected ATK-scaled physical hit and3DP at valid launch',()=>{for(let rank=1;rank<=10;rank++){const{b,u}=make({rank}),e=enemy(b,{c:4.2,def:100});block(u,e);cast(u);b.getPlayer('arkpedia').dp=0;shot(b,u,e);advance(b,.5);near(99999-e.hp,u.s.atk*bb(0,rank).atk_scale-100);near(b.dp,3);assert.equal(u.skill.pending,false);assert.equal(u.findBuff('puzzle:s1-no-sp'),null);}});
test('Key Clue DP belongs to emitted attack: physical dodge/shield/late projectile target loss do not retract it',()=>{for(const mode of['dodge','shield','fizzle']){const{b,u}=make(),e=enemy(b,{c:6});if(mode==='dodge')b.addBuff(e,{key:'dodge',mods:{dodgePhys:1}});if(mode==='shield')b.addBuff(e,{key:'shield',shield:100000});cast(u);b.getPlayer('arkpedia').dp=0;shot(b,u,e);advance(b,.47);near(b.dp,3);if(mode==='fizzle')e.hidden=true;advance(b,.35);near(e.hp,99999);near(b.dp,3);}});
test('Key Clue CAST empty true-dead startup input refunds once, living invalid input does not',()=>{for(const reason of['dead','hidden','leave','free']){const{b,u}=make(),e=enemy(b);cast(u);b.getPlayer('arkpedia').dp=0;shot(b,u,e);if(reason==='dead')b.kill(e);else if(reason==='hidden')e.hidden=true;else if(reason==='leave')move(b,e,3,8);else b.addBuff(e,{key:'free',flags:{untargetable:true}});advance(b,.6);near(b.dp,0);assert.equal(u.skill.charges,reason==='dead'?1:0);assert.equal(u.findBuff('puzzle:s1-no-sp'),null);}});
test('Key Clue dead original with live CAST replacement emits once without refund, own emitted kill never refunds',()=>{for(const replacement of[true,false]){const{b,u}=make(),e=enemy(b,{hp:replacement?99999:1}),z=replacement?enemy(b,{c:5.1}):null;cast(u);b.getPlayer('arkpedia').dp=0;shot(b,u,e);if(replacement)b.kill(e);advance(b,.7);near(b.dp,3);assert.equal(u.skill.charges,0);if(replacement)assert.ok(z.hp<99999);else assert.equal(e.alive,false);}});
test('Key Clue remembers brief control, releases no output or DP, cleans noSP and retains unconsumed pending attack',()=>{for(const status of['stun','freeze','sleep','levitate']){const{b,u}=make(),e=enemy(b);cast(u);b.getPlayer('arkpedia').dp=0;shot(b,u,e);b.applyStatus(u,status,{duration:.001});advance(b,.7);near(e.hp,99999);near(b.dp,0);assert.equal(u.skill.pending,true);assert.equal(u.findBuff('puzzle:s1-no-sp'),null);assert.equal(u.canAct,true);}});
test('Key Clue noSP is held through unborn release, then ranged full-HP impact can give selected talent SP',()=>{const{b,u}=make(),e=enemy(b,{hp:100000,c:6});cast(u);shot(b,u,e);near(u.skill.gainSp(3,'test'),0);advance(b,.47);near(u.skill.spTotal,0);assert.equal(u.findBuff('puzzle:s1-no-sp'),null);advance(b,.35);near(u.skill.spTotal,2);near(100000-e.hp,u.s.atk*3*1.2);});
test('Follow a Lead all ranks hold selected ASPD eight seconds and source literal idle with no invented cast lock',()=>{for(let rank=1;rank<=10;rank++){const{b,u}=make({skill:1,rank});b.addBuff(u,{key:'foreign',mods:{aspd:7}});cast(u);near(u.s.aspd,107+bb(1,rank).attack_speed);near(u.skill.timeLeft,8);assert.deepEqual(u.mem.regularFormVisual,{clip:'Skill_2_Idle',loop:true});assert.equal(Boolean(u.s.flags.disarm),false);u.skill.end('test');near(u.s.aspd,107);assert.equal(u.mem.regularFormVisual,null);assert.ok(u.findBuff('foreign'));}});
test('Follow a Lead uses literal original.333 blocked/unblocked clips and source projectile speed10',()=>{for(const melee of[false,true]){const{b,u,receipts}=make({skill:1}),e=enemy(b,{c:melee?4.2:6});if(melee)block(u,e);cast(u);shot(b,u,e);assert.equal(event(b,u).animation,melee?'Skill_2_Combat':'Skill_2_Attack');near(event(b,u).windup,.333/1.7);advance(b,.16);near(e.hp,99999);advance(b,melee?.15:.4);assert.ok(e.hp<99999);assert.equal(receipts.find(x=>x.dmg.isAttack).dmg.applyWay,melee?'melee':'ranged');assert.ok(e.findBuff(KEY));}});
test('Follow a Lead accepted NORMAL output grants1DP even fully absorbed; canceled/dodged and BUFF output do not',()=>{for(const state of['normal','shield','dodge','cancel']){const{b,u,receipts}=make({skill:1}),e=enemy(b,{c:4.2});block(u,e);if(state==='shield')b.addBuff(e,{key:'shield',shield:100000});if(state==='dodge')b.addBuff(e,{key:'dodge',mods:{dodgePhys:1}});if(state==='cancel')b.on('hit',c=>{if(c.dmg.isAttack)c.dmg.cancel=true;},{priority:-100});cast(u);b.getPlayer('arkpedia').dp=0;shot(b,u,e);advance(b,.32);near(b.dp,['normal','shield'].includes(state)?1:0);assert.ok(e.findBuff(KEY),'isDamageMissable0 attachment independent from NORMAL output');const dp=b.dp;advance(b,.3);near(b.dp,dp);assert.ok(receipts.some(x=>!x.dmg.isAttack));}});
test('Follow a Lead mode-end during already emitted flight retains original impact poison but expires owner DP buff',()=>{const{b,u}=make({skill:1}),e=enemy(b,{c:6});cast(u);b.getPlayer('arkpedia').dp=0;shot(b,u,e);advance(b,.24);assert.ok(b.projectiles.list.length);u.skill.end('duration');advance(b,.4);assert.ok(e.findBuff(KEY));near(b.dp,0);near(99999-e.hp,u.s.atk*(1+.15));});
test('poison every rank caches current ATK, starts only after.15, ticks one-second MAGICAL/BUFF/NONE without dodge',()=>{for(let rank=1;rank<=10;rank++){const f=make({skill:1,rank}),{b,u,receipts}=f,e=enemy(b,{c:4.2,res:25});block(u,e);cast(u);shot(b,u,e);advance(b,.32);const dot=e.findBuff(KEY);assert.ok(dot);const hp=e.hp;near(dot.data.cachedAtk,u.s.atk);near(dot.data.count,1);advance(b,.03);near(e.hp,hp);advance(b,.1);near(hp-e.hp,u.s.atk*bb(1,rank)['attack@atk_scale_2']*.75);const r=receipts.filter(x=>!x.dmg.isAttack);assert.equal(r.length,1);assert.equal(r[0].dmg.type,'arts');assert.equal(r[0].dmg.applyWay,'none');assert.equal(r[0].dmg.isSkill,false);assert.equal(r[0].dmg.canDodge,false);advance(b,1);assert.equal(receipts.filter(x=>!x.dmg.isAttack).length,2);}});
test('poison independent capped count reaches10 and source typed BUFF uses count only once per tick',()=>{const f=make({skill:1}),{b,u,receipts}=f,e=enemy(b,{c:4.2});block(u,e);cast(u);for(let i=0;i<12;i++)poisonShot(f,e);const dot=e.findBuff(KEY);near(dot.data.count,10);assert.equal(e.buffs.filter(x=>x.key===KEY).length,1);const hp=e.hp,count=receipts.filter(x=>!x.dmg.isAttack).length;advance(b,1);near(hp-e.hp,u.s.atk*.15*10);assert.equal(receipts.filter(x=>!x.dmg.isAttack).length,count+1);});
test('poison refresh resamples source ATK without baking T1 scale and preserves existing cadence while renewing16s',()=>{const f=make({skill:1}),{b,u}=f,e=enemy(b,{c:4.2,hp:100000});block(u,e);cast(u);const dot=poisonShot(f,e),initialNext=dot.data.nextAt,oldExpiry=dot.data.expiresAt;near(dot.data.cachedAtk,u.s.atk);b.addBuff(u,{key:'foreign-atk',mods:{atkPct:.5}});e.hp=100000;poisonShot(f,e);assert.equal(e.findBuff(KEY),dot);near(dot.data.count,2);near(dot.data.cachedAtk,u.s.atk);assert.ok(dot.data.expiresAt>oldExpiry);assert.ok(dot.data.nextAt===initialNext||dot.data.nextAt===initialNext+1);near(dot.data.expiresAt,b.time-.32+.333/1.7+16,b.dt*2);});
test('poison snapshot and counter are shared across different producers, newest source replaces only snapshot/credit',()=>{const f=make({skill:1}),{b,u,deploy}=f,e=enemy(b,{c:4.2}),z=deploy(FANG,2,3);block(u,e);cast(u);const dot=poisonShot(f,e);z.def=structuredClone(u.def);z.defId=ID;z.skill.id=u.skill.id;z.skill.bb={...u.skill.bb};z.skill.spec={attack:{puzzleSecond:true}};z.skill.active=true;z.skill.kind='duration';z.skill.timeLeft=100;z.tileR=u.tileR;z.tileC=u.tileC;z.x=u.x;z.y=u.y;z.dir=u.dir;z.profile={...u.profile};installPuzzle({battle:b,unit:z,def:z.def});block(z,e);b.addBuff(z,{key:'foreignATK',mods:{atkFlat:200}});shot(b,z,e);advance(b,.45);assert.equal(e.findBuff(KEY),dot);near(dot.data.count,2);assert.equal(dot.data.source,z);near(dot.data.cachedAtk,z.s.atk);assert.equal(e.buffs.filter(x=>x.key===KEY).length,1);});
test('poison actual full-HP calculation receives T1 while snapshot remains raw; active S2 suppresses talent SP',()=>{const f=make({skill:1}),{b,u,receipts}=f,e=enemy(b,{c:4.2});block(u,e);cast(u);const dot=poisonShot(f,e);e.hp=100000;const hp=e.hp;advance(b,.14);near(hp-e.hp,dot.data.cachedAtk*.15*1.2);near(u.skill.spTotal,0);const tick=receipts.find(x=>!x.dmg.isAttack);near(tick.dmg.amount,dot.data.cachedAtk*.15*1.2);u.skill.end('duration');u.skill.setSpTotal(0);e.hp=100000;advance(b,1);near(u.skill.spTotal,2);});
test('poison continues through source withdrawal, retains emitted projectile, but removed owner talent no longer scales it',()=>{for(const duringFlight of[false,true]){const f=make({skill:1}),{b,u}=f,e=enemy(b,{c:duringFlight?6:4.2});if(!duringFlight)block(u,e);cast(u);shot(b,u,e);advance(b,duringFlight?.24:.32);b.retreatOperator(ID);advance(b,.4);const dot=e.findBuff(KEY);assert.ok(dot);e.hp=100000;const hp=e.hp;advance(b,1);near(hp-e.hp,dot.data.cachedAtk*.15);assert.equal(u.deployed,false);}});
test('attached poison retains fixed clock through owner control and victim hidden/sleep/target-free states',()=>{for(const state of['owner-control','hidden','sleep','free']){const f=make({skill:1}),{b,u,receipts}=f,e=enemy(b,{c:4.2});block(u,e);cast(u);const dot=poisonShot(f,e);if(state==='owner-control')b.applyStatus(u,'stun',{duration:2});if(state==='hidden')e.hidden=true;if(state==='sleep')b.applyStatus(e,'sleep',{duration:.4});if(state==='free')b.addBuff(e,{key:'free',flags:{untargetable:true}});const hp=e.hp;advance(b,.4);if(['hidden','sleep'].includes(state))near(e.hp,hp);else assert.ok(e.hp<hp);if(state==='hidden')e.hidden=false;advance(b,1);assert.equal(e.findBuff(KEY),dot);assert.ok(receipts.filter(x=>!x.dmg.isAttack).length>=1);near(dot.data.nextAt,dot.data.expiresAt-16+.15+2);}});
test('poison selected16s expiry has16 initial pulses and a fresh attachment resets count/first delay',()=>{const f=make({skill:1}),{b,u,receipts}=f,e=enemy(b,{c:4.2});block(u,e);cast(u);poisonShot(f,e);u.skill.end('duration');advance(b,16.2);assert.equal(e.findBuff(KEY),null);assert.equal(receipts.filter(x=>!x.dmg.isAttack).length,16);cast(u);const dot=poisonShot(f,e);near(dot.data.count,1);assert.ok(dot.data.nextAt>b.time);});
test('poison bounded refreshed lifetime extends beyond original16-trigger count instead of silently clearing a kept stack',()=>{const f=make({skill:1}),{b,u,receipts}=f,e=enemy(b,{c:4.2});block(u,e);cast(u);poisonShot(f,e);u.skill.end('duration');advance(b,14);cast(u);const dot=poisonShot(f,e);u.skill.end('duration');advance(b,3);assert.ok(e.findBuff(KEY));assert.ok(receipts.filter(x=>!x.dmg.isAttack).length>16);near(dot.data.count,2);assert.ok(source.verificationLimits.some(x=>x.includes('cumulative16-trigger')));});
test('poison magical damage uses current RES/incoming scalers but captured ATK, never physical DEF or later ATK buff',()=>{const f=make({skill:1}),{b,u}=f,e=enemy(b,{c:4.2,def:10000,res:20});block(u,e);cast(u);const dot=poisonShot(f,e);b.addBuff(u,{key:'lateATK',mods:{atkPct:1}});b.addBuff(e,{key:'arts',mods:{resFlat:30,artsTakenMul:1.5}});const hp=e.hp;advance(b,.14);near(hp-e.hp,dot.data.cachedAtk*.15*.5*1.5);near(dot.data.cachedAtk,u.base.atk);});
test('skill cooldown and pending locks are source-local; withdrawal/death clear noSP and form without dropping enemy DOT',()=>{for(const mode of['retreat','death']){const{b,u}=make();const e=enemy(b);cast(u);shot(b,u,e);if(mode==='retreat')b.retreatOperator(ID);else b.kill(u);advance(b,.7);near(e.hp,99999);assert.equal(u.findBuff('puzzle:s1-no-sp'),null);}const f=make({skill:1}),e=enemy(f.b,{c:4.2});block(f.u,e);cast(f.u);poisonShot(f,e);f.b.retreatOperator(ID);assert.equal(f.u.mem.regularFormVisual,null);assert.ok(e.findBuff(KEY));});
test('natural AI fills Key Clue from first full-HP normal hit and emits exactly one automatic charged attack',()=>{const{b,u,receipts}=make(),e=enemy(b,{c:4.2,hp:100000});block(u,e);u.skill.rule='DEFAULT';u.atkCd=0;b.getPlayer('arkpedia').dp=0;advance(b,2.05);assert.equal(u.skill.activations,1);near(b.dp,3);assert.equal(receipts.filter(x=>x.dmg.isSkill).length,1);const normal=receipts.find(x=>!x.dmg.isSkill);near(normal.dmg.amount,u.s.atk*1.2);assert.equal(u.findBuff('puzzle:s1-no-sp'),null);});
test('natural S2 repeated attacks retain source cadence and grant DP only per NORMAL output, never poison pulses',()=>{const{b,u,receipts}=make({skill:1}),e=enemy(b,{c:4.2});block(u,e);cast(u);u.atkCd=0;b.getPlayer('arkpedia').dp=0;advance(b,2.2);const normal=receipts.filter(x=>x.dmg.isAttack),dot=receipts.filter(x=>!x.dmg.isAttack);assert.ok(normal.length>=3);assert.ok(dot.length>=2);near(b.dp,normal.length);for(let i=1;i<normal.length;i++)near(normal[i].time-normal[i-1].time,u.s.interval,b.dt+.001);u.atkCd=1000;u.skill.end('duration');const dp=b.dp;advance(b,1.1);near(b.dp,dp);assert.ok(receipts.filter(x=>!x.dmg.isAttack).length>dot.length);});
