// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with { type: 'json' };
import evidence from '../data/arkpedia-archetto-prefabs.json' with { type: 'json' };
import { ARCHETTO_OPERATORS as configs } from '../shared/arkpedia/archetto-operators.js';
import { StandardBattle } from '../server/sim/arkpedia.js';
import { defaultBuild } from '../shared/arkpedia/loadout.js';
import { acquireTargets, effectiveProfile } from '../server/sim/ai.js';
const ID='char_332_archet',KROOS='char_124_kroos',EX='char_103_angel',FANG='char_123_fang';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const advance=(b,s)=>{for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);};
const rows=p=>p.flatMap(r=>r.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id,{skill=0,elite=null,rank=10,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} snapshot is required`);elite??=op.phases.length-1;rank=Math.min(rank,elite===2?10:elite===1?7:4);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,skillId:op.skills[skill].id,skillRank:rank,potential};}
function make(opts={},more=[]){const src=structuredClone(data);src.stage.geometry.waves[0].spawns=[];src.stage.battle.dp_per_second=0;const b=new StandardBattle(src,{operators:[build(ID,opts),...more.map(id=>build(id))]});b.autoFinish=false;b.recordEvents=true;b._received=[];b.on('damaged',c=>b._received.push(c));b.setViewport('fullscreen-workspace');b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));const deploy=(id=ID,row=3,col=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,row,col,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;};return{b,deploy};}
function enemy(b,{x=5,y=3,hp=100000,def=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[y,x]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:0});e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,x,y=3){e.x=x;e.y=y;e.tileR=y;e.tileC=x;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(b,u){u.skill.setSpTotal(u.skill.spCost);assert.equal(u.skill.manual?b.activateOperator(ID):u.skill.activate('DEFAULT'),true);u.atkCd=1000;}
function shot(b,u,e,s=1){assert.equal(b.forceAttack(u,Array.isArray(e)?e:[e]),true);u.atkCd=1000;advance(b,s);}
const hits=(b,u)=>b._received.filter(e=>e.source===u);
function firstFlight(b,u){let fired=0;const original=b.addProjectile.bind(b);b.addProjectile=p=>{if(p.source===u)fired++;return original(p);};for(let i=0;i<40&&!fired;i++)b.step();assert.deepEqual(b.errors,[]);assert.ok(fired>0);}

test('Archetto exact original flight/extra-arrow/bounce/selector/model fields are retained',()=>{
 assert.deepEqual(Object.keys(configs),[ID]);assert.equal(evidence.frameParity,false);assert.equal(evidence.sourceBundles.length,5);for(const x of evidence.sourceBundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);
 for(const face of['Front','Back']){assert.equal(evidence.models[ID][face].sha256,evidence.officialSkeletonBindings[ID][face].sha256);near(evidence.models[ID][face].hits.Attack[0],.567);near(evidence.models[ID][face].hits.Skill_2[0],.7);}
 assert.equal(rows(evidence.characters[ID]).find(x=>x.pathId==='-8096753425852574432')._selectTargetTiming,0);
 const s1=rows(evidence.skills.skchr_archet_1).find(x=>x.pathId==='4499921864132659280');assert.deepEqual(s1._extraProjectileKeys,['projectile_chr_archet_s1_2']);
 const p2=rows(evidence.projectiles.projectile_chr_archet_s2),bounce=p2.find(x=>x._bounceTimesAsDamageTimes);near(bounce._perDamageInterval,.15);assert.equal(bounce._allowRepetitionIfNoTarget,0);near(p2.find(x=>x._speedAfterFirstReach)._speedAfterFirstReach,6);assert.equal(rows(evidence.characters[ID]).find(x=>x.pathId==='-5019983563294223072')._selectTargetTiming,3);
});
test('all thirty ranks retain full skills, native offensive SP, charge counts and source unlocks',()=>{for(let skill=0;skill<3;skill++)for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill,rank}),u=deploy(),l=data.operators[ID].skills[skill].levels[rank-1];assert.equal(u.skill.id,configs[ID].skillIds[skill]);assert.equal(u.skill.spType,'attack');assert.equal(u.skill.manual,skill!==0);near(u.skill.spCost,l.spData.spCost);assert.equal(u.skill.maxCharges,l.spData.maxChargeTime);assert.equal(u.skill.noSkill,false);assert.deepEqual(b.errors,[]);}});
test('ordinary attack is one native ranged Physical arrow with CAST release selection and no inherited scatter',()=>{const{b,deploy}=make(),u=deploy(),old=enemy(b),next=enemy(b,{x:9}),extra=enemy(b,{x:5.1});b.forceAttack(u,[old]);u.atkCd=1000;move(b,old,9);move(b,next,5);advance(b,1);near(old.hp,100000);assert.equal(hits(b,u).length,1);near(200000-next.hp-extra.hp,u.s.atk);assert.equal(u.stats.attacks,1);});
test('S1 all ranks produce one scaled main and selected count of separate speed6 secondary flights',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({rank}),u=deploy(),e=enemy(b,{def:100}),others=Array.from({length:4},(_,i)=>enemy(b,{x:5.2+i*.1,def:100})),outside=enemy(b,{x:7.4});cast(b,u);const arrows=[];const add=b.addProjectile.bind(b);b.addProjectile=p=>{if(p.source===u)arrows.push(p.speed);return add(p);};shot(b,u,e,1.3);near(100000-e.hp,u.s.atk*u.skill.bb.atk_scale-100);assert.equal(arrows.filter(s=>s===10).length,1);assert.equal(arrows.filter(s=>s===6).length,u.skill.bb.max_target-1);const damaged=others.filter(x=>x.hp<100000);assert.equal(damaged.length,u.skill.bb.max_target-1);for(const x of damaged)near(100000-x.hp,u.s.atk*u.skill.bb.atk_scale_2-100);near(outside.hp,100000);assert.equal(u.skill.charges,0);}});
test('S1 secondary selection happens at primary arrival and secondary damage waits for its own flight',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{x:7}),z=enemy(b,{x:9});cast(b,u);b.forceAttack(u,[e]);u.atkCd=1000;firstFlight(b,u);move(b,z,8);advance(b,.17);near(e.hp,100000);near(z.hp,100000);advance(b,.07);assert.ok(e.hp<100000);near(z.hp,100000);advance(b,.25);near(100000-z.hp,u.s.atk*u.skill.bb.atk_scale_2);});
test('S1 refund is limited to dead pre-emission input, with live CAST replacement and post-emission spending',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);cast(b,u);b.forceAttack(u,[e]);u.atkCd=1000;b.kill(e);advance(b,1);assert.equal(u.skill.charges,1);const f=make(),v=f.deploy(),old=enemy(f.b),replacement=enemy(f.b,{x:5.1});cast(f.b,v);f.b.forceAttack(v,[old]);v.atkCd=1000;f.b.kill(old);advance(f.b,1);assert.ok(replacement.hp<100000);assert.equal(v.skill.charges,0);});
test('Landen Tactics promotion cadence is delayed and offensive-only for self and unhealable isolated snipers',()=>{for(const[elite,interval]of[[1,3],[2,2.5]]){const{b,deploy}=make({elite},[KROOS,EX,FANG]),k=deploy(KROOS,2,3),ex=deploy(EX,2,4),f=deploy(FANG,2,5),u=deploy();b.addBuff(k,{key:'test:flags',flags:{isolated:true,healFree:true,noHeal:true}});u.skill.setSpTotal(0);k.skill.setSpTotal(0);ex.skill.setSpTotal(0);f.skill.setSpTotal(0);advance(b,interval-.05);near(u.skill.sp,0);near(k.skill.sp,0);advance(b,.1);near(u.skill.sp,1);near(k.skill.sp,1);assert.ok(ex.skill.sp>0);near(f.skill.sp,b.time);assert.equal(f.findBuff('archetto:sniper-sp'),null);assert.ok(k.findBuff('archetto:sniper-sp'));}});
test('Landen target-free/source removal detaches only owned timer and new entrants get a fresh clock',()=>{const{b,deploy}=make({},[KROOS]),u=deploy();advance(b,2);const k=deploy(KROOS,2,3);k.skill.setSpTotal(0);advance(b,.6);near(k.skill.sp,0);advance(b,1.9);near(k.skill.sp,1);b.addBuff(k,{key:'test:free',flags:{untargetable:true}});advance(b,.1);assert.equal(k.findBuff('archetto:sniper-sp'),null);b.removeBuff(k,'test:free');advance(b,.1);assert.ok(k.findBuff('archetto:sniper-sp'));b.retreat(u);assert.equal(k.findBuff('archetto:sniper-sp'),null);});
test('Iron Bowstring blocks one accepted hit then grants selected potential SP exactly once',()=>{for(const[potential,sp]of[[1,7],[5,9]]){const{b,deploy}=make({skill:2,potential}),u=deploy(),e=enemy(b);u.skill.setSpTotal(0);b.dealDamage(e,u,{amount:100,type:'true'});near(u.hp,u.s.maxHp);near(u.skill.sp,sp);assert.equal(u.findBuff('archetto:shield'),null);b.dealDamage(e,u,{amount:100,type:'true'});near(u.hp,u.s.maxHp-100);near(u.skill.sp,sp);}});
test('shield does not consume on canceled/zero output or grant SP on non-consumed cleanup',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);u.skill.setSpTotal(0);b.dealDamage(e,u,{amount:0,type:'true'});assert.ok(u.findBuff('archetto:shield'));near(u.skill.sp,0);b.removeBuff(u,'archetto:shield');near(u.skill.sp,0);const f=make({elite:1,skill:1}),v=f.deploy();assert.equal(v.findBuff('archetto:shield'),null);});
test('S2 manual command is immediate locked cast, ready without target and rejects repeated cast during its clip',()=>{const{b,deploy}=make({skill:1}),u=deploy();u.skill.setSpTotal(27);assert.equal(u.skill.ready,true);assert.equal(b.activateOperator(ID),false);const e=enemy(b);assert.equal(b.activateOperator(ID),true);assert.equal(u.skill.charges,2);assert.equal(b.activateOperator(ID),false);advance(b,.65);near(e.hp,100000);advance(b,.22);assert.ok(e.hp<100000);assert.equal(u.mem.regularFormVisual.clip,'Skill_2');advance(b,.7);assert.equal(u.mem.regularFormVisual,null);assert.equal(b.activateOperator(ID),true);});
test('S2 all ranks preserve five-to-one ricochet hits, per-victim full mitigation and no revisit',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:1,rank}),u=deploy(),es=Array.from({length:6},(_,i)=>enemy(b,{x:5+i*.9,def:150}));cast(b,u);advance(b,4.5);const times=u.skill.bb.times,hit=u.s.atk*u.skill.bb.atk_scale-150;for(let i=0;i<times;i++)near(100000-es[i].hp,(times-i)*hit);near(es[times].hp,100000);assert.equal(hits(b,u).length,times*(times+1)/2);}});
test('S2 native .15 holds and speed10 then6 flights survive source withdrawal without queued duplicates',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b),next=enemy(b,{x:6.4}),speeds=[];const add=b.addProjectile.bind(b);b.addProjectile=p=>{if(p.source===u)speeds.push(p.speed);return add(p);};cast(b,u);firstFlight(b,u);b.retreat(u);advance(b,2);near(100000-e.hp,5*u.s.atk*1.4);near(100000-next.hp,4*u.s.atk*1.4);assert.deepEqual(speeds,[10,6]);});
test('S2 current-target death/disappearance terminates that arrow without replacement and cast control never resumes',()=>{for(const state of['dead','hidden','control']){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b),next=enemy(b,{x:5.5});cast(b,u);if(state==='control')b.applyStatus(u,'stun',{duration:.001});else{firstFlight(b,u);if(state==='dead')b.kill(e);else e.hidden=true;}advance(b,2);near(next.hp,100000);if(state==='control')near(e.hp,100000);}});
test('S2 rejected immunity preserves release, and a born controller has one total lifetime across slow flights',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);u.def.immune.add('stun');cast(b,u);b.applyStatus(u,'stun',{duration:.001});advance(b,2);near(100000-e.hp,5*u.s.atk*1.4);const f=make({skill:1}),v=f.deploy(),z=enemy(f.b,{x:7});const add=f.b.addProjectile.bind(f.b);f.b.addProjectile=p=>add({...p,speed:.01});cast(f.b,v);advance(f.b,7);near(z.hp,100000);assert.equal(f.b.projectiles.list.length,0);});
test('S3 all ranks release two targets times three separate arrows with one attack lifecycle and selected modifiers',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:2,rank}),u=deploy(),e=enemy(b,{def:100}),z=enemy(b,{x:5.2,def:100}),extra=enemy(b,{x:5.4});cast(b,u);near(u.s.atk,u.base.atk*(1+u.skill.bb.atk));const p=effectiveProfile(u),selected=acquireTargets(b,u,p);assert.equal(selected.length,2);shot(b,u,selected,1.5);for(const t of selected)near(100000-t.hp,3*(u.s.atk-100));near(extra.hp,100000);assert.equal(hits(b,u).length,6);assert.equal(u.stats.attacks,1);u.skill.end('duration');near(u.s.atk,u.base.atk);}});
test('natural S3 loop never multiplies each target into an extra burst and extends forward range exactly',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:8}),z=enemy(b,{x:8.2});assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);cast(b,u);assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,2);u.atkCd=0;b.step();u.atkCd=1000;advance(b,1.3);assert.equal(u.stats.attacks,1);assert.equal(hits(b,u).length,6);});
test('S3 control cancels unborn rounds, immunity preserves them, born arrows and already started native burst survive mode end',()=>{for(const end of['control','immune','mode','withdraw']){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:7});if(end==='immune')u.def.immune.add('stun');cast(b,u);b.forceAttack(u,[e]);u.atkCd=1000;firstFlight(b,u);const atk=u.s.atk;if(end==='mode')u.skill.end('duration');else if(end==='withdraw')b.retreat(u);else b.applyStatus(u,'stun',{duration:.001});advance(b,1);near(100000-e.hp,(end==='control'||end==='withdraw'?1:3)*(end==='mode'||end==='withdraw'?u.base.atk:atk));}});

test('S2 source no-SP gate covers unborn release then ordinary grant resumes at emission',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(b,u);assert.equal(u.s.flags.noSp,true);u.skill.gainSp(1, 'buff');near(u.skill.sp,0);advance(b,.6);u.skill.gainSp(1, 'buff');near(u.skill.sp,0);advance(b,.2);assert.equal(u.s.flags.noSp,undefined);u.skill.gainSp(1, 'buff');near(u.skill.sp,1);});
test('S2 invalid unborn input emits its saved-position arrow, never a guessed replacement or refund',()=>{for(const state of['dead','hidden']){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{x:7}),next=enemy(b,{x:9});cast(b,u);if(state==='dead')b.kill(e);else e.hidden=true;move(b,e,9);firstFlight(b,u);const p=b.projectiles.list.find(p=>p.source===u);assert.ok(p);assert.equal(p.target,null);near(p.tx,7);near(p.ty,3);advance(b,1);near(next.hp,100000);assert.equal(u.skill.charges,0);}});
