// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with { type: 'json' };
import source from '../data/arkpedia-nian-prefabs.json' with { type: 'json' };
import { NIAN_OPERATORS as configs } from '../shared/arkpedia/nian-operators.js';
import { prepareNianSquad } from '../server/sim/content/arkpedia-nian.js';
import { StandardBattle } from '../server/sim/arkpedia.js';
import { defaultBuild, recordFor } from '../shared/arkpedia/loadout.js';
import { effectiveProfile } from '../server/sim/ai.js';
const ID='char_2014_nian',BEAGLE='char_122_beagle',FANG='char_123_fang',SHARP='char_4063_quartz';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const rows=r=>r.flatMap(x=>x.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id=ID,{skill=0,rank=10,elite=2,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} snapshot required`);elite=Math.min(elite,op.phases.length-1);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,skillId:op.skills[skill].id,skillRank:Math.min(rank,[4,7,10][elite]),potential};}
function make(opts={},extra=[BEAGLE,FANG,SHARP]){const d=structuredClone(data);d.stage.geometry.waves[0].spawns=[];d.stage.battle.dp_per_second=0;d.stage.geometry.rows=19;d.stage.geometry.cols=21;d.stage.geometry.tileGrid=Array.from({length:19},()=>Array(21).fill(2));const b=new StandardBattle(d,opts.support?{operators:extra.map(id=>build(id)),support:{id:ID,skillId:'skchr_nian_1'}}:{operators:[build(ID,opts),...extra.map(id=>build(id))]});b.autoFinish=false;b.setViewport('fullscreen-workspace');b.recordEvents=true;b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));const receipts=[];b.on('damaged',c=>receipts.push({...c,time:b.time}));const deploy=(id=ID,r=3,c=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,r,c,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;};return{b,deploy,receipts};}
function advance(b,s){for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);}
function enemy(b,{x=5,y=3,hp=100000,def=0,res=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[y,x]});Object.assign(e.base,{maxHp:100000,def,res,moveSpeed:0});e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,x,y=3){e.x=x;e.y=y;e.tileR=y;e.tileC=x;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(b,u){u.skill.setSpTotal(u.skill.spCost);assert.equal(b.activateOperator(ID),true);u.atkCd=1000;}
function shot(b,u,e){assert.equal(b.forceAttack(u,Array.isArray(e)?e:[e]),true);u.atkCd=1000;}
const own=(r,u,e)=>r.filter(x=>x.source===u&&(!e||x.target===e));
function incoming(b,e,u,extra={}){return b.dealDamage(e,u,{amount:10,type:'phys',isAttack:true,...extra});}

test('Nian retains all three exact skill IDs, original mode attack types, shield/squad fields and native face bytes',()=>{assert.deepEqual(Object.keys(configs),[ID]);assert.deepEqual(configs[ID].skillIds,['skchr_nian_1','skchr_nian_2','skchr_nian_3']);assert.equal(source.frameParity,false);assert.equal(source.source.bundles.length,5);for(const x of source.source.bundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);for(const face of['Front','Back']){assert.equal(source.models[ID][face].sha256,source.originalFacingBindings[ID][face].sha256);near(source.models[ID][face].hits.Attack_Loop[0],.1);near(source.models[ID][face].hits.Skill_2_Loop[0],.1);}const cs=rows(source.characters[ID]);assert.equal(cs.find(x=>x.pathId==='4292495747785807228')._damageType,1);assert.equal(cs.find(x=>x.pathId==='1659593818324522364')._damageType,2);assert.equal(cs.find(x=>x.pathId==='5577237372275971452')._damageType,1);assert.equal(source.buffTemplates['inverse_damage[magic]'].eventToActions.ON_TAKE_DAMAGE[0]._filterModifierCancelled,false);assert.equal(source.models[ID].Back.durations.Skill_1_Loop,undefined);});
test('squad MaxHP promotion/potential law affects both Nian and a Defender before Nian deploys but no other profession',()=>{for(const[elite,potential,pct]of[[0,1,0],[1,1,.08],[1,5,.12],[2,1,.16],[2,5,.20]]){const{b,deploy}=make({elite,potential}),a=deploy(BEAGLE,1,1),f=deploy(FANG,1,3),u=deploy();near(a.s.maxHp,a.base.maxHp*(1+pct));near(u.s.maxHp,u.base.maxHp*(1+pct));near(f.s.maxHp,f.base.maxHp);near(a.hp,a.s.maxHp);b.retreat(u);near(a.s.maxHp,a.base.maxHp*(1+pct));}});
test('named squad HP contribution is idempotent, additive with foreign producers and falls off when source records disappear',()=>{const n=recordFor(build(),data),z=recordFor(build(BEAGLE),data);z.arkpedia.modifiers.hpPct=.2;const records={n,z};prepareNianSquad(records);prepareNianSquad(records);near(z.arkpedia.modifiers.hpPct,.36);delete records.n;prepareNianSquad(records);near(z.arkpedia.modifiers.hpPct,.2);});
test('strongest identical Nian squad contribution does not multiply two selected source records',()=>{const n=recordFor(build(),data),p=recordFor(build(ID,{potential:5}),data),z=recordFor(build(BEAGLE),data);prepareNianSquad({n,p,z});near(z.arkpedia.modifiers.hpPct,.20);});
test('normal first-only native Begin+.1 event deals one Physical melee attack, not block-count AoE',()=>{const{b,deploy,receipts}=make(),u=deploy(),a=enemy(b),z=enemy(b,{x:5.1});u.atkCd=0;b.step();u.atkCd=1000;advance(b,.5);near(a.hp,100000);advance(b,.2);assert.equal(own(receipts,u).length,1);near(100000-a.hp,u.s.atk);near(z.hp,100000);assert.equal(own(receipts,u)[0].dmg.applyWay,'melee');assert.equal(u.stats.attacks,1);});
test('ordinary CAST selects entering victim and rejects leaving or target-free input at native release',()=>{for(const free of[false,true]){const{b,deploy}=make(),u=deploy(),old=enemy(b),next=enemy(b,{x:15});shot(b,u,old);move(b,old,15);move(b,next,5);if(free)b.addBuff(next,{key:'test:free',flags:{untargetable:true}});advance(b,.8);near(old.hp,100000);assert.equal(next.hp<100000,!free);}});
test('first Begin is not repeated while engaged; native End resets it on the next encounter',()=>{const{b,deploy}=make(),u=deploy(),a=enemy(b);shot(b,u,a);advance(b,.8);const hp=a.hp;shot(b,u,a);advance(b,.2);assert.ok(a.hp<hp);move(b,a,15);advance(b,1.6);assert.equal(u.mem.nianEngaged,false);move(b,a,5);const before=a.hp;shot(b,u,a);advance(b,.4);near(a.hp,before);advance(b,.3);assert.ok(a.hp<before);});
test('ordinary and S1 source cap2 release respects both facing original event curves under ASPD buffs',()=>{for(const dir of['RIGHT','DOWN','LEFT','UP']){const{b,deploy}=make(),u=deploy(ID,5,5,dir),x=dir==='RIGHT'?6:dir==='LEFT'?4:5,y=dir==='UP'?6:dir==='DOWN'?4:5,e=enemy(b,{x,y});b.addBuff(u,{key:'test:fast',mods:{aspd:300}});shot(b,u,e);advance(b,.25);near(e.hp,100000);advance(b,.15);assert.ok(e.hp<100000);}});
test('S1 all ten ranks retain additive ATK/DEF, Arts output and exact duration cleanup',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({rank}),u=deploy(),e=enemy(b,{def:10000,res:20});b.addBuff(u,{key:'foreign',mods:{atkPct:.1,defPct:.2}});cast(b,u);near(u.s.atk,u.base.atk*(1.1+u.skill.bb.atk));near(u.s.def,u.base.def*(1.2+u.skill.bb.def));shot(b,u,e);advance(b,.8);near(100000-e.hp,u.s.atk*.8);advance(b,30);assert.equal(u.skill.active,false);near(u.s.atk,u.base.atk*1.1);near(u.s.def,u.base.def*1.2);}});
test('S1 switch_mode preserves pending family and evaluates its new Arts damage at release without replayed Begin',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{def:10000});shot(b,u,e);advance(b,.2);cast(b,u);advance(b,.5);near(100000-e.hp,u.s.atk);assert.equal(u.stats.attacks,1);});
test('S1 ending during an unborn release restores Physical without invented restart',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{def:100});cast(b,u);shot(b,u,e);advance(b,.2);u.skill.end('test');advance(b,.5);near(100000-e.hp,u.s.atk-100);});
test('T2 three shields are E2 only and restore each actual redeployment',()=>{for(const elite of[0,1,2]){const{b,deploy}=make({elite}),u=deploy(),e=enemy(b);const initial=u.hp;for(let i=0;i<3;i++)incoming(b,e,u,{type:'true',amount:10});near(initial-u.hp,elite===2?0:30);incoming(b,e,u,{type:'true',amount:10});near(initial-u.hp,elite===2?10:40);b.retreat(u);b.bench[ID].readyAt=b.time;const z=deploy();assert.equal(z.findBuff('nian_t_2')?.shieldHits??0,elite===2?3:0);}});
test('T2 blocks Physical/Arts/True but not direct HP loss or elemental gauge and does not consume on dodge',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);const hp=u.hp;b.addBuff(u,{key:'dodge',mods:{dodgePhys:1}});incoming(b,e,u);assert.equal(u.findBuff('nian_t_2').shieldHits,3);b.removeBuff(u,'dodge');b.loseHp(u,10,{source:e});incoming(b,e,u,{type:'element',element:'burn',amount:10});assert.equal(u.findBuff('nian_t_2').shieldHits,3);for(const type of['phys','arts','true'])incoming(b,e,u,{type});near(u.hp,hp-10);assert.equal(u.findBuff('nian_t_2'),null);});
test('S2 all ten ranks raise DEF/block, prevent attacks and counter with selected current ATK Arts',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy,receipts}=make({skill:1,rank}),u=deploy(),e=enemy(b,{res:20});cast(b,u);near(u.s.def,u.base.def*(1+u.skill.bb.def));near(u.s.blockCnt,u.base.blockCnt+1);assert.equal(effectiveProfile(u).noAttack,true);u.atkCd=0;b.step();near(e.hp,100000);assert.equal(u.stats.attacks,0);incoming(b,e,u,{type:'true'});near(100000-e.hp,u.s.atk*u.skill.bb.atk_scale*.8);const r=own(receipts,u,e)[0];assert.equal(r.dmg.isAttack,true);assert.equal(r.dmg.applyWay,'none');assert.equal(u.stats.attacks,0);near(e.findBuff('silence').timeLeft,u.skill.bb.silence);u.skill.end('test');near(u.s.def,u.base.def);near(u.s.blockCnt,u.base.blockCnt);assert.equal(Boolean(u.s.flags.disarm),false);}});
test('S2 switch_mode_restart_fsm cancels unborn ordinary release rather than leaking a disarmed attack',()=>{const{b,deploy,receipts}=make({skill:1}),u=deploy(),e=enemy(b);shot(b,u,e);advance(b,.2);cast(b,u);advance(b,.6);near(e.hp,100000);assert.equal(own(receipts,u).length,0);});
test('S2 source pre-receipt mapping counters shielded and dodged attacks but invulnerability prevents dispatch',()=>{for(const state of['shield','dodge','invulnerable']){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(b,u);if(state==='dodge')b.addBuff(u,{key:'test:protect',mods:{dodgePhys:1}});if(state==='invulnerable')b.addBuff(u,{key:'test:protect',flags:{invulnerable:true}});const hp=u.hp;incoming(b,e,u);near(u.hp,hp);near(100000-e.hp,state==='invulnerable'?0:u.s.atk*u.skill.bb.atk_scale);}});
test('S2 enemy-source output has no invented IsAttack filter and excludes allied/source-less/HP-loss/gauge receipts',()=>{const{b,deploy}=make({skill:1}),u=deploy(),a=deploy(FANG,1,1),e=enemy(b);cast(b,u);incoming(b,e,u,{type:'true',isAttack:false,tags:['dot']});near(100000-e.hp,u.s.atk*u.skill.bb.atk_scale);const hp=e.hp;b.dealDamage(a,u,{amount:10,type:'true'});b.dealDamage(null,u,{amount:10,type:'true'});b.dealDamage(e,u,{amount:10,type:'true',sourceless:true});b.loseHp(u,10,{source:e});incoming(b,e,u,{type:'element',element:'burn',amount:10});near(e.hp,hp);});
test('S2 counter remains active during Nian control; Silence immunity suppresses only the debuff',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(b,u);b.applyStatus(u,'stun',{duration:3});e.def.immune.add('silence');incoming(b,e,u,{type:'true'});near(100000-e.hp,u.s.atk*u.skill.bb.atk_scale);assert.equal(e.findBuff('silence'),null);});
test('S2 counter uses later current Nian ATK and current target RES rather than an incoming-damage proportion',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{res:50});cast(b,u);b.addBuff(u,{key:'late',mods:{atkPct:.4}});incoming(b,e,u,{amount:1,type:'true'});near(100000-e.hp,u.s.atk*u.skill.bb.atk_scale*.5);});
test('S2 exact duration detaches counter and silence creation while preserving already born nonderived Silence',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);cast(b,u);advance(b,u.skill.duration-1);incoming(b,e,u,{type:'true'});advance(b,1.2);const hp=e.hp;incoming(b,e,u,{type:'true'});near(e.hp,hp);assert.ok(e.findBuff('silence'));near(u.s.blockCnt,u.base.blockCnt);});
test('S3 all ten ranks give owner ATK only and others DEF/block/Resist without self or double aura stats',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:2,rank}),u=deploy(),a=deploy(FANG,3,5);cast(b,u);near(u.s.atk,u.base.atk*(1+u.skill.bb['nian_s_3[self].atk']));near(u.s.def,u.base.def);near(u.s.blockCnt,u.base.blockCnt);near(b.resistOf(u),0);near(a.s.def,a.base.def*(1+u.skill.bb['nian_s_3[ally].def']));near(a.s.blockCnt,a.base.blockCnt+1);near(b.resistOf(a),.5);u.skill.end('test');near(a.s.def,a.base.def);near(a.s.blockCnt,a.base.blockCnt);near(b.resistOf(a),0);}});
test('S3 native mode3 Physical one-victim strike follows literal Begin.5 then Skill2Loop.1 capped1',()=>{const{b,deploy,receipts}=make({skill:2}),u=deploy(),e=enemy(b,{def:100,res:80}),z=enemy(b,{x:5.1});b.addBuff(u,{key:'fast',mods:{aspd:300}});cast(b,u);advance(b,.55);assert.equal(u.mem.regularFormVisual.clip,'Skill_2_Idle');shot(b,u,e);advance(b,.05);near(e.hp,100000);advance(b,.15);near(100000-e.hp,u.s.atk-100);near(z.hp,100000);assert.equal(own(receipts,u).length,1);assert.equal(own(receipts,u)[0].dmg.type,'phys');});
test('S3 natural loop never acquires surrounding aura victims as attack targets',()=>{const{b,deploy,receipts}=make({skill:2}),u=deploy(),front=enemy(b),auraOnly=enemy(b,{x:4,y:5});cast(b,u);advance(b,.6);u.atkCd=0;b.step();u.atkCd=1000;advance(b,.2);near(100000-front.hp,u.s.atk);near(auraOnly.hp,100000);assert.equal(own(receipts,u).length,1);});
test('S3 aura accepts unhealable Operators and friendly camouflage/stealth but drops hidden/target-free/isolated targets',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=deploy(SHARP,3,5);b.addBuff(a,{key:'free-heal',flags:{healFree:true,camou:true,stealth:true}});cast(b,u);assert.ok(a.findBuff('nian_s_3[ally]'));b.addBuff(a,{key:'free-target',flags:{untargetable:true}});b.step();assert.equal(a.findBuff('nian_s_3[ally]'),null);b.removeBuff(a,'free-target');b.step();assert.ok(a.findBuff('nian_s_3[ally]'));a.hidden=true;b.step();assert.equal(a.findBuff('nian_s_3[ally]'),null);a.hidden=false;b.addBuff(a,{key:'isolated',flags:{isolated:true}});b.step();assert.equal(a.findBuff('nian_s_3[ally]'),null);});
test('S3 owned aura range exit/reentry is immediate and preserves an independent DEF/Resist producer',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=deploy(FANG,3,5);b.addBuff(a,{key:'foreign',mods:{defPct:.2}});b.applyStatus(a,'resist',{key:'foreign-resist',value:.7});cast(b,u);near(a.s.def,a.base.def*(1.2+u.skill.bb['nian_s_3[ally].def']));near(b.resistOf(a),.7);a.x=15;a.tileC=15;b.step();near(a.s.def,a.base.def*1.2);near(b.resistOf(a),.7);a.x=5;a.tileC=5;b.step();assert.ok(a.findBuff('nian_s_3[ally]'));u.skill.end('test');assert.ok(a.findBuff('foreign'));assert.ok(a.findBuff('foreign-resist'));});
test('S3 Resist halves supported controlled duration without doubling the existing-status decay clock',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=deploy(FANG,3,5);cast(b,u);b.applyStatus(a,'stun',{duration:4});near(a.findBuff('stun').timeLeft,2);advance(b,1.9);assert.ok(a.findBuff('stun'));advance(b,.2);assert.equal(a.findBuff('stun'),null);});
test('S3 source withdrawal removes only its ally buffs and redeployment gets a fresh owned lifecycle',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=deploy(FANG,3,5);cast(b,u);assert.ok(a.findBuff('nian_s_3[ally]'));b.retreat(u);assert.equal(a.findBuff('nian_s_3[ally]'),null);near(b.resistOf(a),0);b.bench[ID].readyAt=b.time;const z=deploy();cast(b,z);assert.ok(a.findBuff('nian_s_3[ally]'));assert.equal(a.findBuff('nian_s_3[ally]').source,z);});
test('S3 selected duration holds SP exactly while active and cleanup restores ordinary Physical profile',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=deploy(FANG,3,5);cast(b,u);assert.equal(u.skill.gainSp(100,'test'),0);advance(b,u.skill.duration+.1);assert.equal(u.skill.active,false);assert.equal(a.findBuff('nian_s_3[ally]'),null);assert.ok(u.skill.gainSp(1,'test')>0);near(u.s.atk,u.base.atk);});
test('ordinary sub-tick accepted control cancels unborn attack while immunity rejection preserves it',()=>{for(const immune of[false,true]){const{b,deploy}=make(),u=deploy(),e=enemy(b);if(immune)u.def.immune.add('stun');shot(b,u,e);b.applyStatus(u,'stun',{duration:.001});advance(b,.8);assert.equal(e.hp<100000,immune);}});
test('S3 activation/attack presentation uses only actual source clips across all four facings',()=>{for(const dir of['RIGHT','DOWN','LEFT','UP']){const{b,deploy}=make({skill:2}),u=deploy(ID,5,5,dir),x=dir==='RIGHT'?6:dir==='LEFT'?4:5,y=dir==='UP'?6:dir==='DOWN'?4:5,e=enemy(b,{x,y});cast(b,u);assert.equal(u.mem.regularFormVisual.clip,'Skill_2_Begin');advance(b,.6);shot(b,u,e);assert.equal(u.mem.nianClip,'Skill_2_Loop');advance(b,.2);assert.ok(e.hp<100000);u.skill.end('test');assert.equal(u.mem.regularFormVisual.clip,'Skill_2_End');advance(b,.6);assert.equal(u.mem.regularFormVisual,null);}});

test('maxed support Nian applies selected20percent HP to bench Defenders without deploying source',()=>{const{b,deploy}=make({support:true},[BEAGLE,FANG]),a=deploy(BEAGLE,1,1),f=deploy(FANG,1,3);near(a.s.maxHp,a.base.maxHp*1.2);near(f.s.maxHp,f.base.maxHp);assert.ok(!b.bench[ID].unit);});
