// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with {type:'json'};
import evidence from '../data/arkpedia-mlynar-prefabs.json' with {type:'json'};
import {MLYNAR_OPERATORS as configs} from '../shared/arkpedia/mlynar-operators.js';
import {StandardBattle} from '../server/sim/arkpedia.js';
import {defaultBuild} from '../shared/arkpedia/loadout.js';
import {acquireTargets,effectiveProfile} from '../server/sim/ai.js';
const ID='char_4064_mlynar',KAZ='char_237_gravel',OTHER='char_208_melan';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const rows=r=>r.flatMap(x=>x.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id=ID,{skill=0,rank=10,elite=null,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} snapshot needed`);elite??=op.phases.length-1;rank=Math.min(rank,elite===2?10:elite===1?7:4);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,potential,skillId:op.skills[skill].id,skillRank:rank};}
function make(opts={},more=[]){const d=structuredClone(data);d.stage.geometry.waves[0].spawns=[];d.stage.battle.dp_per_second=0;const b=new StandardBattle(d,{operators:[build(ID,opts),...more.map(id=>build(id))]});b.setViewport('fullscreen-workspace');b.autoFinish=false;b.recordEvents=true;b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));b.receipts=[];b.on('damaged',c=>b.receipts.push({...c,time:b.time}));return{b,deploy:(id=ID,r=3,c=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,r,c,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;}};}
function advance(b,s){for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);}
function enemy(b,{r=3,c=5,hp=100000,def=0,fly=false}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[r,c]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:0});e.def={...e.def,immune:new Set(e.def.immune)};e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',persist:true,flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,r,c){e.x=c;e.y=r;e.tileR=r;e.tileC=c;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(u){u.skill.setSpTotal(u.skill.spCost);assert.equal(u.skill.activate('test'),true);u.atkCd=1000;}
function ready(b,u){cast(u);advance(b,.4);}
function shot(b,u,targets){assert.equal(b.forceAttack(u,targets==null?undefined:Array.isArray(targets)?targets:[targets]),true);u.atkCd=1000;}
function atkEvent(b,u){return b._evq.filter(x=>x[0]==='atk'&&x[1]===u.id).at(-1)[4];}
function receipts(b,e,tag=null){return b.receipts.filter(c=>c.target===e&&(!tag||c.dmg.tags.includes(tag)));}
function reflectMark(u,a=u){return a.findBuff(`mlynar:inverse:${u.id}`);}
function full(b,u){advance(b,40+b.dt);assert.equal(u.mem.mlynarStacks,40);}

test('Mlynar retains complete source hierarchy, exact faces and honestly scoped dispatcher boundaries',()=>{assert.deepEqual(Object.keys(configs),[ID]);assert.equal(evidence.frameParity,false);assert.equal(evidence.sourceBundles.length,4);for(const x of evidence.sourceBundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);for(const facing of['Front','Back'])assert.equal(evidence.originalModels[ID][facing].sha256,evidence.officialSkeletonBindings[ID][facing].sha256);const c=rows(evidence.characters[ID]);for(const id of['-2573672186445041373','7735429415023866147','-2279883596139859677'])assert.equal(c.find(x=>x.pathId===id)._maxAnimScale,-1);assert.equal(evidence.buffTemplates['damage_resistance[IncludePure]'].eventToActions.ON_TAKE_DAMAGE[0]._damageMask,'ANY_ATTACK');assert.equal(evidence.buffTemplates['mlynar_t_2[inverse]'].eventToActions.ON_TAKE_DAMAGE[0]._attackType,'NORMAL');assert.ok(evidence.verificationLimits.some(x=>x.includes('_preprocessData1')));});
test('all thirty exact selected skill ranks instantiate with native rank durations, SP and coefficients',()=>{for(let skill=0;skill<3;skill++)for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill,rank}),u=deploy();const s=data.operators[ID].skills[skill].levels[rank-1];assert.equal(u.skill.id,configs[ID].skillIds[skill]);near(u.skill.spCost,s.spData.spCost);cast(u);near(u.skill.timeLeft,s.duration);near(u.skill.bb['attack@atk_scale'],s.blackboard.find(x=>x.key==='attack@atk_scale').value);assert.deepEqual(b.errors,[]);}});
test('E0, E1, E2 and selected potential talents remain distinct',()=>{for(const[elite,potential,scale]of[[0,1,1],[1,1,1.05],[1,3,1.08],[2,1,1.1],[2,3,1.13]]){const{deploy}=make({elite,potential}),u=deploy();near(u.mem.mlynarScale,scale);assert.equal(u.def.talents.length,elite===0?0:elite===1?1:2);assert.equal(Boolean(reflectMark(u)),elite===2);}});
test('actual idle deployment has Block0 and cannot attack in the natural loop',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);near(u.s.blockCnt,0);u.atkCd=0;advance(b,2.2);near(e.hp,100000);assert.equal(u.stats.attacks,0);assert.equal(e.blockedBy,null);});
test('trait starts one second after a fractional delayed actual deployment and caps at forty stacks',()=>{const{b,deploy}=make();advance(b,1.5);const u=deploy(),at=b.time;advance(b,.9);near(u.s.atk,u.base.atk);assert.equal(u.mem.mlynarStacks,0);advance(b,.1);near(b.time-at,1);assert.equal(u.mem.mlynarStacks,0);b.step();assert.equal(u.mem.mlynarStacks,1);near(u.s.atk,u.base.atk*1.05);advance(b,42);assert.equal(u.mem.mlynarStacks,40);near(u.s.atk,u.base.atk*3);});
test('idle charge is one independent additive ATK term beside percentage, flat and final buffs',()=>{const{b,deploy}=make(),u=deploy();b.addBuff(u,{key:'foreign',mods:{atkPct:.2,atkFlat:100,atkFinalFlat:50}});full(b,u);near(u.s.atk,(u.base.atk+100)*3.2+50);assert.ok(u.findBuff('foreign'));});
test('S1 charge freezes while active, then count clears but permanent birth interval keeps its phase',()=>{const{b,deploy}=make(),u=deploy();advance(b,2.5);assert.equal(u.mem.mlynarStacks,2);cast(u);advance(b,1.1);assert.equal(u.mem.mlynarStacks,2);u.skill.end('manual');near(u.s.atk,u.base.atk);near(u.s.blockCnt,0);advance(b,.2);assert.equal(u.mem.mlynarStacks,0);advance(b,.2+b.dt);assert.equal(u.mem.mlynarStacks,1);near(u.s.atk,u.base.atk*1.05);});
test('Wanderer first high-count poll is .05 after birth and later checks use the native .2 interval',()=>{const{b,deploy}=make();const es=[enemy(b),enemy(b,{c:5.1}),enemy(b,{c:5.2})],u=deploy();near(u.mem.mlynarScale,1.1);near(u.s.trueTakenMul,1);b.step();near(u.mem.mlynarScale,1.1);b.step();b.step();near(u.mem.mlynarScale,1.15);near(u.s.trueTakenMul,.85);move(b,es[2],1,8);advance(b,.15);near(u.mem.mlynarScale,1.15);advance(b,.1);near(u.mem.mlynarScale,1.1);near(u.s.trueTakenMul,1);});
test('nearby checker counts both motions and unavailable attack targets, but excludes hidden/dead/outside bodies',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b),a=enemy(b,{fly:true}),z=enemy(b,{c:5.1});b.addBuff(a,{key:'free',flags:{untargetable:true,stealth:true}});b.applyStatus(z,'sleep',{duration:5});advance(b,.1);near(u.mem.mlynarScale,1.15);z.hidden=true;advance(b,.25);near(u.mem.mlynarScale,1.1);z.hidden=false;advance(b,.25);near(u.mem.mlynarScale,1.15);b.kill(z);advance(b,.25);near(u.mem.mlynarScale,1.1);move(b,e,1,8);move(b,a,1,8);advance(b,.25);near(u.mem.mlynarScale,1.1);});
test('Wanderer applies selected pre-DEF main damage scale at E1/E2 and potential, not post-mitigation',()=>{for(const[elite,potential,scale]of[[1,1,1.05],[1,3,1.08],[2,1,1.1],[2,3,1.13]]){const{b,deploy}=make({elite,potential}),u=deploy(),e=enemy(b,{def:100});ready(b,u);const atk=u.s.atk;shot(b,u,e);advance(b,.6);near(100000-e.hp,atk*u.skill.bb['attack@atk_scale']*scale-100);}});
test('IncludePure chosen Sanctuary reduces physical, Arts and True, but not direct HP loss',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);enemy(b,{c:5.1});enemy(b,{c:5.2});advance(b,.1);for(const type of['phys','arts','true']){const hp=u.hp;const amount=type==='phys'?u.s.def+100:type==='arts'?100/(1-u.s.res/100):100;b.dealDamage(e,u,{amount,type});near(hp-u.hp,85);}const hp=u.hp;b.loseHp(u,100);near(hp-u.hp,100);});
test('stronger ordinary protection cannot erase Pure channel and removing owned Mlynar aura preserves foreign source',()=>{const{b,deploy}=make(),u=deploy(),es=[enemy(b),enemy(b,{c:5.1}),enemy(b,{c:5.2})];b.applyStatus(u,'sanctuary',{key:'foreign',value:.4});advance(b,.1);near(u.s.physTakenMul,.6);near(u.s.artsTakenMul,.6);near(u.s.trueTakenMul,.85);b.kill(es[2]);advance(b,.25);near(u.s.physTakenMul,.6);near(u.s.trueTakenMul,1);assert.ok(u.findBuff('foreign'));});
test('S1 all source rank DEF percentages compose with unrelated DEF and restore on finish',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({rank}),u=deploy();b.addBuff(u,{key:'foreign',mods:{defPct:.2}});cast(u);near(u.s.def,u.base.def*(1+.2+u.skill.bb.def));near(u.s.blockCnt,u.base.blockCnt);u.skill.end('manual');near(u.s.def,u.base.def*1.2);near(u.s.blockCnt,0);assert.ok(u.findBuff('foreign'));}});
test('S1 source startup, .533 release and end forms prevent ordinary startup/ending attacks',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b);cast(u);assert.equal(u.mem.regularFormVisual.clip,'Skill_1_Start');u.atkCd=0;advance(b,.3);near(e.hp,100000);assert.equal(u.stats.attacks,0);u.atkCd=1000;advance(b,.1);assert.equal(u.mem.regularFormVisual.clip,'Skill_1_Idle');shot(b,u,e);near(atkEvent(b,u).windup,.533);advance(b,.5);near(e.hp,100000);advance(b,.1);assert.ok(e.hp<100000);u.skill.end('manual');assert.equal(u.mem.regularFormVisual.clip,'Skill_1_End');advance(b,.4);assert.equal(u.mem.regularFormVisual,null);near(u.s.blockCnt,0);});
test('S1 and S2 remain ground-only while S3 source ALL acquires air',()=>{for(const skill of[0,1,2]){const{b,deploy}=make({skill}),u=deploy(),e=enemy(b,{fly:true});ready(b,u);const targets=acquireTargets(b,u,effectiveProfile(u));assert.equal(targets.includes(e),skill===2);}});
test('all native direction clips retain uncapped ASPD-scaled source events',()=>{for(const dir of['RIGHT','LEFT','DOWN','UP'])for(const skill of[0,1,2]){const{b,deploy}=make({skill}),u=deploy(ID,3,4,dir),e=enemy(b,{r:dir==='DOWN'?2:dir==='UP'?4:3,c:dir==='LEFT'?3:dir==='RIGHT'?5:4});ready(b,u);b.addBuff(u,{key:'speed',mods:{aspd:100}});shot(b,u,e);assert.equal(atkEvent(b,u).animation,`Skill_${skill+1}_Loop`);near(atkEvent(b,u).windup,(skill===1?.267:.533)/2);advance(b,.5);assert.ok(e.hp<100000);}});
test('native forms hold SP gains through exact Start/End gates and active skill',()=>{const{b,deploy}=make({skill:1}),u=deploy();cast(u);near(u.skill.gainSp(2,'talent'),0);advance(b,.4);near(u.skill.gainSp(2,'talent'),0);u.skill.end('manual');near(u.skill.gainSp(2,'talent'),0);advance(b,.4);near(u.skill.gainSp(2,'talent'),2);});
test('S2 BAT+.3 is additive seconds before unrelated percent and multiplier, with cleanup',()=>{const{b,deploy}=make({skill:1}),u=deploy();b.addBuff(u,{key:'foreign',mods:{batFlat:.2,batPct:.3,batMul:.8}});cast(u);near(u.s.bat,(u.base.bat+.2+.3)*1.3*.8);u.skill.end('manual');near(u.s.bat,(u.base.bat+.2)*1.3*.8);assert.ok(u.findBuff('foreign'));});
test('S2 releases two separately mitigated hits at .267 and .567 with shared attack identity',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{def:100});ready(b,u);const atk=u.s.atk,amount=atk*u.skill.bb['attack@atk_scale']*1.1-100;shot(b,u,e);advance(b,.333);near(100000-e.hp,amount);advance(b,.2);near(100000-e.hp,amount);advance(b,.1);near(100000-e.hp,2*amount);const r=receipts(b,e);assert.equal(r.length,2);assert.equal(r[0].dmg.attackId,r[1].dmg.attackId);assert.equal(r[0].dmg.applyWay,'melee');});
test('S2 natural attack loop has one double family each source1.5 seconds, without duplicate releases',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);ready(b,u);u.atkCd=0;advance(b,3.7);assert.equal(u.stats.attacks,3);assert.equal(receipts(b,e).length,6);});
test('S2 accepted sub-tick control after first strike cancels unborn second; immune rejection does not',()=>{for(const immune of[false,true]){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);ready(b,u);if(immune)u.def={...u.def,immune:new Set([...u.def.immune,'stun'])};shot(b,u,e);advance(b,.333);const hp=e.hp;b.applyStatus(u,'stun',{duration:.001});advance(b,.4);assert.equal(receipts(b,e).length,immune?2:1);if(!immune)near(e.hp,hp);}});
test('S2 dead/hidden original victim does not redirect its delayed second strike',()=>{for(const why of['dead','hidden']){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b),z=enemy(b,{c:5.1});ready(b,u);shot(b,u,e);advance(b,.333);if(why==='dead')b.kill(e);else e.hidden=true;advance(b,.4);near(z.hp,100000);assert.equal(receipts(b,e).length,1);}});
test('S2 manual cancel and source withdrawal cancel a still-unborn second strike',()=>{for(const why of['manual','retreat']){const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);ready(b,u);shot(b,u,e);advance(b,.333);const hp=e.hp;if(why==='manual')u.skill.end('manual');else b.retreatOperator(ID);advance(b,.4);near(e.hp,hp);}});
test('only actual S2 DoubleAttack kill retains exact held charge after manual end',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b,{hp:1});advance(b,8.5);assert.equal(u.mem.mlynarStacks,8);ready(b,u);shot(b,u,e);advance(b,.4);assert.equal(e.alive,false);assert.equal(u.mem.mlynarKilled,true);u.skill.end('manual');assert.equal(u.mem.mlynarStacks,8);near(u.s.atk,u.base.atk*1.4);advance(b,.8);assert.equal(u.mem.mlynarStacks,9);});
test('S2 reflection kill has credit but cannot set DoubleAttack retention marker',()=>{const{b,deploy}=make({skill:1}),u=deploy();advance(b,8.5);ready(b,u);const e=enemy(b,{hp:1});b.dealDamage(e,u,{amount:1,type:'true'});assert.equal(e.alive,false);assert.equal(u.mem.mlynarKilled,false);u.skill.end('manual');assert.equal(u.mem.mlynarStacks,0);near(u.s.atk,u.base.atk);});
test('S3 captures double additive held trait only, preserves foreign ATK, and clears original stacks',()=>{const{b,deploy}=make({skill:2}),u=deploy();b.addBuff(u,{key:'foreign',mods:{atkPct:.2,atkFlat:100,atkFinalFlat:50}});full(b,u);cast(u);assert.equal(u.mem.mlynarStacks,0);near(u.mem.mlynarCapturedPct,4);near(u.s.atk,(u.base.atk+100)*5.2+50);u.skill.end('manual');near(u.s.atk,(u.base.atk+100)*1.2+50);assert.ok(u.findBuff('foreign'));});
test('S3 native minimum-one capture differs from an idle zero-stack coefficient and all ranks retain rider values',()=>{for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill:2,rank}),u=deploy();cast(u);near(u.mem.mlynarCapturedPct,.1);near(u.s.atk,u.base.atk*1.1);const s=data.operators[ID].skills[2].levels[rank-1];near(u.skill.bb.atk_scale,s.blackboard.find(x=>x.key==='atk_scale').value);}});
test('S3 source range extends actual acquisition to front2 and removes extension after ending',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{c:6});assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);ready(b,u);assert.ok(acquireTargets(b,u,effectiveProfile(u)).includes(e));shot(b,u);advance(b,.6);assert.ok(e.hp<100000);u.skill.end('manual');advance(b,.4);assert.equal(acquireTargets(b,u,effectiveProfile(u)).length,0);});
test('S3 one natural attack selects at most five source victims and emits exactly one main plus one rider each',()=>{const{b,deploy}=make({skill:2}),u=deploy(),es=Array.from({length:6},(_,i)=>enemy(b,{c:5+i*.02}));full(b,u);ready(b,u);u.atkCd=0;b.step();u.atkCd=1000;advance(b,.6);assert.equal(u.stats.attacks,1);assert.equal(es.filter(e=>e.hp<100000).length,5);assert.equal(b.receipts.filter(c=>c.source===u&&c.target.side==='enemy').length,10);for(const e of es.filter(e=>e.hp<100000)){assert.equal(receipts(b,e,'mlynar:s3').length,1);assert.equal(receipts(b,e,'mlynar:rider').length,1);}});
test('S3 every main victim uses the same held ATK; source BigAttack kills lower charge once after whole family',()=>{const{b,deploy}=make({skill:2}),u=deploy();full(b,u);ready(b,u);const atk=u.s.atk,main=atk*1.8*1.1,rider=atk*.12,e=enemy(b,{hp:rider+1}),z=enemy(b);enemy(b,{r:3,c:7});shot(b,u,[e,z]);advance(b,.6);assert.equal(e.alive,false);near(100000-z.hp,main+rider);near(u.mem.mlynarCapturedPct,3.9);near(u.s.atk,u.base.atk*4.9);});
test('S3 multiple main kills reduce captured coefficient in a batch with zero floor; rider kills do not count',()=>{const{b,deploy}=make({skill:2}),u=deploy();ready(b,u);const atk=u.s.atk,e=enemy(b,{hp:atk*.12+1}),z=enemy(b,{hp:atk*.12+1});shot(b,u,[e,z]);advance(b,.6);near(u.mem.mlynarCapturedPct,0);near(u.s.atk,u.base.atk);const{b:c,deploy:d}=make({skill:2}),v=d(),a=enemy(c,{hp:1});ready(c,v);shot(c,v,a);advance(c,.6);assert.equal(a.alive,false);near(v.mem.mlynarCapturedPct,.1);});
test('S3 rider uses current Mlynar ATK without Wanderer/other ally ATK, not target ATK',()=>{const{b,deploy}=make({skill:2},[KAZ]),u=deploy(),a=deploy(KAZ,1,1),e=enemy(b);ready(b,u);b.addBuff(u,{key:'foreign',mods:{atkPct:.5}});e.base.atk=99999;e.markDirty();const atk=u.s.atk;b.dealDamage(a,e,{amount:100,type:'phys',isAttack:true});near(100000-e.hp,100+atk*.12);const r=receipts(b,e,'mlynar:rider')[0];near(r.dmg.amount,atk*.12);assert.equal(r.dmg.applyWay,'none');assert.equal(r.dmg.isAttack,false);});
test('S3 rider requires live legal current source range and Kazimierz attack, not other factions/direct abilities',()=>{const{b,deploy}=make({skill:2},[KAZ,OTHER]),u=deploy(),a=deploy(KAZ,1,1),z=deploy(OTHER,1,2),e=enemy(b),far=enemy(b,{r:1,c:8});ready(b,u);for(const[source,target,isAttack]of[[z,e,true],[a,e,false],[a,far,true]]){const hp=target.hp;b.dealDamage(source,target,{amount:100,type:'true',isAttack});near(hp-target.hp,100);}b.addBuff(e,{key:'free',flags:{untargetable:true}});const hp=e.hp;b.dealDamage(a,e,{amount:100,type:'true',isAttack:true});near(hp-e.hp,100);});
test('T2 deployed global faction aura includes self and target-free/isolated/unhealable operators, excluding tokens and other factions',()=>{const{b,deploy}=make({},[KAZ,OTHER]),u=deploy(),a=deploy(KAZ,1,1),z=deploy(OTHER,1,2);b.addBuff(a,{key:'flags',flags:{untargetable:true,isolated:true,noHeal:true,healFree:true}});advance(b,.25);assert.ok(reflectMark(u));assert.ok(reflectMark(u,a));assert.ok(!reflectMark(u,z));a.kind='token';advance(b,.25);assert.ok(!reflectMark(u,a));a.kind='op';advance(b,.25);assert.ok(reflectMark(u,a));near(u.s.taunt,u.base.tauntLevel+1);});
test('T2 reflection is current Mlynar ATK times selected15/18percent without attack scale, DEF or RES',()=>{for(const[potential,scale]of[[1,.15],[5,.18]]){const{b,deploy}=make({potential},[KAZ]),u=deploy(),a=deploy(KAZ,1,1),e=enemy(b,{def:9999});advance(b,4.5);advance(b,.25);const atk=u.s.atk;b.dealDamage(e,a,{amount:100,type:'true'});near(100000-e.hp,atk*scale);const r=receipts(b,e,'mlynar:inverse')[0];assert.equal(r.source,u);assert.equal(r.dmg.type,'true');assert.equal(r.dmg.applyWay,'none');}});
test('T2 reflection excludes allied/sourceless damage, direct HP loss and elemental gauges',()=>{const{b,deploy}=make({},[KAZ]),u=deploy(),a=deploy(KAZ,1,1),e=enemy(b);advance(b,.25);b.dealDamage(null,a,{amount:1,type:'true'});b.dealDamage(u,a,{amount:1,type:'true'});b.loseHp(a,1,{source:e});b.dealDamage(e,a,{amount:1,type:'element',element:'burn'});near(e.hp,100000);});
test('death/withdrawal clears only owned faction marks/forms, preserves foreign aura, and redeployment starts zero',()=>{for(const why of['retreat','death']){const{b,deploy}=make({skill:2},[KAZ]),u=deploy(),a=deploy(KAZ,1,1);advance(b,5.5);ready(b,u);advance(b,.25);b.addBuff(a,{key:'mlynar:inverse:foreign'});assert.ok(reflectMark(u,a));if(why==='retreat')b.retreatOperator(ID);else b.kill(u);assert.ok(!reflectMark(u,a));assert.ok(a.findBuff('mlynar:inverse:foreign'));assert.equal(u.mem.regularFormVisual,null);b.bench[ID].readyAt=b.time;const v=deploy();assert.equal(v.mem.mlynarStacks,0);near(v.s.blockCnt,0);near(v.s.atk,v.base.atk);}});

test('S3 target-side NORMAL aura accepts source inverse reflection once without Wanderer or recursive ADDITION',()=>{const{b,deploy}=make({skill:2},[KAZ]),u=deploy(),a=deploy(KAZ,1,1),e=enemy(b);ready(b,u);advance(b,.25);const atk=u.s.atk;b.dealDamage(e,a,{amount:1,type:'true',isAttack:true});near(100000-e.hp,atk*(.15+.12));assert.equal(receipts(b,e,'mlynar:inverse').length,1);assert.equal(receipts(b,e,'mlynar:rider').length,1);near(receipts(b,e,'mlynar:inverse')[0].dmg.amount,atk*.15);assert.equal(u.stats.attacks,0);near(u.mem.mlynarCapturedPct,.1);});
test('reflection still retaliates outside S3 aura range without receiving the regional additional rider',()=>{const{b,deploy}=make({skill:2},[KAZ]),u=deploy(),a=deploy(KAZ,1,1),e=enemy(b,{r:1,c:8});ready(b,u);advance(b,.25);const atk=u.s.atk;b.dealDamage(e,a,{amount:1,type:'true'});near(100000-e.hp,atk*.15);assert.equal(receipts(b,e,'mlynar:rider').length,0);});
test('selected pre-receipt reflection mapping survives fully shielded/dodged incoming hits but not invulnerability',()=>{for(const how of['shield','dodge','invulnerable']){const{b,deploy}=make({},[KAZ]),u=deploy(),a=deploy(KAZ,1,1),e=enemy(b);advance(b,.25);if(how==='shield')b.addBuff(a,{key:'protect',shield:1000});else if(how==='dodge')b.addBuff(a,{key:'protect',mods:{dodgePhys:1}});else b.addBuff(a,{key:'protect',flags:{invulnerable:true}});const hp=a.hp,atk=u.s.atk;b.dealDamage(e,a,{amount:100,type:'phys'});near(a.hp,hp);near(100000-e.hp,how==='invulnerable'?0:atk*.15);}});
test('S3 chosen before-dodge rider mapping remains one current-ATK True output while fully dodged main stays zero',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);ready(b,u);b.addBuff(e,{key:'dodge',mods:{dodgePhys:1}});const atk=u.s.atk;shot(b,u,e);advance(b,.6);near(100000-e.hp,atk*.12);assert.equal(receipts(b,e,'mlynar:rider').length,1);near(u.mem.mlynarCapturedPct,.1);});
test('S3 acquired air victim keeps native MeleeAttack origin, so a MELEE-only barrier cancels main not NONE rider',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{fly:true});ready(b,u);b.addBuff(e,{key:'barrier',shieldHits:1,shieldApplyWays:['melee']});const atk=u.s.atk;shot(b,u,e);advance(b,.6);near(100000-e.hp,atk*.12);assert.equal(e.findBuff('barrier'),null);});
test('CAST release reselects current legal main targets without widening first-release INPUT direction',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b),z=enemy(b,{r:1,c:8});ready(b,u);shot(b,u,e);e.hidden=true;move(b,z,3,5);advance(b,.4);assert.equal(receipts(b,z).length,1);assert.equal(receipts(b,e).length,0);move(b,z,1,8);advance(b,.3);assert.equal(receipts(b,z).length,2);near(e.hp,100000);});
test('reaction control accepted inside first S2 receipt cancels the delayed tail even if shorter than one tick',()=>{const{b,deploy}=make({skill:1}),u=deploy(),e=enemy(b);ready(b,u);b.on('damaged',({source,target,dmg})=>{if(source===u&&target===e&&dmg.tags.includes('mlynar:s2'))b.applyStatus(u,'stun',{duration:.001});});shot(b,u,e);advance(b,.8);assert.equal(receipts(b,e).length,1);});
test('first S3 family cannot attack before source startup finishes, and completed duration restores idle behavior',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(u);u.atkCd=0;advance(b,.3);near(e.hp,100000);near(u.s.blockCnt,u.base.blockCnt);u.atkCd=1000;advance(b,u.skill.duration+.2);near(u.s.blockCnt,0);near(u.mem.mlynarCapturedPct,0);assert.equal(u.mem.mlynarStacks,1);near(u.s.atk,u.base.atk*1.05);assert.equal(u.skill.active,false);const hp=e.hp;u.atkCd=0;advance(b,.5);near(e.hp,hp);});
