// SPDX-License-Identifier: GPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import data from '../data/arkpedia-mvp.json' with { type: 'json' };
import evidence from '../data/arkpedia-rosa-prefabs.json' with { type: 'json' };
import { ROSA_OPERATORS as configs } from '../shared/arkpedia/rosa-operators.js';
import { StandardBattle } from '../server/sim/arkpedia.js';
import { recordFor, defaultBuild } from '../shared/arkpedia/loadout.js';
import { acquireTargets, effectiveProfile } from '../server/sim/ai.js';
import { prepareRosaSquad } from '../server/sim/content/arkpedia-rosa.js';
const ID='char_197_poca',FANG='char_123_fang';
const near=(a,z,e=1e-5)=>assert.ok(Math.abs(a-z)<e,`${a} != ${z}`);
const advance=(b,s)=>{for(let i=0;i<Math.ceil(s/b.dt-1e-9);i++)b.step();assert.deepEqual(b.errors,[]);};
const rows=p=>p.flatMap(r=>r.components.map(c=>({pathId:c.pathId,...c.data})));
function build(id,{skill=0,elite=null,rank=10,potential=1}={}){const op=data.operators[id];assert.ok(op,`Reviewed ${id} snapshot is required`);elite??=op.phases.length-1;rank=Math.min(rank,elite===2?10:elite===1?7:4);return{...defaultBuild(op),elite,level:op.phases[elite].maxLevel,skillId:op.skills[skill].id,skillRank:rank,potential};}
function make(opts={},more=[]){const src=structuredClone(data);src.stage.geometry.waves[0].spawns=[];src.stage.geometry.rows=19;src.stage.geometry.cols=21;src.stage.geometry.tileGrid=Array.from({length:19},()=>Array(21).fill(2));src.stage.battle.dp_per_second=0;const b=new StandardBattle(src,{operators:[build(ID,opts),...more.map(id=>build(id))]});b.autoFinish=false;b.recordEvents=true;b._received=[];b.on('damaged',c=>b._received.push(c));b.setViewport('fullscreen-workspace');b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));const deploy=(id=ID,row=3,col=4,dir='RIGHT')=>{b.addDp('arkpedia',99);const u=b.deployOperator(id,row,col,dir);assert.ok(u);u.atkCd=1000;u.skill.rule='NEVER';return u;};return{b,deploy};}
function enemy(b,{x=6,y=3,hp=100000,def=0,fly=false,weight=1}={}){const e=b.spawnEnemy('enemy_1007_slime',{pos:[y,x]});Object.assign(e.base,{maxHp:100000,def,res:0,moveSpeed:0,massLevel:weight});e.markDirty();void e.s;e.hp=hp;if(fly)e.motion='FLY';b.addBuff(e,{key:'test:pin',flags:{noMove:true,disarm:true}});b._buildEnemyIndex();return e;}
function move(b,e,x,y=3){e.x=x;e.y=y;e.tileR=y;e.tileC=x;b._enemiesDirty=true;b._buildEnemyIndex();}
function cast(b,u){u.skill.setSpTotal(u.skill.spCost);assert.equal(b.activateOperator(ID),true);u.atkCd=1000;}
function shot(b,u,e,s=1){assert.equal(b.forceAttack(u,Array.isArray(e)?e:[e]),true);u.atkCd=1000;advance(b,s);}
const hits=(b,u)=>b._received.filter(e=>e.source===u);
function firstFlight(b,u){let fired=0;const original=b.addProjectile.bind(b);b.addProjectile=p=>{if(p.source===u)fired++;return original(p);};for(let i=0;i<60&&!fired;i++)b.step();assert.deepEqual(b.errors,[]);assert.ok(fired>0);}

test('Rosa exact table/shared prefab, original attack events and retained link fields are source-backed',()=>{
 assert.deepEqual(Object.keys(configs),[ID]);assert.deepEqual(configs[ID].skillIds,['skcom_atk_up[3]','skchr_poca_2','skchr_poca_3']);assert.equal(evidence.frameParity,false);assert.equal(evidence.sourceBundles.length,5);
 for(const x of evidence.sourceBundles)assert.match(x.sha256,/^[0-9a-f]{64}$/);
 for(const face of['Front','Back']){const m=evidence.models[ID][face];assert.equal(m.sha256,evidence.officialSkeletonBindings[ID][face].sha256);near(m.hits.Attack[0],.533);near(m.durations.Skill_End,.933);}
 const skills=rows(evidence.skills.skchr_poca_3),main=skills.find(x=>x.pathId==='-9209906963622926832');assert.equal(main._waitForAttackEvent,0);near(main._preDelay,evidence.runtimeMapping.s3PreDelay);assert.equal(main._selectTargetTiming,0);assert.equal(main._waitForProjectileInvalid,1);assert.equal(main._waitForAnimEndWhenProjectileInvalid,1);near(main._minPostDelayWhenProjectileInvalid,.933);
 const proj=rows(evidence.projectiles.projectile_chr_poca_s3),link=proj.find(x=>x._keepHitTarget!=null);assert.equal(link._managedBySource,0);assert.equal(link._keepHitTarget,1);assert.equal(link._actionController._detachAllBuffsWhenStopped,1);near(link._keepAlreadyHitTime,1);near(link._linkDuration,10);assert.equal(link._lifeTimeType,2);
 const deck=rows(evidence.characters[ID]).find(x=>x._deckBuffs);assert.equal(deck._options.selector.filterTag,'student');assert.equal(deck._options.selector.excludeNotInHand,0);assert.equal(deck._deckBuffs[0].buff.attributes.attributeModifiers[0].formulaItem,1);assert.equal(evidence.tableContracts[ID].skills['skcom_atk_up[3]'].levels[0].prefabId,'skcom_atk_up');
});
test('all thirty ranks retain damage scales, target counts and selected per-link pulse duration',()=>{for(let skill=0;skill<3;skill++)for(let rank=1;rank<=10;rank++){const{b,deploy}=make({skill,rank}),u=deploy(),es=Array.from({length:5},(_,i)=>enemy(b,{x:6+i*.12,weight:5-i,def:100})),level=data.operators[ID].skills[skill].levels[rank-1];assert.equal(u.skill.id,configs[ID].skillIds[skill]);near(u.skill.spCost,level.spData.spCost);cast(b,u);const atk=u.s.atk,bb=u.skill.bb;
 if(skill<2){const targets=acquireTargets(b,u,effectiveProfile(u));assert.equal(targets.length,skill===1?2:1);shot(b,u,targets,1);for(let i=0;i<5;i++)near(100000-es[i].hp,i<targets.length?atk-100*(i<3?.4:1):0);assert.equal(hits(b,u).length,targets.length);}
 else{advance(b,bb.hit_duration+2);assert.equal(u.skill.active,false);for(let i=0;i<5;i++)near(100000-es[i].hp,i<bb.max_target?bb.hit_duration*(atk-100*(i<3?.4:1)):0);assert.equal(hits(b,u).length,bb.max_target*bb.hit_duration);}
}});
test('ordinary normal targeting selects one current heaviest enemy and one physical ranged projectile',()=>{const{b,deploy}=make(),u=deploy(),light=enemy(b,{weight:1}),heavy=enemy(b,{x:6.1,weight:4}),flying=enemy(b,{x:6.2,weight:2,fly:true});assert.deepEqual(acquireTargets(b,u,effectiveProfile(u)),[heavy]);shot(b,u,heavy);near(100000-heavy.hp,u.s.atk);near(light.hp,100000);near(flying.hp,100000);assert.equal(hits(b,u).length,1);assert.equal(hits(b,u)[0].dmg.isAttack,true);assert.equal(hits(b,u)[0].dmg.applyWay,'ranged');});
test('weight modifiers affect heaviest selection and talent GE3 at impact rather than base weight',()=>{const{b,deploy}=make(),u=deploy(),a=enemy(b,{weight:4,def:500}),z=enemy(b,{x:6.1,weight:3});b.addBuff(a,{key:'test:weight',mods:{massFlat:-2}});assert.deepEqual(acquireTargets(b,u,effectiveProfile(u)),[z]);move(b,z,15);shot(b,u,a);near(100000-a.hp,u.s.atk-500);b.removeBuff(a,'test:weight');const before=a.hp;shot(b,u,a);near(before-a.hp,u.s.atk-200);});
test('normal CAST selects the entering heaviest victim and ignores leaving or target-free pending input',()=>{for(const state of['leave','free']){const{b,deploy}=make(),u=deploy(),old=enemy(b,{weight:5}),next=enemy(b,{x:15,weight:6});b.forceAttack(u,[old]);u.atkCd=1000;if(state==='leave')move(b,old,15);else b.addBuff(old,{key:'test:free',flags:{untargetable:true}});move(b,next,6);advance(b,1);near(old.hp,100000);near(100000-next.hp,u.s.atk);}});
test('normal original .533 release honors source animation cap1 and slows with decreased ASPD',()=>{for(const aspd of[100,200,50]){const{b,deploy}=make(),u=deploy(),e=enemy(b);b.addBuff(u,{key:'test:aspd',mods:{aspd:aspd-100}});let born=0;const original=b.addProjectile.bind(b);b.addProjectile=p=>{born++;return original(p);};b.forceAttack(u,[e]);u.atkCd=1000;advance(b,aspd===50?1:.5);assert.equal(born,0);advance(b,.1);assert.equal(born,1);}});
test('S2 natural loop creates one arrow for each of two heaviest victims without duplicate splash',()=>{const{b,deploy}=make({skill:1}),u=deploy(),es=[enemy(b,{weight:1}),enemy(b,{x:6.1,weight:4}),enemy(b,{x:6.2,weight:3})];cast(b,u);u.atkCd=0;b.step();u.atkCd=1000;advance(b,1);near(es[0].hp,100000);assert.equal(hits(b,u).length,2);assert.equal(u.stats.attacks,1);assert.ok(es[1].hp<100000&&es[2].hp<100000);});
test('Bone Piercer promotion only ignores DEF from weight3, and cleanly composes with other penetration',()=>{for(const elite of[0,1,2]){const{b,deploy}=make({elite}),u=deploy(),e=enemy(b,{weight:3,def:500});b.addBuff(u,{key:'test:pen',mods:{defIgnorePct:.1}});shot(b,u,e);near(100000-e.hp,u.s.atk-500*(1-.1-(elite===2?.6:elite===1?.4:0)));assert.equal(b._hooks.hit?.filter(x=>!x.removed).length??0,0);}});
test('born ordinary arrow retains sole victim and source passive after source withdrawal',()=>{const{b,deploy}=make(),u=deploy(),e=enemy(b,{x:7,weight:4,def:500}),other=enemy(b,{x:15,weight:5});b.forceAttack(u,[e]);u.atkCd=1000;firstFlight(b,u);move(b,other,7.1);b.retreat(u);advance(b,1);near(100000-e.hp,u.s.atk-200);near(other.hp,100000);});
test('Ideal Student applies from bench and support, with promotion and potential selection',()=>{for(const[elite,potential,pct]of[[1,1,0],[2,1,.08],[2,5,.1]]){const src=structuredClone(data);src.stage.geometry.waves[0].spawns=[];const other='char_115_headbr',op=data.operators[other];assert.ok(op);const b=new StandardBattle(src,{operators:[build(other),build(ID,{elite,potential})]});b.autoFinish=false;b.setViewport('fullscreen-workspace');b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));b.addDp('arkpedia',99);const u=b.deployOperator(other,3,4,'RIGHT');assert.ok(u);u.atkCd=1000;near(u.s.atk,u.base.atk*(1+pct));assert.equal(b.bench[ID].unit,null);}});
test('maxed support Rosa supplies the selected potential5 squad buff from bench',()=>{const src=structuredClone(data);src.stage.geometry.waves[0].spawns=[];const other='char_115_headbr';const b=new StandardBattle(src,{operators:[build(other)],support:{id:ID,skillId:configs[ID].skillIds[0]}});b.autoFinish=false;b.setViewport('fullscreen-workspace');b.grid.tiles=b.grid.tiles.map(t=>({...t,height:'LOW',build:'ALL',pass:'ALL'}));b.addDp('arkpedia',99);const u=b.deployOperator(other,3,4,'RIGHT');assert.ok(u);near(u.s.atk,u.base.atk*1.1);assert.equal(b.bench[ID].unit,null);});
test('Ideal Student percentage is additive with skill/external ATK and excludes other factions',()=>{const{b,deploy}=make({skill:0},[FANG]),u=deploy(),other=deploy(FANG,3,3);near(u.s.atk,u.base.atk*1.08);near(other.s.atk,other.base.atk);b.addBuff(u,{key:'test:atk',mods:{atkPct:.2}});cast(b,u);near(u.s.atk,u.base.atk*(1+.08+.2+1));});
test('named squad preparation is idempotent, strongest and reversible without removing another modifier',()=>{const r=recordFor(build(ID),data);r.arkpedia.modifiers.atkPct=.2;const records={[ID]:r};prepareRosaSquad(records);prepareRosaSquad(records);near(r.arkpedia.modifiers.atkPct,.28);r.talents.find(t=>t.prefabKey==='2').bb.atk=.1;prepareRosaSquad(records);near(r.arkpedia.modifiers.atkPct,.3);r.talents=r.talents.filter(t=>t.prefabKey!=='2');prepareRosaSquad(records);near(r.arkpedia.modifiers.atkPct,.2);});
test('S3 native predelay emits at legal CAST victims and holds no-SP through end animation',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{weight:3});cast(b,u);assert.equal(u.mem.regularFormVisual.clip,'Skill_Begin');advance(b,.5);near(e.hp,100000);assert.equal(u.skill.gainSp(10,'test'),0);advance(b,.35);assert.ok(e.hp<100000);assert.equal(u.mem.regularFormVisual.clip,'Skill_Loop');advance(b,8.15);assert.equal(u.skill.active,true);assert.equal(u.mem.regularFormVisual.clip,'Skill_End');assert.equal(u.skill.gainSp(10,'test'),0);advance(b,1);assert.equal(u.skill.active,false);assert.equal(u.mem.regularFormVisual,null);assert.equal(Boolean(u.s.flags.disarm),false);assert.ok(u.skill.gainSp(1,'test')>0);});
test('S3 CAST rechecks all input membership, target-free and weight changes during predelay',()=>{const{b,deploy}=make({skill:2,rank:1}),u=deploy(),old=enemy(b,{weight:6}),z=enemy(b,{x:6.1,weight:5}),next=enemy(b,{x:15,weight:7});cast(b,u);move(b,old,15);b.addBuff(z,{key:'test:free',flags:{untargetable:true}});move(b,next,6);advance(b,1);near(old.hp,100000);near(z.hp,100000);assert.ok(next.hp<100000);assert.equal(hits(b,u).length,1);});
test('S3 sub-frame control cancels only unborn cast and no arrows reappear after recovery',()=>{for(const immune of[false,true]){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);if(immune)u.def.immune.add('stun');cast(b,u);b.applyStatus(u,'stun',{duration:.001});advance(b,1);assert.equal(hits(b,u).length,immune?1:0);assert.equal(u.skill.active,immune);}});
test('S3 no legal victim spends the skill and leaves no held SP or cast state after source end window',()=>{const{b,deploy}=make({skill:2}),u=deploy();cast(b,u);advance(b,1);assert.equal(u.skill.active,true);assert.equal(u.skill.gainSp(3,'test'),0);advance(b,.7);assert.equal(u.skill.active,false);assert.equal(Boolean(u.s.flags.disarm),false);assert.equal(u.mem.regularFormVisual,null);assert.ok(u.skill.sp<u.skill.spCost);});
test('each harpoon retains its own original victim, and one death does not terminate surviving links',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=enemy(b,{weight:4}),z=enemy(b,{x:6.1,weight:3}),replacement=enemy(b,{x:15,weight:5});cast(b,u);advance(b,1);assert.equal(a.s.flags.bind,true);assert.equal(z.s.flags.bind,true);b.kill(a);assert.ok(!a.findBuff(`rosa:harpoon:${u.id}:1:${a.id}`));move(b,replacement,6);advance(b,2);assert.equal(u.skill.active,true);near(replacement.hp,100000);assert.ok(hits(b,u).filter(x=>x.target===z).length>=3);});
test('all original victims dying ends links early but retains the full source post-end no-SP window',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=enemy(b);cast(b,u);advance(b,1);b.kill(a);assert.equal(u.mem.regularFormVisual.clip,'Skill_End');assert.equal(u.skill.active,true);assert.equal(u.skill.gainSp(5,'test'),0);advance(b,1);assert.equal(u.skill.active,false);});
test('temporary target disappearance skips pulses without retargeting or a queued burst on return',()=>{const{b,deploy}=make({skill:2}),u=deploy(),a=enemy(b),z=enemy(b,{x:15});cast(b,u);advance(b,1);a.hidden=true;move(b,z,6);advance(b,3);const n=hits(b,u).length;a.hidden=false;advance(b,.1);assert.equal(hits(b,u).length,n);advance(b,.9);assert.equal(hits(b,u).length,n+1);near(z.hp,100000);advance(b,5);assert.equal(u.skill.active,false);assert.equal(Boolean(a.s.flags.bind),false);});
test('harpoon expiry detaches only its owned bind and preserves another source bind',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(b,u);advance(b,1);b.applyStatus(e,'bind',{key:'test:other',duration:20});advance(b,9);assert.equal(u.skill.active,false);assert.ok(e.findBuff('test:other'));assert.equal(e.s.flags.bind,true);assert.equal(e.buffs.filter(x=>x.key.startsWith('rosa:harpoon')).length,0);});
test('withdrawal before release cancels unborn harpoons, while released unmanaged links retain original lifetime',()=>{for(const released of[false,true]){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{weight:3,def:300});cast(b,u);if(released)advance(b,1);else advance(b,.2);b.retreat(u);const before=hits(b,u).length, hp=e.hp, atk=u.s.atk;advance(b,3);assert.equal(hits(b,u).length,released?before+3:0);near(hp-e.hp,released?3*(atk-120):0);advance(b,6);assert.equal(e.buffs.filter(x=>x.key.startsWith('rosa:harpoon')).length,0);}});
test('target dying or disappearing before original harpoon flight impact cannot hit a replacement',()=>{for(const state of['dead','hidden']){const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:7}),z=enemy(b,{x:15});cast(b,u);firstFlight(b,u);if(state==='dead')b.kill(e);else e.hidden=true;move(b,z,7);advance(b,2);near(z.hp,100000);assert.equal(hits(b,u).length,0);assert.equal(u.skill.active,false);}});
test('normal attack resumption after S3 end produces a sole original-speed arrow rather than another link pulse',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b);cast(b,u);advance(b,10);const before=hits(b,u).length;shot(b,u,e,1);assert.equal(hits(b,u).length,before+1);assert.equal(hits(b,u).at(-1).dmg.isSkill,false);assert.equal(Boolean(e.s.flags.bind),false);});

test('withdrawn born harpoon flight fizzle cleans its independent watcher and unowned death hook',()=>{const{b,deploy}=make({skill:2}),u=deploy(),e=enemy(b,{x:7});const before=b._hooks.death?.filter(h=>!h.removed).length??0;cast(b,u);firstFlight(b,u);b.retreat(u);e.hidden=true;advance(b,2);assert.equal(hits(b,u).length,0);assert.ok(u.mem.rosaHarpoons.links.every(x=>x.done));assert.equal(b._hooks.death?.filter(h=>!h.removed).length??0,before);assert.equal(e.buffs.filter(x=>x.key.startsWith('rosa:harpoon')).length,0);});
